blobstore/gcsblobstore.py, tests/test_gcsblobstore.py
Added unit test that verifies a bucket's existence.
=> Add skeleton for Google Cloud Store driver

tests/test.py
=> rename test_dss_api to test_file_api

dss-api.yml, dss/api/bundles.py, tests/test.py
1) Add `list_versions`, which just returns a list of versions.
2) Given a bundle UUID+version, include a list of files (i.e., `file_version`)
=> Flesh out the bundle api.

dss-api.yml
Should be POST/PUT to /files/<uuid> going forward.
=> [easy] remove POST to /files

dss-api.yml, dss/__init__.py
It's the one that's going to be required, so for readability reasons, I'm moving it up.
=> [easy] reorder UUID parameter to the top.

dss-api.yml
=> writer-> creator

dss-api.yml, dss/api/files.py
MD5 is not truly supported by S3
=> switch MD5 to S3-etag

tests/test.py
This allows us to build simple test statements.  The next diff in this stack will refactor the existing tests to use the new facility.
=> skeleton for assert_response

dss-api.yml
1. move description up.
2. add patterns.
3. md5 -> s3_etag
=> update the specs for common metadata

dss/blobstore/__init__.py, dss/blobstore/gcs.py, dss/blobstore/s3.py, tests/test_blobstore.py, tests/test_gcsblobstore.py, tests/test_s3blobstore.py
Added test to retrieve metadata for known blobs.
=> Method to retrieve metadata for an object.

dss/blobstore/__init__.py, dss/blobstore/s3.py, tests/test_s3blobstore.py
This is the same as #70, which I accidentally closed.  Oops!
=> API for generating a presigned url and test for it.

tests/test_s3blobstore.py, tests/test_s3hcablobstore.py
All the deprecated messages were getting to me.  Hard to find actual errors.
=> assertEquals -> assertEqual

tests/test_gcsblobstore.py, tests/test_s3blobstore.py, tests/test_s3hcablobstore.py, tests/utils.py
=> Clean up the fetching of bucket env variables.

dss/blobstore/__init__.py, dss/blobstore/gcs.py, dss/blobstore/s3.py, tests/test_s3hcablobstore.py
Since we decided on using the bucket term, let's stick with it everywhere.
=> rename container -> bucket

dss/api/files.py, dss/config.py, dss/hcablobstore/__init__.py, tests/test.py
Retrieve the file from s3://hca-dss-test-src/test_good_source_data and uploaded it.
I visually confirmed that the file metadata + blob seems to have been correctly formed on S3.
=> implementation of PUT /files/{uuid}

tests/test.py
Conditional on DSS_RUN_LONG_TESTS being set.
=> Sync daemon: add GCS readback test

tests/infra.py, tests/test.py, tests/test_sync.py
1. move sync tests to its own module.
2. move the code to fire up verbose logging to its own module.
=> Clean up tests

dss-api.yml, dss/api/files.py, tests/test_file.py
Removed a bunch of the old tests that merely verified the API was alive and replaced them with somewhat meaningful tests.
=> API to get files!

.travis.yml, chalice/.chalice/config.json, chalice/Makefile, daemons/Makefile, daemons/dss-index/.chalice/config.json, daemons/dss-sync/.chalice/config.json, daemons/dss-sync/app.py, daemons/invoke_lambda.sh
- Inject GCS credentials into lambda deployment packages
- Add test code in deployment routine
- Fix typos in original code not covered by tests
=> Fixups for Lambda daemons that didn't have integration tests

dss-api.yml, dss/api/files.py
This is to make it consistent with bundles.
=> Move version field into the query string.

dss-api.yml, dss/api/bundles.py, dss/hcablobstore/__init__.py, tests/test_bundle.py
Running the unit test writes the following bundle to the store:
```
{"format": "0.0.1", "version": "2017-06-20T21:41:25.793628Z", "files": [{"name": "LICENSE", "uuid": "f3926590-5f38-429c-a024-63bab88e97fe", "version": "2017-06-20T21:41:23.811824Z", "content-type": "text/plain", "indexed": false, "crc32c": "e16e07b9", "s3-etag": "3b83ef96387f14655fc854ddc3c6bd57", "sha1": "2b8b815229aa8a61e483fb4ba0588b8b6c491890", "sha256": "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30"}], "creator_uid": 12345}
```
=> add PUT /bundles api.

dss/blobstore/gcs.py, tests/test_blobstore.py, tests/test_s3blobstore.py
Moved test from `test_s3blobstore.py` to `test_blobstore.py` since both platform are now supported.
=> implement listing of a bucket for GCSBlobStore

dss/blobstore/__init__.py, dss/blobstore/s3.py, tests/test_s3blobstore.py
=> method to pull the cloud-provided checksum.

dss/hcablobstore/__init__.py, dss/hcablobstore/s3.py, tests/test_s3hcablobstore.py
We don't need this method any more.
=> remove `copy_blob_from_staging`

dss/blobstore/gcs.py, dss/hcablobstore/__init__.py, dss/hcablobstore/gcs.py, tests/test_blobstore.py, tests/test_gcshcablobstore.py
Add test that apparently was never written
=> GCS support of copy_blob

dss-api.yml, dss/api/files.py, dss/config.py
=> Basic setup for the files/bundles/their unit tests to communicate with GCS.

dss/config.py, tests/test_bundle.py, tests/test_file.py
Switch the override mechanism to use the BucketConfigs
=> introduce the notion of prod/test/test_fixture configs

dss-api.yml, dss/api/files.py, dss/blobstore/gs.py, dss/config.py, tests/test_bundle.py, tests/test_file.py, tests/test_sync.py
It's called Google Cloud Platform.
=> Rename GCS to GCP.

tests/infra.py, tests/test_api.py
Upload files, create bundle, retrieve bundle, retrieve files
=> Quick API file/bundle full lifecycle test

Makefile
See https://codecov.io/gh/HumanCellAtlas/data-store for pretty coverage graphs.
=> Enable coverage

chalice/app.py, daemons/dss-index/app.py, daemons/dss-sync/app.py, dss-api, dss/__init__.py, dss/config.py, dss/events/handlers/sync.py, environment, iam/policy-templates/ci-cd.json, scripts/authorize_aws_deploy.sh, tests/test_api.py, tests/test_bundle.py, tests/test_file.py
1. Dev points to a separate bucket.
2. tests continue running against org-humancellatlas-dss-test
=> Add a dev stage

README.md, chalice/build_deploy_config.sh, daemons/build_deploy_config.sh, daemons/invoke_lambda.sh, dss/config.py, environment, iam/policy-templates/ci-cd.json, iam/policy-templates/dss-index-lambda.json, iam/policy-templates/dss-lambda.json, iam/policy-templates/dss-sync-lambda.json, scripts/authorize_aws_deploy.sh, tests/daemons/sample_s3_bundle_created_event.json.template, tests/sample_data_loader.py, tests/test_api.py, tests/test_bundle.py, tests/test_file.py, tests/test_gsblobstore.py, tests/test_gshcablobstore.py, tests/test_indexer.py, tests/test_s3blobstore.py, tests/test_s3hcablobstore.py, tests/test_sync.py
Also word swapped DEV_BUCKET -> BUCKET_DEV
This facilitates the appending of "_${DEPLOYMENT_STAGE}" to variables to get the bucket name variable.
=> [easy] word swap TEST_BUCKET -> BUCKET_TEST

chalice/app.py, chalice/build_deploy_config.sh, daemons/build_deploy_config.sh, daemons/dss-index/app.py, daemons/dss-sync/app.py, daemons/invoke_lambda.sh, dss-api, dss/config.py, environment, iam/policy-templates/ci-cd.json, scripts/authorize_aws_deploy.sh
1. Bucket configs are "normal" (DSS_S3_BUCKET), "test" (DSS_S3_BUCKET_TEST), and "test_fixture" (DSS_S3_BUCKET_TEST_FIXTURES)
2. Remove logic to infer which env variable based on stage.
This should address #228.
=> Allow deployments to custom stages.

dss/util/__init__.py, tests/infra.py, tests/test_api.py, tests/test_bundle.py, tests/test_file.py
It turns out to be more useful than anticipated, so moving it out of the tests dir.
=> move URLBuilder.

tests/test_sync.py
Bucket config should come from the config module.
=> fix sync test

dss-api.yml, dss/api/bundles.py, dss/config.py, tests/test_bundle.py
=> provide direct access URLs if directurls=true

tests/infra.py, tests/test_api.py, tests/test_bundle.py, tests/test_file.py, tests/test_search.py
=> remove DSSAsserts.setup()

dss-api.yml, dss/__init__.py, dss/error.py, tests/test_file.py
Apparently, there's an RFC for everything under the sun.
=> Made the error type compliant with RFC 7807.

tests/infra.py, tests/test_file.py
Modified the negative test in tests/test_file.py to take advantage of the new API.
=> Fold the testing of error responses into assert*Response

dss/api/search.py, dss/api/subscriptions.py, dss/events/handlers/index.py, dss/util/__init__.py, dss/util/es.py
* Move es utility functions into util/es.py module. 
* Change imports to reflect that. 
* Add get_elasticsearch_index that checks and if not created, makes the index. 
* Tests will be integrated when the endpoint logic is implemented.
* connect_elasticsearch will call a connection manager in the future @mikebaumann
=> Subscriptions util

tests/infra.py, tests/test_api.py, tests/test_bundle.py, tests/test_file.py
Thanks to @mackey22 for the suggestion.
=> simpler return values from assert*Response

daemons/dss-sync/Readme.md, daemons/dss-sync/app.py, dss/events/handlers/sync.py, dss/util/aws/__init__.py, dss/util/aws/_boto3_loader.py, dss/util/aws/clients.py, dss/util/aws/resources.py, dss/util/streaming.py, iam/policy-templates/dss-sync-lambda.json, tests/test_sync.py, tests/test_utils.py
Also introduce a few AWS/boto3 utility functions.
Fixes #195.
=> Sync daemon: parallelize copying of large objects between S3 and GS.

dss-api.yml, dss/__init__.py, dss/api/subscriptions.py, dss/config.py, environment, tests/sample_index_doc.json, tests/sample_percolate_query.json, tests/test_subscriptions.py
* Full endpoint coverage for Subscriptions api
* Full testing of functionality
* Upload files for sample index and query docs for testing
* Manage whitelisted emails with contextmanager and config class
=> Subscriptions API functionality

iam/policy-templates/dss-lambda.json
Needed so people can remove their own notifications!
=> Allow for EsHttpDelete by the dss-lambda

dss/events/handlers/index.py, tests/test_indexer.py
Added HTTP server to verify subscription notifications for matched documents.
Corrected notification payload content type to be application/json.
=> Subscription notification test and fix

dss/events/chunkedtask/__init__.py, dss/events/chunkedtask/base.py, dss/events/chunkedtask/constants.py, dss/events/chunkedtask/runner.py, tests/test_chunkedtask.py
Three major components:
1. There is an abstract class `ChunkedTask` that specifies the work.  Calls to `run_one_unit()` will run one unit of work.  Calls to `get_state()` will serialize the state for subsequent execution.
2. There is an abstract class `ChunkedTaskRuntime` that specifies the environment for the work.  Calls to `get_remaining_time_in_millis()` should return the amount of time left in this current execution environment.
3. There is a class `ChunkedTaskRunner` that orchestrates the execution.
Add unit tests to test ChunkedTaskRunner.
=> Basic framework to specify work that can be broken up.

tests/test_indexer.py
The indexer test test_indexed_file_access_error formerly removed the a file blob associated with a test bundle to verify the indexer handles this case as expected. However, the file blob was for a commonly used test file, and intermittent test failures were occurring when run using a shared test bucket. The test was changed to instead create a bundle manifest entry such that the file blob
reference is invalid. The code and test semantics are the same.
This is the same as #316 but with a few stylistic fixes.
=> Fix intermittent test failure related to file blob removal

environment
=> Add Broad Institute IAM account to auth whitelist

dss/blobstore/s3.py, tests/test_s3blobstore.py
Allows a user to specify the starting part number from where we search and the number of results.
Adds a ton of tests to verify the results.
=> Utility function to find the next N missing parts of a multipart upload.

dss/events/chunkedtask/awscopyclient.py, tests/test_awscopyclient.py
Added a simple unit test that does a multipart copy and verifies that the output etag matches.
=> Implement AWS multipart copy as a chunked task.

daemons/build_deploy_config.sh, iam/policy-templates/dss-chunked-task-lambda.json
1. r/w from the dss bucket for its stage and the test bucket.
2. r/o from everywhere else.
=> S3 policies for the chunked task lambda.

dss/events/chunkedtask/_awsimpl.py, dss/events/chunkedtask/_awstest.py, dss/events/chunkedtask/aws.py, tests/test_chunkedtask.py
=> [easy] Move test task and runtime to its own file.

dss/events/chunkedtask/awscopyclient.py, tests/test_awscopyclient.py
1. next_part is not advanced.
2. there's an off-by-one where if we run out of items in the work queue and we haven't copied the last chunk, then we don't search for more uncopied parts.
=> Test to expose a bug and a hilarious bugfix.

dss/events/chunkedtask/awscopyclient.py, tests/test_awscopyclient.py
Add test to cover this use case.
=> Adapt AWS Copy Client to copy blobs smaller than a multipart object.

tests/infra.py
Now that the errors have nice formats, it can often have useful information for debugging like stacktraces.  Print it out if an assertion fires.
=> Pretty-print the response json if an assertion fires.

dss/api/files.py
This will make the code to copy small objects synchronously cleaner.
=> Make the copy type explicit.

tests/fixtures/cloud_uploader.py
Use the chunk size calculation code in #288.
=> Cloud uploader should use multipart upload.

dss/api/files.py, tests/infra.py, tests/test_file.py
1. Files smaller or equal to `dss.api.files.SYNC_COPY_LIMIT` will be copied synchronously.
2. Added a flag to `upload_file_wait` indicating whether we should expect a synchronous copy, an asynchronous copy, or if we don't care.
3. Added a test case to upload a file larger than `dss.api.files.SYNC_COPY_LIMIT` and validate whether it was done synchronously.
=> Upload small files synchronously.

dss-api.yml, dss/api/search.py, tests/test_search.py
Removed the GET /search route, as requested by kislyuk.
=> Removed GET /search route

dss/events/chunkedtask/aws.py
This makes it easier to find error information rather than scraping through the lambda logs.
=> Catch all exceptions and log them in the chunked task dispatch method.

dss/util/aws/__init__.py, dss/util/aws/logging.py, iam/policy-templates/ci-cd.json, tests/test_logging.py
- Logs to cloudwatch.
- Creates the group and stream, if necessary.
- Retrieves the uploadSequenceToken to log to existing streams.
- Adds test to verify most of the functionality.  The key functionality that is not tested is the creation of a logging group.  Rationale: There's a hard limit on the number of test groups.  If this test goes wild, it might do bad things to the account.
Connects to #319 
=> Add a simple logging facility.

dss/events/chunkedtask/_awsimpl.py, requirements-dev.txt, requirements.txt, requirements.txt.in
Watchtower is logging duplicate statements.  Switching to the simple logger seems to eliminate the issue.
Connects to #319 
=> switch logging to the simple logger.

daemons/Makefile, daemons/dss-chunked-task/app.py, dss/events/chunkedtask/_awsimpl.py, dss/events/chunkedtask/aws.py, dss/events/chunkedtask/awsconstants.py, iam/policy-templates/dss-chunked-task-fasttest-lambda.json, iam/policy-templates/dss-chunked-task-s3_copy-lambda.json, iam/policy-templates/dss-chunked-task-s3_copy_write_metadata-lambda.json, scripts/get_all_dss_chunked_task_clients.py
Automatically builds makefile rules from the client list, and rewrites the config for each separate client.
Connects to #319 
=> Separate lambdas for each chunked-worker client.

dss/events/chunkedtask/_awsimpl.py, dss/events/chunkedtask/aws.py, dss/events/chunkedtask/awsconstants.py, iam/policy-templates/ci-cd.json, tests/test_chunkedtask.py
=> Separate logging groups for each chunked worker client.

tests/test_chunkedtask.py
=> return result through the work_complete_callback

tests/chunked_worker.py, tests/test_s3copyclient.py
=> [easy] move the stingy runtime to a common area.

dss/api/files.py, dss/events/chunkedtask/_awsimpl.py, dss/events/chunkedtask/_awstest.py, dss/events/chunkedtask/aws.py, dss/events/chunkedtask/base.py, dss/events/chunkedtask/runner.py, dss/events/chunkedtask/s3copyclient.py, tests/chunked_worker.py, tests/test_chunkedtask.py, tests/test_s3copyclient.py
This is the megadiff version.  I'll PR separate versions if you think that's easier to read. :)
=> Allow chunked tasks to fork off work.

tests/chunked_worker.py, tests/test_chunkedtask.py, tests/test_s3copyclient.py
=> Improve TestStingyRuntime so it can save a mapping of task id -> task

tests/test_subscriptions.py
Added test cases for GCP subscribe.
Connects to #348
=> Added Test Cases for GCP Subscribe

dss-api.yml, dss/api/search.py, tests/test_search.py
Added support for replica in search API.
Connects to #348
=> Added Support for Replica in Search API

tests/test_search.py
=> Added Test Cases for GCP Search

dss-api.yml, dss/api/subscriptions.py, dss/events/handlers/index.py, tests/smoketest.py, tests/test_indexer.py, tests/test_search.py, tests/test_subscriptions.py
=> Renamed query to es_query for subscription and notification in the dss-api

chalice/app.py
=> Log some data about each query so we can trace the execution of requests

dss/__init__.py, tests/test_bundle.py
Connexion immediately calls its internal error handler when parameter or body validation fails.  We want to manage the error handling so the error message fits our formatting.
=> Handle parameter and body validation errors with our code.

dss/api/subscriptions.py, tests/test_subscriptions.py
- Removed undefined values from log messages
- Added useful information to log messages
- Added tests cases to verify exception.
- connects to #459
=> Correcting Logic Error

chalice/chalicelib/index.html
@csweaver says this is better.
=> upgrade to 3.2.1 of swagger ui.

dss-api.yml, dss/api/bundles.py, dss/api/files.py, dss/error.py
see https://github.com/HumanCellAtlas/data-store/pull/432#discussion_r138255838
=> mandate replica.

.travis.yml, Makefile
This reduces the time it take to execute our tests suite.
connects to #460
=> Running tests in parallel

tests/test_file.py
We need a relatively specialized set of parameters, and I don't want to make `infra.upload_file_wait` too complicated.  Extract out the synchronous code path.
This is a straight refactor and introduces no new functionality.
=> Refactor the upload file code path.

dss/api/bundles.py, dss/api/files.py, tests/test_bundle.py, tests/test_file.py
=> Use DSSException to signal not-found errors

dss-api.yml, dss/api/search.py, dss/util/es.py, requirements-dev.txt, requirements.txt, requirements.txt.in, tests/infra.py, tests/test_search.py
- Added per_page and _scroll_id to dss-api.yml
- next_url is returned by search post to retrieve the next results
- connects to #376
=> Added Pagination Support

dss-api.yml, dss/api/search.py, tests/smoketest.py, tests/test_search.py
Connects to #212
- Added smoketest case to use format raw.
- updated test search to validate new raw format
Bundle metadata is return with the search results when format=raw. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html
=> Multiple result views supported for search

tests/test_standalone_script.py
=> Unit test to ensure that the standalone script is not broken.

chalice/app.py, tests/test_exptime.py
This allows the CLI to test the code for retrying operations.
Depends on #562.
Connects to #399
=> Fake a 504 response with a given probability if a cookie is present.

dss/util/es.py, tests/infra/server.py, tests/test_indexer.py, tests/test_search.py, tests/test_standalone_script.py, tests/test_subscriptions.py
Looks like travis is choking on localhost.  I suspect it's binding to ipv6, and that's not really working great.
=> Explicitly code 127.0.0.1 in place of localhost.

tests/test_indexer.py
This shaves test run time from 420s to 275s.
=> Upload the test bundle only once per replica.

dss-api.yml, dss/api/bundles.py, dss/api/files.py, tests/test_bundle.py, tests/test_file.py
Size metadata read on file/bundle get
Merge requires nuking/re-initialization of existing dss deployments.
Connects to #471
=> Include size in manifests GET

dss-api.yml, dss/hcablobstore/__init__.py, tests/infra/storage_mixin.py, tests/test_indexer.py
=> Remove remaining references to hca-dss-content-type.

dss/events/handlers/index.py
=> less strict parsing of content-type in metadata indexer

iam/policy-templates/ci-cd.json
=> Allow Travis to manage state machines

README.md
Just some things I ran into while working through the README.
Manually test the modified setup steps once.
=> README.md improvements (spelling, missing steps, etc.)

README.md
Please do not unwrap lines. Please wrap lines at 80 or 120 chars at your discretion.
This is a fixup for #625
=> Fix line wrapping

requirements-dev.txt, requirements-dev.txt.in
Brian, sth I stumbled across today.
=> Add version constraint to domovoi dependency

iam/policy-templates/ci-cd.json, requirements-dev.txt, requirements-dev.txt.in, requirements.txt
Unbreaks master.
Deployed locally while impersonating Travis.
=> Update CI-CD IAM policy template, pull in sfn deploy update

requirements-dev.txt.in, requirements.txt.in
Continued from #683 which was merged into the wrong branch by mistake.
=> unpin requirements.txt and requirements-dev.txt

requirements-dev.txt
=> Sync version pins between dev and runtime deps (fixes #686)

dss/stepfunctions/__init__.py
Invoking step functions is going to be a common idiom, so let's have a library function to do it.
Connects to #592
=> Simple method to invoke a step function.

dss/api/bundles/checkout.py
Use the method provided by #701
=> Refactor the SFN invoke code used in the checkout service.

dss/stepfunctions/__init__.py
Utility methods needed for visitation batch processor, may
be useful for other step function consumers.
connects to #539
Tested locally through visitation batch processor integration tests. Will be tested through smoketest in the future.
=> A few extra step function utility methods.

tests/__init__.py
Eventually is a convenience method for testing against concurrent services. It retries a a function with assertions on an interval until those assertions pass or a timeout is reached.
=> Add the 'eventually' convenience method

dss/api/bundles/__init__.py, dss/api/files.py, dss/util/version.py, tests/__init__.py, tests/infra/upload_mixin.py, tests/test_bundle.py, tests/test_file.py, tests/test_indexer.py
=> Make a standard version (date) formatting function

dss/stepfunctions/generator/__init__.py, dss/stepfunctions/generator/parser.py, dss/stepfunctions/generator/types.py, requirements-dev.txt, requirements-dev.txt.in
This introduces a pre-processor for state machine definitions that manages bindings from state machine parallel states to a separate state machine, which is replicated as parameterized.  The states in the nested state machine are called with the branch id.
=> Module to simplify the creation and dispatch of parallel branches in state machines

dss/stepfunctions/s3copyclient/__init__.py, dss/stepfunctions/s3copyclient/implementation.py
Most of the code is lifted from `chained-aws-lambda`.
Depends on #704.
=> Definition for a parallelized s3 copy state machine.

daemons/Makefile, daemons/dss-s3-copy-sfn/.chalice/config.json, daemons/dss-s3-copy-sfn/.gitignore, daemons/dss-s3-copy-sfn/app.py, daemons/dss-s3-copy-sfn/requirements.txt, iam/policy-templates/dss-s3-copy-sfn-lambda.json
=> S3 parallel copy state machine app

daemons/Makefile, daemons/dss-s3-copy-write-metadata-sfn/.chalice/config.json, daemons/dss-s3-copy-write-metadata-sfn/.gitignore, daemons/dss-s3-copy-write-metadata-sfn/app.py, daemons/dss-s3-copy-write-metadata-sfn/requirements.txt, iam/policy-templates/dss-s3-copy-write-metadata-sfn-lambda.json
Dispatch logic to the s3 parallel copy + metadata write state machine.
Depends on #704, #707, #708, #709
=> S3 parallel copy + metadata write state machine app

daemons/dss-checkout-sfn/app.py, daemons/dss-sync/app.py, dss/api/bundles/__init__.py, dss/api/files.py, dss/api/search.py, dss/events/handlers/sync.py, dss/storage/index_document.py, dss/util/checkout.py, tests/test_hcablobstore.py, tests/test_indexer.py, tests/test_search.py
The term 'bundle_id' has popped up in the repository, but it is not
always clear what it means.
Here I introduce the term Bundle Fully Qualified Identifier, which is
the combination of the bundle UUID and version string. It is analogous
to FQDN in that it specifies a bundle version exactly and fully.
The terms 'bundle_key', 'key', and 'file_key' have popped up in the
repository alongside terms like `*_object_name`.
This PR attempts to standardize the terminology.
=> DSS-721: Standardize terminology

dss/api/bundles/__init__.py, dss/api/bundles/checkout.py, dss/api/files.py, dss/config.py, dss/events/handlers/index.py, dss/events/handlers/sync.py, dss/storage/index_document.py, dss/util/bundles.py, dss/util/checkout.py, tests/infra/storage_mixin.py, tests/infra/upload_mixin.py, tests/test_api.py, tests/test_bundle.py, tests/test_checkout.py, tests/test_file.py, tests/test_indexer.py
=> Use enums uniformly for specifying replicas

daemons/dss-checkout-sfn/app.py, daemons/dss-sync/app.py, dss/config.py
Bug fix for broken checkout deploy.
=> Replace "aws" with enum

dss/events/handlers/index.py, tests/test_indexer.py
… and eliminate unnecessary method indirection.
=> Assert that bundle events originate from expected bucket

common.mk
Anaconda Python prints its version on stderr instead of stdout.
Ran test suite with anaconda python.
=> Slurp stderr when sanity checking Python version

tests/test_search.py
applied changed for #751 to test_search
=> added tested decorators to test_search

dss/api/bundles/__init__.py, dss/events/handlers/index.py, dss/storage/bundles.py, dss/storage/index_document.py, dss/util/bundles.py, tests/__init__.py, tests/test_indexer.py, tests/test_object_identifier.py
=> ObjectIdentifier and child classes manage storage strings

dss/api/subscriptions.py, dss/storage/index.py, dss/storage/index_document.py, dss/util/es.py, tests/test_search.py, tests/test_subscriptions.py
Methods in this module are used for getting and setting indices.
=> Move index management functions to their own module

tests/test_sync.py
=> Mark sync daemon tests as standalone

dss/api/files.py
This introduces a pre-processor for state machine definitions that includes:
1. Bindings from state machine states to python methods.
2. Bindings from state machine parallel states to a separate state machine, which is replicated as parameterized.
Depends on #704, #707, #708, #710
=> Switch PUT /files to use the new state-machine based parallel s3 copy + metadata write

tests/test_checkout.py, tests/test_email.py
Marked tests related to the checkout service as either standalone or integration depending on the use of lambdas
=> Annotated tests for checkout service

daemons/integration-test/app.py
=> Make Travis integration test job title more descriptive

tests/fixtures/datafiles/indexing/bundles/v3/smartseq2/paired_ends/assay.json, tests/fixtures/datafiles/indexing/bundles/v3/smartseq2/paired_ends/cell.json, tests/fixtures/datafiles/indexing/bundles/v3/smartseq2/paired_ends/manifest.json, tests/fixtures/datafiles/indexing/bundles/v3/smartseq2/paired_ends/project.json, tests/fixtures/datafiles/indexing/bundles/v3/smartseq2/paired_ends/sample.json, tests/fixtures/populate_lib.py
Test data is now retrieved and stored in test/fixtures. This gives us more control over our test data especially as new versions of data bundles are released.
Changed where test data is retrieved from. Test data is now populated from test/fixtures.
=> Changed where test data is retrieved from.

dss/stepfunctions/generator/parser.py
Hotpatched to dev to verify unbreak :shipit:
=> Remove domovoi import from apiserver library code

Makefile
1. test is now only standalone tests.
2. create a all_test rule that hits integration + standalone.
=> switch test and standalone_test

dss/api/search.py, dss/config.py, tests/test_search.py
Fixes https://github.com/HumanCellAtlas/data-store/issues/772
=> Search API should use Replica enums instead of strings

requirements.txt.in
=> updated elastic search requirements to avoid upgrading to 6.0.0

tests/test_indexer.py
=> Correcting test function name changes

dss/events/handlers/index.py, dss/storage/bundles.py, dss/storage/index_document.py, tests/test_indexer.py
=> Compare existing document with new one and log differences (fixes #774)

requirements-dev.txt
Regression from 8612783b794d48861c6110425b314b9814f49ccf
=> Fix version inconsistency between requirements.txt and …-dev.txt

daemons/build_deploy_config.sh, dss/stepfunctions/visitation/integration_test.py, iam/policy-templates/dss-visitation-lambda.json, tests/test_visitation.py
Volatile nature of dev buckets makes consistency checking on
number of items fragile. Use fixture buckets instead.
=> Visitation integration test lists on fixtures

dss/storage/index_document.py, dss/storage/validator.py, requirements.txt.in, tests/fixtures/datafiles/indexing/bundles/v3/smartseq2/paired_ends/assay.json, tests/test_indexer.py
connects to #609 
creating new test data and unit tests for validation.
test data will be modified and populate will need to be run
- Added file `validator.py` which contains the validator for scrubbing the index data.
- Added a function `scrub_index_data` to compare the index_data to its schema and remove extra fields and files before adding it to the index. Schema is determined using the `core` field of the `index_data`
- Added v3 data bundles to test fixtures
=> Removing files and fields not specified in schema

tests/test_smoketest.py
=> change `uuid` to `id` in smoke test

iam/policy-templates/dss-visitation-lambda.json
Visitation batch processor needs modification access to ES for re-index.
=> Give visitation IAM access to ES

dss/stepfunctions/visitation/timeout.py, tests/test_visitation.py
Context manager useful for applying time constraints to lambda executions.
Unit tests.
=> Timeout mechanism using signals.

tests/hcablobstore_base.py, tests/test_api.py, tests/test_bundle.py, tests/test_lambdaexecutor.py, tests/test_logging.py, tests/test_standalone_script.py, tests/test_utils.py
These are the tests I've written or am somewhat responsible for.
=> Mark standalone tests

.coveragerc, dss/stepfunctions/visitation/__init__.py, dss/stepfunctions/visitation/implementation.py, dss/stepfunctions/visitation/integration_test.py, tests/test_visitation.py
This improves on the fix in 10c6be3
=> Aggregate output by visitation workers, not discard it

dss/storage/bundles.py, dss/storage/index_document.py, tests/test_indexer.py
=> Reindexing 2/3: Fix zombie bundles

dss-api.yml
This informs the CLI that these requests can be retried.
Connects to #485
=> Mark PUT /files and PUT /bundles idempotent

dss/util/checkout.py, iam/policy-templates/dss-s3-copy-sfn-lambda.json
=> refactor checkout service to use state machine parallel copy

daemons/Makefile, daemons/dss-gs-copy-sfn/.chalice/config.json, daemons/dss-gs-copy-sfn/app.py, daemons/dss-gs-copy-sfn/requirements.txt, dss/stepfunctions/gscopyclient/__init__.py, dss/stepfunctions/gscopyclient/implementation.py, iam/policy-templates/dss-gs-copy-sfn-lambda.json, tests/test_gscopyclient.py
Unlike S3 copy, GS copy cannot be parallelized.  However, it has a token that can be used to continue a rewrite call.
Connects to #349
=> GS copy implemented as step functions

tests/test_s3parallelcopy.py
1. Creates a large-ish blob.
2. Copies it.
Connects to #592
=> S3 parallel copy integration test

daemons/Makefile
Create four variables: SERIAL_AWS_DAEMONS SERIAL_GCP_DAEMONS PARALLEL_AWS_DAEMONS PARALLEL_GCP_DAEMONS.  Build almost all the remaining rules off of these variables.
=> Clean up daemons/Makefile

.travis.yml, Makefile, tests/test_logging.py
Umm, this is rather urgent. Test failures currently don't cause the build to fail:
https://travis-ci.org/HumanCellAtlas/data-store/builds/330533019
This is a regression from 05a7e548ba81c5f02c46466947f35bbd66b7f006 (#827)
=> Fix: test failures don't escalate to build failure

dss/storage/validator.py, tests/test_indexer.py
added a unit test to verify this behavior.
- Run reindex on master after merge.
- Run reindex after deploying to staging
=> Added checking when core exists but schema_url does not.

chalice/build_deploy_config.sh
This speeds up deployment when many API Gateways/resources are present in the account.
=> Avoid enumerating API Gateways when deploying Lambda

dss/storage/validator.py, tests/test_s3urlcache.py
connects to #609
Will add test cases to check urls are stored and buckets cache is used.
Caching the contents of website urls to an S3 bucket.
=> Cache URL content in S3

dss/stepfunctions/gscopyclient/implementation.py
The latter API is crufty and needs a refactor.  The issue at hand is that S3BlobStore and GSBlobStore are actually not tied to a specific bucket, yet we have to configure the bucket config.
=> build the gcp client directly rather than get_cloud_specific_handles

chalice/app.py, tests/test_exptime.py
=> set DSS_FAKE_504_PROBABILITY as a header, not a cookie.

dss/config.py
This is a simple move, with a bit of tweaking to satisfy mypy.
=> Move `Replica` to after `Config`.

dss/stepfunctions/gscopyclient/__init__.py, dss/stepfunctions/s3copyclient/__init__.py
=> [easy] Use mutablemapping as return type instead.

scripts/kibana-proxy.py
=> Minor documentation fixes in kibana-proxy.py

daemons/dss-sync/app.py, dss/api/bundles/__init__.py, dss/api/files.py, dss/config.py, dss/events/handlers/sync.py, dss/stepfunctions/visitation/integration_test.py, dss/stepfunctions/visitation/reindex.py, dss/storage/index_document.py, dss/storage/validator.py, dss/util/bundles.py, dss/util/checkout.py, tests/test_api.py, tests/test_bundle.py, tests/test_gscopyclient.py, tests/test_indexer.py, tests/test_s3urlcache.py, tests/test_visitation.py
1. Retrieve blobstore and hcablobstore from Config.
2. Retrieve bucket name from replica.
=> Refactor calls to get_cloud_specific_handles()

chalice/build_deploy_config.sh, daemons/build_deploy_config.sh, scripts/release.sh
This makes it easier to track who deployed what when.
=> Tag lambdas with deploy info

dss/util/retry.py
When there are nested @retry transactions as in
```python
@retry
def f():
g()
@retry
def g():
assert False
```
an exception in an inner transaction gets logged by the outer transaction, too.
Additionally, when logging an exception, this PR adds logging of the outer stack frames, too. Those are the ones leading up to the call of the function decorated with `@retry`.
=> 3/4: Log retried exceptions only once (fixes #922)

dss/storage/validator.py, dss/util/s3urlcache.py, tests/test_s3urlcache.py
=> Separate s3urlcache into it’s own file.

dss/config.py, dss/stepfunctions/gscopyclient/implementation.py
This addresses the TODO introduced in #861.
=> Use the new CloudStorageHandles in gscopyclient

dss-api.yml
=> Fix copy-pasta for docs in PUT /files

dss/stepfunctions/s3copyclient/implementation.py
The race occurs when a task finishes or fails, before the main thread has a chance to add the callback to the future. Using ThreadPoolExecutor.map() instead of callbacks allows for proper error propagation.
Connected to #961, connected #963.
=> Fix race and lack of error propagation in s3copyclient

dss/events/handlers/index.py, dss/storage/index_document.py, dss/util/es.py, tests/test_indexer.py
This is the last open item on #829.
=> Shorten f"" string interpolations in logging calls (connected to #829)

dss/storage/bundles.py, dss/storage/index.py, dss/storage/index_document.py, dss/util/es.py
Until now mypy ignored this directory because it did not see it as a package (sigh), so a number of type errors went undetected.
=> [package-reorg 1/2] Fix: dss/storage lacks __init__.py

dss/stepfunctions/s3copyclient/implementation.py, tests/test_s3parallelcopy.py
Currently, the s3 copy step function flips out when it is passed a file that's too small for multipart copy.  It loops indefinitely in the first branch of the parallel section, which is not good.
This takes into account the possibility we might be asked to copy a small object.  If that happens, it copies during `setup_copy_task` and jumps straight to the end.
(Technically, this is an independent diff from #969...)
=> [fix-s3-copy 2/2] support small files in s3 copy

.coveragerc, .travis.yml, Makefile, dss/api/search.py, tests/test_checkout.py, tests/test_config.py, tests/test_doctests.py, tests/test_email.py, tests/test_indexer.py, tests/test_json_faker.py, tests/test_object_identifier.py, tests/test_search.py, tests/test_subscriptions.py, tests/test_sync.py, tests/test_visitation.py
Assorted fixes I stumbled upon during #980.
=> Minor test improvements

daemons/Makefile
Before deployment, add read permissions to domovoilib with
chmod -R ugo+r.
=> [easy] Add read permissions to daemon domovoilib

requirements-dev.txt, requirements.txt, requirements.txt.in, scripts/deploy_gcf.py
Use signed URL to deploy dss-gs-event-relay instead of uploading to test fixtures bucket.
Fixes #943
=> Remove GCF deployment deps on fixtures bucket 2

README.md, dss-api.yml, environment, environment.prod, environment.staging, tests/test_smoketest.py
Renamed in anticipation of allowing functional deployments
without creating a custom domain name.
connects to #856
=> Rename API_HOST to API_DOMAIN_NAME

README.md
Changed  "Project – Service Account Actor" to "Service Account - Service Account Actor"
@xbrianh please looks this over.
=> corrected roles in GCP setup instructions

iam/policy-templates/ci-cd.json, iam/policy-templates/dss-scalability-test-lambda.json
Granting DynamoDB permissions to travis-ci
=> Grant DynamoDB permissions to Travis

daemons/dss-scalability-test/app.py, iam/policy-templates/ci-cd.json
=> Lazy import hca

dss/index/es/document.py
Fixed lint error introduced in fix for v5 metadata support.
=> Fix lint error from adbc941

daemons/dss-scalability-test/domovoilib/json_generator/__init__.py
- added HCAJsonGenerator to dss-scalability-test
=> Added HCAjsongenerator to scalability test

scripts/deploy_scale_dashboard.py
Add 2 new charts to the scalability dashboard
=> Add Throttle/Started SFN count charts to the scalability dashboard

daemons/build_deploy_config.sh, iam/policy-templates/scheduled-ci-build-lambda.json
https://github.com/HumanCellAtlas/data-store/commit/2cf0e1dde58c91875d1092aefb9fbd9bc86917ed#r28209002
Deployed the scheduled-ci-build manually and triggered an execution. Watched the logs.
=> Provide IAM policy for scheduled-ci-build lambda

dss/util/s3urlcache.py
… so we don't need to evict the cache in a timely manner after deploying changes to this code that break backwards compatibility with existing cached URLs.
Follows up on https://github.com/HumanCellAtlas/data-store/pull/1068
Unit tests suffice.
=> Version the folder used by s3urlcache

daemons/dss-scalability-test/requirements.txt
=> Fix scalability test reqs

daemons/dss-scalability-test/domovoilib/json_generator/__init__.py, tests/test_hcagenerator.py
=> Scale test Fix: Not generating JSON schema data that contains oneOf

.travis.yml, daemons/dss-sync/app.py, dss/events/handlers/sync.py, dss/index/bundle.py, dss/logging.py, tests/test_sync.py
Fixes #1020
Fixes #942 
Fixes #1073
I also snuck in a change that prevents another redundant build being triggered by `make release_…`.
Redeployed dss-visitation and triggered a reindex to see if the log warning from #1020 disappears from CloudWatch log stream. Set DSS_DEBUG=2 on that Lambda and triggered reindex again to verify that log levels are configured properly.
=> Logging fixes

iam/policy-templates/ci-cd.json, scripts/authorize_aws_deploy.sh
Fix type in iam/policy-templates/ci-cd.json
=> [easy] Including missing env var in scripts/authorize_aws_deploy.py

README.md
=> Updated Readme to with instruction to make DSS_GS_CHECKOUT_BUCKET

dss/stepfunctions/s3copyclient/implementation.py
If the number of parts is smaller than the branch id, there is no possibility we will be asked to do any work.  Therefore, strip the state (this is required because otherwise the state becomes too big on a thread-join), and proceed to the end.
See https://console.aws.amazon.com/states/home?region=us-east-1#/executions/details/arn:aws:states:us-east-1:861229788715:execution:dss-s3-copy-write-metadata-sfn-dev:9aa35372-364a-4be2-9652-6791ce4fbc87
=> [reduce-lambda-usage 2/2] Don't run lambdas unnecessarily.

iam/policy-templates/ci-cd.json
Grant events:* in order to subscribe to the CloudWatch timer event
=> iam policy for cw timer event

dss/config.py, tests/test_config.py
use DSS_S3_CHECKOUT_BUCKET_TEST for TEST_FIXTURE config
=> checkout bucket in fixture config

daemons/dss-checkout-sfn/app.py, tests/test_smoketest.py
Remove email parameter from the checkout invocation in the smoketest
=> Remove email from the checkout smoketest

dss/index/bundle.py
Reworded comment, eliminated `continue` statements, inline variables.
=> [2/2] Retry get file blob if not found else raise error (fixes #1115)

dss-api.yml, dss/api/subscriptions.py, dss/config.py, dss/index/__init__.py, dss/index/es/__init__.py, dss/index/es/backend.py, dss/index/es/document.py, dss/notify/notification.py, tests/infra/__init__.py, tests/infra/elasticsearch_test_case.py, tests/infra/testmode.py, tests/test_indexer.py, tests/test_subscriptions.py
Same as #1170 but denormalized request body schema for `PUT /subscriptions`
=> [1/3] Reliable notifications

iam/policy-templates/ci-cd.json, scripts/authorize_aws_deploy.sh
Connects to #1181 
Tested with hot-patch.
=> [Easy] Give travis access to relay secrets

tests/test_smoketest.py
Using signed POST against S3 for endpoint, actually verify notifications during the smoke test.
Other improvements to smoke test.
=> [3/3] Reliable notifications

requirements.txt, requirements.txt.in
=> cloud-blobstore 2.1.1 for better error messages on BlobNotFoundError

requirements-dev.txt, requirements-dev.txt.in, requirements.txt
clickclick isn't used anywhere.
click should be in requirements-dev.txt.in
=> Fix click requirements.

dss-api.yml, dss/api/subscriptions.py, dss/index/es/backend.py, dss/notify/attachment.py, requirements.txt.in, tests/test_indexer.py, tests/test_subscriptions.py
… aka custom notification fields.
=> Support for notification attachments (resolves #1092)

environment, scripts/create_aws_event_relay_user.py, scripts/deploy_gcf.py, scripts/set_event_relay_secrets.py
Instead of keeping `AccessKeyId` and `SecretAccessKey` as two Secrets Manager secrets, store them in a single secret.
=> Combine relay user secrets int a single secret.

iam/policy-templates/ci-cd.json, scripts/deploy_gcf.py, scripts/set_event_relay_secrets.py
=> Include stage in secrets keys

dss-api.yml, dss/storage/hcablobstore/__init__.py
Follow-up on #1212
Connected to #1172.
=> [2/2] Remove backlink from file to bundle

daemons/scheduled-ci-build/app.py
I already deployed this daemon with this change to `dev`.
=> Run integration tests on travis-ci.com instead of .org

scripts/deploy_gcf.py
Travis does not have GCP deployment credentials. As workaround, service credentials are grabbed from Secrets Manager for deployment.
=> Grab travis creds to deploy GCF

scripts/create_config_aws_event_relay_user.py
=> Sanitize AWS response while setting relay secrets

daemons/package_daemon.sh
Fix bash conditional in daemons/package_daemon.sh
Wrap long line. Not everyone has a 50" screen …
=> Fix bash conditional in daemons/package_daemon.sh

dss/config.py, dss/notify/notifier.py, environment
Need this for increasing the notification timeout in order to accommodate Lira (Green) taking a little longer than 10s (the default).
=> Make notifier timeout configurable

dss/index/es/backend.py, dss/notify/notification.py, dss/notify/notifier.py
Low hanging fruit from collaboration with @rexwangcc at the Boston May 2018 F2F.
=> Assorted notification fixes

chalice/app.py
We missed a variable refactor when changing XRAY_TRACE to DSS_XRAY_TRACE
=> s/ XRAY_TRACE/ DSS_XRAY_TRACE 

tests/test_indexer.py
=> Fix flaky attachments test

dss-api.yml
Breakout from https://github.com/HumanCellAtlas/data-store/pull/1214#discussion_r191005115
=> Don't list enum contents in description

dss/api/files.py, dss/util/tracing.py
Using Xray to profile lambdas we would like to use subsegments to profile specific segments of code. Currently subsegment tracing is not working using `dss.util.tracing.begin_segment` and `dss.util.tracing.end_segment`. This PR aims to fix that.
=> Fixing subsegment traces in aws Lambdas

daemons/dss-sync/app.py, dss/events/handlers/sync.py
This will properly update the metadata of objects synced from S3 to GCP.
- Fixes #1261
=> [WIP] changed get_key to get_blob in dss-sync. Fixes #1261

.circleci/config.yml, Dockerfile.build, scripts/list_docker_tags.sh, tests/test_notifier.py
=> Add support for CircleCI

tests/test_sync.py
Speeding up the sync test by limiting the generation of random data.
=> minor optimization to test_sync

dss/logging.py, dss/util/tracing.py
Added xray trace_id to logs when enabled and present.
=> Add xray trace_id to lambda logs if enabled.

chalice/app.py
The fallback timeout mechanism (spawns a thread to run the real work, and returns an 504 with stacktraces) used a different (and shorter) timeout than the PUT files retry mechanism.  This meant that the fallback timeout mechanism would trigger, rather than the PUT files retry mechanism giving up first.
=> Provide a consistent timeout to the application logic

daemons/dss-checkout-sfn/app.py, dss/api/bundles/checkout.py, dss/storage/checkout.py
mostly E302 warnings and some unused imports.
=> [checkout-cleanup 1/3] [easy] style & import fixes

daemons/dss-checkout-sfn/app.py
=> [checkout-cleanup 2/3] Inline `email_sender` and `default_checkout_bucket`

infra/build_deploy_config.py
I don't think this does anything...?
=> Remove the alias to self.

daemons/dss-notify/app.py, dss/util/time.py
=> Add safety margin for shutting down notifier 

daemons/dss-checkout-sfn/app.py, dss/stepfunctions/checkout/checkout_states.py
This makes the code easier to read.
Depends on #1311, #1312 
Deployed and ran `DSS_TEST_MODE="standalone integration" python tests/test_checkout.py`
=> [checkout-cleanup 3/3] Integrate the state machine methods into the state machine definition.

requirements-dev.txt, requirements.txt, requirements.txt.in
https://github.com/chanzuckerberg/cloud-blobstore/pull/20
=> bump cloud-blobstore to pick up fix

chalice/app.py
This code is not longer used or working.
=> Remove get_logs route from dss-api

dss/util/__init__.py, tests/test_utils.py
1. Add the ability for UrlBuilder to start with a URL.
2. Add the ability for UrlBuilder to replace a query param.
3. Tests!
=> Enhance UrlBuilder

tests/test_smoketest.py
* Moved common setup code to setUpClass
* Added support for testing additional replicas
=> Replicating smoke test using GCP

dss/api/bundles/checkout.py, dss/storage/checkout.py
This is so that we can reuse this code for #1203 and #1204.
Depends on #1313, #1316
`DSS_TEST_MODE="standalone integration" python tests/test_checkout.py`
=> Abstract the code that starts a bundle checkout.

tests/test_checkout.py
1. Name variables so they're very clear that it's expected to not exist.
2. Don't use values that look like they _should_ exist (perhaps as a fixture).
Depends on #1318, #1320
=> Clarify when we are using a bundle UUID/version that is not supposed to exist

tests/test_checkout.py
This allows us to do a proper checkout.
Depends on #1321
=> Upload a test bundle for checking out.

tests/test_checkout.py
This way, we can actually do a proper integration test.
Previously, we were validating that the bundle exists locally with the bucket-override, but when the state machine gets the request, it would discover that the bundle doesn't exist, as it only existed in the fixtures bucket.
Depends on #1324
=> Checkout from uploaded bundle

tests/test_checkout.py
Rather than just test that the checkout sfn can start, verify that it completes with the expected result.  This requires several changes:
1. Check for the expected status, but keep trying for "RUNNING".
2. Need to read from the normal (i.e., not test) bucket as the status is written to that space.  I don't see there being a lot of value to parameterize that as well.
Depends on #1325
=> test that the checkout sfn completes with the expected code.

dss/storage/checkout.py, tests/test_checkout.py
Added test for extra fun times.
Depends on #1333, #1334, #1335
=> Implement single-file checkout.

dss-api.yml, dss/api/files.py, dss/storage/checkout.py, tests/test_bundle.py, tests/test_file.py
Depends on #1336, #1343 
Fixes #1310
=> Support for checkout service in GET /files

dss/stepfunctions/checkout/checkout_states.py, dss/stepfunctions/checkout/constants.py, dss/storage/checkout.py
Also renamed some variables named `bundle_id` or `bundle_fqid` that were actually bundle_uuid.  Also renamed some variables named `version` that were actually bundle_version.
Test plan: Deployed daemon and ran integration+standalone checkout tests.
=> Remove magic constants from checkout code.

dss/stepfunctions/checkout/checkout_states.py
It's RESULT and not EMAIL_RESULT.
=> fix the key for RESULT.

tests/__init__.py
Thanks to @Bento007 for finding this issue.
=> use a set to store the authorized admin users.

dss-api.yml, dss/api/bundles/checkout.py, tests/test_checkout.py
Return 404.
Test plan: yo there's a test.
=> Don't return server error for unknown checkout id.

tests/test_checkout.py
=> Fix checkout test.

dss-api.yml, dss/api/bundles/__init__.py, dss/storage/checkout.py, tests/test_bundle.py
This behavior is only triggered for presignedurl=true or directurl=true.
Depends on #1362, #1359, #1371 
Fixes #1203, #1204, and #1289
=> Incorporate bundle checkout into GET /bundles/<uuid>

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
* Reduce some text
* Remove outdated references to Waffle.io
* Add a separate feature request section
* Make the calls to action louder using upper case
=> Update new issue and PR templates

dss/storage/checkout.py
this may help track down the error @Bento007 flagged: https://travis-ci.com/HumanCellAtlas/data-store/jobs/131482812
Test plan:
```
INFO:dss:[dispatch] "GET /v1/files/5e26c221-80af-4179-a70a-b136f0431451" 302 {'replica': 'aws', 'token': '{"execution_id": "2c2968da-f6f1-471a-94bf-dafe6459ffd3", "start_time": 1530051259.990313, "attempts": 0}'}
INFO:dss:[dispatch] "PUT /v1/files/df4537dc-0deb-4eee-b6fa-d6fe13adcbb5" 201 {'version': '2018-06-26T221423.252086Z'}
INFO:dss:[dispatch] "GET /v1/files/df4537dc-0deb-4eee-b6fa-d6fe13adcbb5" 301 {'replica': 'gcp'}
INFO:dss:[dispatch] "GET /v1/files/df4537dc-0deb-4eee-b6fa-d6fe13adcbb5" 302 {'replica': 'gcp', 'token': '{"execution_id": "536f05d2-46d7-4d34-82be-fcf3e30a1fe9", "start_time": 1530051267.050048, "attempts": 0}'}
```
=> parallel_copy should return the execution id

tests/test_smoketest.py
* Moved common setup code to setUpClass
* Added support for testing additional replicas
* Added GSBlobstore for GS checkout verification.
Ran smoke test locally against the dev deployment
=> Adding GCP replica to smoketest

dss/util/parallel_worker.py, tests/test_parallel_worker.py
=> Library to manage a task that is broken into sequential subtasks.

dss/stepfunctions/s3copyclient/implementation.py
Currently, we're marking the entire range (A, B) of a multipart copy complete if B completes.  This is obviously not correct, as it only means B completes.  (A, B-1) still may not have completed.  Generally, this resolves itself as the parts do copy, but if the parts in (A, B-1) error out, then we don't ever complete the copy.
see dss-s3-copy-sfn-dev:9d5cb5f4-df3c-44ec-95bf-04dd54abebeb for an example of where this fails.
This rewrites the parallel copy management using the library in #1377.
=> Handle multipart copy that completes out of order.

README.md
=> [EASY] moving badges to the top of readme

tests/test_smoketest.py
This will make debugging smoke test easier.
=> Printing out smoke test comments

tests/test_collections.py
- Added additional testcases
- Separated subtests into own tests.
=> Refactored Collections Testcases

infra/buckets/s3_buckets.tf
Also prune incomplete multipart uploads.
=> Shorten the expiration on the dev checkout bucket

tests/test_checkout.py
=> Add additional debugging info for when the exception fires.

tests/test_checkout.py
1. remove `test_validate_wrong_key` as it is the same as `test_validate_bundle_exists_fail`.
2. remove `test_validate_bundle_exists` as it is almost the same as `test_validate` (the former calls `validate_bundle_exists`; the latter calls `pre_exec_validate`, but that in turn calls `validate_bundle_exists`).
3. Changed test_status_{success,fail} to test_checkout_{success,fail} as that's what it's actually doing.
4. Switch some of the sanity checks to standalone since they don't depend on a deployed stepfunction.
Depends on #1411
=> Clean up checkout tests

dss-api.yml
=> Add DSS HTTP client best practices docs

Dockerfile.allspark
Addresses "Python 3 Surrogate Handling": http://click.pocoo.org/5/python3/
=> Set language locale to address Click issue

.gitlab-ci.yml, Makefile, infra/Makefile, scripts/release.sh
Use `terraform plan -detailed-exitcode` to check that infra is not stale.
=> During ci/cd build use terraform plan, not apply

tests/test_file.py
- split test into subtests
- added tests for invalid uuids
- run unittests
- improved test coverage for Put /file
=> Separated file_put into subtests

.gitmodules, requirements-dev.txt, requirements-dev.txt.in, tests/fixtures/cloud_uploader.py
=> Remove the submodule dependency on checksumming_io

dss-api.yml, dss/api/bundles/__init__.py, tests/test_bundle.py
=> Reject bundles containing duplicated filenames

.gitlab-ci.yml, scripts/status.sh
The dcp-wide integration test has moved to GitLab. This allows us to check status there.
=> Check dcp-int status on GitLab

dss/api/bundles/__init__.py, dss/index/bundle.py, dss/index/indexer.py, dss/storage/bundles.py, dss/storage/identifiers.py, tests/test_object_identifier.py
- Added CollectionFQID and CollectionTombstoneID to ObjectIdentifier
- updated test cases to include collectionID, collectionTombstoneID, and BundleTombstoneID
=> [Refactor] Changed TombstoneID to BundleTombstoneID

.gitlab-ci.yml
This allows forced release to be performed with the GUI:
=> Add force-release buttons to GitLab

.gitmodules, tests/test_smoketest.py
* Update smoketest fixture to new bundle format
* Remove unused `data-bundle-examples` submodule
=> Update smoketest bundle fixture

tests/test_indexer.py
This removes test code duplication of application logic from `dss.index.es.document.BundleDocument`
depends on  #1500
=> Remove duplicated code in indexer tests

README.md, daemons/Makefile, daemons/build_tf_deploy_config.py
This runs TF workflow if terraform files are present in `daemons/{daemon_name}`
=> Incorporate terraform workflow into daemon deployment

README.md
=> Add link to CONTRIBUTING.md in README.md

tests/test_indexer.py
=> Add test for notification upon bundle delete

dss/index/es/document.py, tests/test_indexer.py, tests/test_subscriptions.py
=> Put the shape descriptor in the ES index doc

chalice/app.py
API_GATEWAY_TIMEOUT_SECONDS is a constant, so it is not appropriate for calculating time_remaining.  It should be start_time + API_GATEWAY_TIMEOUT_SECONDS - current_time.
Test plan: Repeated hit PUT /bundles with a file that doesn't exist.
=> Fix timeout handling for API lambda

CONTRIBUTING.md
=> Fix grammar

dss/api/subscriptions.py, dss/config.py, environment, tests/test_subscriptions.py
=> remove subscription restriction

iam/policy-templates/dss-sync-sfn-lambda.json
=> [EASY] Tighten IAM policy for SQS access for sync daemon

daemons/Makefile, daemons/dss-gs-event-relay/main.py
=> Add logging and retries to gs relay daemon

tests/__init__.py
=> Add debug logging to the tests.eventually decorator

chalice/build_deploy_config.sh, scripts/release.sh
- Reformat release tags to sort alphanumerically by date
- Inline most recent release tag into deployed code
- Read back version from deployed apiserver and assert that it matches release tag
=> Release tag handling improvements in release.sh

environment.prod
adding the production google project accounts to production authorized domain list.
=> adding google project to whitelist

environment.prod
see the connected issue https://github.com/HumanCellAtlas/fusillade/issues/7
=> Use dev Auth0 until prod Auth0 is available.

.gitlab-ci.yml
Use a conditional to set `DSS_ENV` and define CI deployment environments.
Note the branch->env mapping `[master, integration, staging]` -> `[dev, integration, staging]`
=> gitlab-ci.yml simplifications

.gitlab-ci.yml
=> [easy] .gitlab-ci.yml: Break up long line

.travis.yml
This is handled by GitLab instead
=> Remove travis deploy jobs

README.md
=> Move badges under Title

dss/notify/notifier.py
=> Making notification logs less noisy

docs/environment/README.md
=> Adding environment variable documentation

scripts/release.sh
=> [easy] Fix scripts/release.sh --help

Dockerfile.allspark
Also make help text more useful.
=> Use new Terraform version in Docker image

dss/stepfunctions/s3copyclient/implementation.py
=> [Easy] Add retry to join task in s3copyclient sfn

dss-api.yml
=> remove unsupported azure from swagger

dss-api.yml, dss/api/search.py, tests/test_search.py
Partial fix for #1648
- Documented limitation when using search with out format raw.
=> Raw Search Page Limit Documented

environment.prod
=> updating authorized domain in prod

docs/environment/README.md
=> Update docs for some env vars

daemons/dss-index/app.py, scripts/deploy_gcf.py
This should:
1. Provide additional elasticity
2. Allow integration with ops scripts via SQS
=> Drive dss-index with SQS instead of SNS

tests/test_indexer.py
=> Adding Indexer idempotent test

dss/index/es/backend.py
=> replacing scan with search after for notifications.

.flake8
=> [EASY] ignoring lint E252

README.md
Otherwise make `deploy-infra` will fail since the volumes are already created and not owned by terraform deployment process.
=> DEFINE, not CREATE the bucket

dss/api/files.py, tests/test_file.py
updated test case for file head to verify meta data fields are returned.
=> head File returns file metadata.

.gitlab-ci-prod.yml, .gitlab-ci.yml, chalice/build_deploy_config.sh, scripts/set_version.sh
Update version only if deploy succeeds.
fixes #1702
=> Update DSS_VERSION after deploy succeeds

dss/api/collections.py, tests/test_collections.py
added code to test deduplication in collection patch and put.
=> updating patch collection to deduplicate contents

README.md
=> [EASY] Updating Auth in readme

.gitlab-ci-prod.yml, .gitlab-ci.yml, allspark.Dockerfile
also mv Dockerfile.allspark -> allspark.Dockerfile
=> Update terraform version in allspark.Dockerfile

README.md
=> Note requirement of privileged access in README.md

.gitignore, dss-api.yml, dss/api/bundles/__init__.py, tests/test_bundle.py
… (200), attempting pull request to run testing
[WIP] #1331 
PR to test implementation within Travis CI
=> PUT/Bundle Response Manifest

environment.staging
Update list of users authorized for direct url access to staging checkout bucket.
=> [Easy] Update staging checkout bucket viewers

dss/api/bundles/checkout.py, tests/test_checkout.py
=> sanitation checks for POST bundle checkout

infra/buckets/s3.tf
=> Fix Unwritable bucket

infra/buckets/s3.tf
Fixes https://github.com/HumanCellAtlas/data-store/issues/1792
=> Set CORS policy on checkout bucket

infra/buckets/s3.tf
#1755 had some syntax errors, this corrects those.
=> Correct for syntax error in s3.tf.

infra/async_state_db/main.tf
This improves performance at scale
=> Switch to on-demand capacity for async state db

scripts/set_secret.py
=> Added dry-run functionality to scripts/set_secrets

infra/gcp_service_account/main.tf
=> Reducing the DSS permission to deny deletion privilages

scripts/tombstone_bundles.py
This is the script, with procedures, used to tombstone bundles in prod or other stages.
=> Script for tombstoning bundles

chalice/app.py, dss/util/security.py
- the user email, ip address, token issuer, token issue date, token expiration date, token issuer, and token claims will be logged for all requests.
Related to #1667
=> Adding Source IP and Decoded JWT to logs

infra/Makefile
=> infra make clean adjustment

dss/index/es/backend.py, tests/sample_doc_tombstone.json, tests/sample_search_queries.py, tests/test_indexer.py
This should notify correctly for delete events.
Test coverage is to be addressed, see #1850
=> [Easy] Use correct document when notifying on delete

tests/test_smoketest.py
adding deletion and tombstone notifications to smoke test
* Fixes #1850
=> notify tombstone smoke

chalice/app.py
=> smokeTest Errors 

dss-api.yml
=> Fix typo in Swagger doc

iam/policy-templates/ci-cd.json
Needed to address https://travis-ci.com/HumanCellAtlas/data-store/jobs/178271918#L1236
=> changed ci-cd.json for ddb query

daemons/build_deploy_config.sh
added USER_TEST bucket to checkout for correct policy deployment.
See
`aws iam get-role-policy --role-name dss-s3-copy-sfn-dev  --policy-name dss-s3-copy-sfn-dev`
=> added TEST_USER to envsubst

dss/storage/checkout/cache_flow.py, tests/test_checkout_caching.py
PR for removing TEST checkout buckets from cache_flow, added mocking for testing.
=> removed TEST_USER buckets, added mocking to tests

dss/error.py
=> Log API exceptions

scripts/populate_lambda_ssm_parameters.py
Lambda environment variables should be updated, not replaced.
=> Fix scripts/populate_lambda_ssm_parameters.py

dss-api.yml, tests/test_file.py
Going back to the original regex I had which should fix things.  Also added one of the breaking paths to the testing.
=> Change regex for PUT file/{uuid}.

dss/util/__init__.py
=> removed hard-coded reference

iam/policy-templates/ci-cd.json
To fix this error: https://travis-ci.com/HumanCellAtlas/data-store/jobs/182797366#L1587
=> Travis dynamoDB permission additions.

dss-api.yml
Just updates and adds swagger descriptions.  Should address `dcp-cli` issue #221.
=> Improve swagger descriptions.

README.md
* Formatting, spelling fixes
* Added note on Terraform
* Clarified GCP authentication flow
=> Update deployment documentation (closes #1902)

security.txt
=> Add a security.txt file.

dss-api.yml
=> Swagger docs: follow common style

daemons/dss-sync-sfn/.chalice/config.json, dss-api.yml, dss/api/bundles/__init__.py, dss/api/collections.py, dss/util/__init__.py, scripts/swagger_auth.py, tests/test_bundle.py
This allows bundles to grow to arbitrary size via /PATCH
connects to #1901 
closes #1940
=> Add support for PATCH /bundle

tests/__init__.py, tests/test_utils.py
- testing multiple audiences
- testing single audience
=> additional test cases for jwt audience

README.md, docs/environment/README.md
Address issues of readability and provide inside to deploying infra for DSS
Sort `doc/environment/readme.md` for easier locating of values.
Add Table of Contents to `readme.md` for easier access
Reorganize sections in `readme.md`
Resolves: #1960
=> [WIP] Update Readme.md Flow

dss/api/bundles/__init__.py
Creating/patching large bundles is unduly restrictive without parallelizing file metadata collection.
depends on #1993 #1994
connected to #1901
=> Parallelize bundle file verification

dss/storage/bundles.py, dss/storage/checkout/__init__.py
Should fix the current error on `dev`.
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/-/jobs/26318
=> Bucket var input for caching.

daemons/invoke_lambda.sh
Output complete Lambda response during invocation test. This will hopefully provide enough information to debug intermittent daemon deployment failures.
connects to #2022
=> [Easy] Lambda invoke test outputs complete response

daemons/dss-notify-v2/app.py
This will enable downstream services to react to object removal events in the DSS.
depends on #2048 
closes #2003
=> Deliver JMESPath DELETE notifications upon object deletion

dss/api/health.py, iam/policy-templates/ci-cd.json, tests/test_health.py
Add dynamic fetching of of dynamodb tables to health checks
Resolves: #2021
=> Dynamic DynamoDB Table Fetching

dss-api.yml
modify description for /PUT/Collection, remove reference for generated timestamp
Resolves: [dcp/cli#299](https://www.youtube.com/watch?v=Nw4Sng23YH0)
=> Modifed Description for /PUT/Collection

daemons/invoke_lambda.sh
Collect correct Lambda function output during deployment invocation tests.
closes #2022
=> Lambda invocation test examines correct JSON object

dss/events/handlers/notify_v2.py
This keeps JMESPath querying consistent with current indexing schemes.
=> Modify file names in metadata document

dss/api/bundles/__init__.py, dss/api/collections.py, dss/storage/blobstore.py, dss/storage/bundles.py
=> Make bundle manifest memcache replica specific

dss/dynamodb/__init__.py, dss/util/async_state.py, infra/async_state_db/main.tf
=> Use dynamoDB methods in async_state.

dss/events/handlers/sync.py, tests/test_sync.py
fixes #2073 
This also:
- Should improve metadata caching performance, which caches dependent on content-type.
- Fixes the large bundle sync test
See documentation for gs PATCH Objects
https://cloud.google.com/storage/docs/json_api/v1/objects/patch
=> Sync daemon sets destination content-type equal to source

dss/stepfunctions/gscopyclient/implementation.py, dss/stepfunctions/s3copyclient/implementation.py, dss/storage/checkout/cache_flow.py, tests/test_checkout_caching.py
closes #2077 
connected to #2075
=> Cache for content type like 'application/json; foo'

infra/buckets/gs.tf
update google-storage terraform scripts to remove DEPRECATED messages
Resolves: #2070
=> Update GS TF scripts

tests/test_prod_smoketest.py
Fix string comparison to avoid errors.
=> Change String Comparison

tests/test_prod_smoketest.py
Remove possibility for tombstoned bundles to be in the prod-smoketest
=> Prod Smoke Test Query

.gitlab-ci.yml
- provide flexible scale and performance test job
=> Simplify GitLab job definitions

environment.integration, environment.prod, environment.staging
update the backend bucket env based on the stage that is currently set.
In deployments this looks like `source environment && source environment.{stage}`
=> Update Terraform Backend Env Var

dss-api.yml
Fixes list not being correctly formatted
=> Improve `PUT /files/{uuid}` description

scripts/envhook.py, scripts/swagger_auth.py, scripts/update_collection_db.py
These were missing from a few python scripts.
=> Add python shebangs to scripts.

dss/operations/__init__.py, scripts/dss-ops.py, tests/test_operations.py
This PR
1. Provides a central entrypoint for DSS operations scripting, and
2. Provides a framework for command forwarding to Lambda
connected to #2096, #2111
=> Operations CLI framework

dss/operations/util.py, tests/test_operations.py
Some useful utility routines for queuing commands and performing operations on bucket contents.
depends on #2111
connected to #2096, #2111
=> Operations utils

dss/api/files.py
=> Fix typo in `PUT /file/{uuid}` metadata parsing

allspark.Dockerfile
updates buildbox for `xxd` and `openssl`
=> Update BuildBox for Layers

daemons/dss-operations/app.py, dss/operations/__init__.py, dss/operations/storage.py, dss/operations/util.py, scripts/dss-ops.py
Add two storage operations:
1. Verify expected blob metadata
2. Verify referential integrity for DSS entities
Also some operations framework improvements.
#connected to #2096
=> Add verification storage operations

daemons/dss-gs-copy-sfn/app.py, daemons/dss-gs-copy-write-metadata-sfn/app.py, daemons/dss-s3-copy-sfn/app.py, dss/stepfunctions/gscopyclient/implementation.py
=> Pull logging into copy clients

dss-api.yml, dss/api/files.py, tests/test_file.py
=> Verify checksums on `PUT /file/{uuid}`

scripts/check_deployment_secrets.py
Updated authorization endpoint checks due to change in Fusillade.
=> [ez] Updated Authorization Endpoint Checks 

tests/test_async_state.py
=> Add short retry to get-item test

dss/stepfunctions/gscopyclient/implementation.py, infra/buckets/gs.tf, tests/test_checkout_caching.py
=> Use STANDARD storage class to mark non-cached checkout objects

tests/test_api.py
=> Fix tests/test_api.py test mode

chalice/build_deploy_config.sh, daemons/build_deploy_config.sh
Adds resource tagging on AWS Lambda Functions
=> [EZ] Lambda Tagging

dss/index/indexer.py, tests/test_indexer.py
=> Remove indexer retries for non-existent objects

daemons/dss-notify-v2/app.py
=> Remove notifier v2 retries for non-existent objects

dss/events/handlers/notify_v2.py, dss/operations/storage.py, dss/operations/util.py, tests/test_notify_v2.py, tests/test_operations.py
This also refactors and re-enables a notify-v2 test
connected to #2171
=> Consolidate SQS message delivery

daemons/invoke_lambda.sh, scripts/generate_upload_requirements_layer.sh
=> Miscellaneous fixes

dss/api/subscriptions_v1.py
=> De-register percolate queries across all indices

chalice/app.py, dss/storage/identifiers.py
See: https://github.com/HumanCellAtlas/dcp-community/blob/master/rfcs/text/0005-analytics-instrumentation-plan.md#data-storage-service-instrumentation
=> Reformat request to analytics log message.

dss/operations/storage.py, dss/operations/util.py
- Simplify command forwarding mechanism
- Better log messages
- Reduce parallelization to avoid dropped HTTP pool connections
=> Storage operations improvements

infra/fargate/main.tf
Address invocation issue of Fargate task from scheduler.
Change invocation schedule to be everyday, not just M-F.
=> [EZ] updated iam / cron for fargate

daemons/dss-sync-sfn/.chalice/config.json, daemons/dss-sync-sfn/app.py
This provides padding for syncing large bundle and collection manifests.
connected to #2097
=> Increase sync daemon timeout to 900s

dss/events/handlers/sync.py
Optimize dependency check for syncing large bundle manifests.
connected to #2097
=> Parallelize sync manifest deps check

scripts/tombstone_bundles.py
This adds parallelization to `scripts/tombstone_bundles.py`.
connected to #2139
=> Parallelize bundle tombstone script

dss/api/collections.py, tests/test_sync.py
This adds a sync test for a manifest containing 1000000 files.
=> Large bundle manifest sync test

dss/operations/storage.py
This is helpful for passing in large lists of keys.
connected to #2225
=> Storage ops accept input keys file in JSON format

daemons/dss-index/app.py, dss/operations/elasticsearch.py, scripts/dss-ops.py
=> Add operation to trigger Elasticsearch indexer

dss/operations/storage.py
=> Parallelize local storage ops

tests/infra/base_smoketest.py
=> Adjust smoketest to wait a bit longer when downloading after a sync.

dss/api/bundles/__init__.py, dss/storage/checkout/__init__.py
Saw these and I can't find where they're used anywhere so I figured I'd make a PR.
=> [easy] Remove unused code.

dss/api/subscriptions_v1.py, dss/operations/elasticsearch.py
This adds admin operations for:
- listing, getting, and deleting subscriptions
- retrieving ES documents by id
=> Operations for managing the ES index and subscriptions

tests/test_collections.py
Should resolve some recent flakiness: https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/-/jobs/38069
=> Add retries within collections testing.

environment.integration
@rhiananthony has requested an additional account to have access to integration.
=> Broad Integration Test Accounts update

dss-api.yml, tests/test_collections.py
(For full disclosure, the changes to the schema were made by @xbrianh, I just added the test.)
=> 1k item limit in PUT /collections (closes #2281)

tests/test_subscriptions.py
Deletes the subscriptions that the test_subscriptions make. 
Resolves: #2270
=> Delete Test Subscription

tests/test_subscriptions.py
repair integration test failure
=> fixed integration test errors

allspark.Dockerfile, infra/buckets/gs.tf, infra/buckets/s3.tf, infra/collections_db/main.tf, infra/elasticsearch/main.tf
This updates the Terraform scripting that defines DSS deployed infrastructure for compatibility with Terraform v0.12.6
closes #2336
=> Terraform v0.12.6 compatibility updates

.gitlab-ci.yml, daemons/package_daemon.sh
This fixes permission errors encountered during daemon-import-tests.
=> Fix daemon import test CI

dss-api.yml, dss/api/bundles/__init__.py, tests/test_bundle.py
Reverts HumanCellAtlas/data-store#2344
=> Revert "Fix 500 error when deleting nonexistent bundle (closes #1918)"

dss-api.yml
=> Schema typo fix (s/it/is)

README.md
=> [EASY] Update link to security policy

dss/api/collections.py, tests/test_collections.py
This fixes broken master from #2332.
=> Pagination headers fix

allspark.Dockerfile
Updates TF version in buildbox from `0.12.6` -> `0.12.8`
=> DSS BuildBox: Update TF Version

dss/operations/lambda_params.py
Implements better handling of AWS exceptions
=> Error catching improvements from @natanlao

dss-api.yml, dss/api/events.py, dss/util/version.py, scripts/swagger_auth.py, tests/test_events.py
depends on #2433 #2434 
connected to #2293
=> Define the API to retrieve and playback events

daemons/dss-notify-v2/app.py, tests/test_notify_v2.py
Also add a test the code block that contained the incorrect method signature.
=> Fix signature in daemons/dss-notify-v2/app.py

.gitlab-ci.yml
=> [EASY] In CICD moving fusillade to after deployment

README.md
Addressing @amarjandu code review comment for #2475, clarifying where commands should be run from
=> add readme note on where commands should be run from

dss/events/__init__.py, dss/events/handlers/notify_v2.py, tests/test_notify_v2.py
Also, correctly retry for DELETE events
=> Avoid mangling key for queued notifications

tests/infra/base_smoketest.py, tests/test_prod_smoketest.py, tests/test_smoketest.py
adds support for testing `jmespath` subscriptions in test_smoketest.py
refactored test_prod_smoketest.py
=> DSS SmokeTest: jmespath support

scripts/tombstone_bundles.py
data-ops team requested to be tagged on tombstone scripts, updating script as a reminder.
=> Update tombstone_bundles.py [EZ]

dss/api/bundles/__init__.py, dss/storage/bundles.py, tests/test_utils.py
resolve issue where tombstoned bundle might appear within the returned response, refactor tests to test this case, rename internal function
=> fixes tombstone issues, refactor tests

dss/operations/iam.py, tests/test_events.py, tests/test_operations.py
=> Add Fusillade tests to IAM auditing functionality in dss-ops script 

daemons/dss-index/app.py, dss/operations/elasticsearch.py, tests/test_indexer_daemon.py
Default is to not send notifications.
=> Optionally send notifications during reindex

tests/test_operations.py
This PR is made on the `chmreid-iam-ops-fus` branch.
This PR splits up and isolates some of the aws-specific work in PR #2492. It is intended to make that pull request easier to review.
=> Add AWS (+tests) to IAM auditing functionality in dss-ops script

dss/events/handlers/notify_v2.py, dss/subscriptions_v2/__init__.py
Fixes mypy typing errors in #2482 due to introducing enums
cc @amarjandu
=> Fix typing for enums

README.md
This PR adds links for each stage's swagger API docs
Closes #2438
=> Add links to swagger API docs to Readme

dss/operations/secrets.py
Fix a variable name in `dss/operations/secrets.py`
`s/events/secrets`
=> [EASY] Typo fix for dss/operations/secrets.py

dss-api.yml, dss/api/events.py, dss/operations/events.py, requirements-dev.txt, requirements.txt, requirements.txt.in, tests/test_events.py
This also adds a paging test asserting future CLI expectations of the paged response.
=> Fix events paging, bump flashflood to 0.4.0

dss/operations/iam.py, tests/test_operations.py
This PR adds AWS functionality to the dss-ops.py script's IAM action.
This PR is part of #2509
This adds both AWS IAM functionality and tests for the new functionality.
=> Add AWS IAM auditing functionality to dss-ops script (redux)

dss/util/__init__.py, tests/test_utils.py
This functionality is useful for the forthcoming events journaling daemon.
=> Add method to time limit iterated work

dss/operations/checkout.py
This will check out all files meeting the caching criteria.
=> Add checkout sync operation.

.gitlab-ci.yml, .travis.yml, Makefile
Turns out that smoketests rely on stdout so those can't be buffered.
Sorry for breaking master, again.
=> Suppress test output on a per-test basis

daemons/Makefile, daemons/dss-events-scribe/.chalice/config.json, daemons/dss-events-scribe/app.py, dss/events/__init__.py, dss/util/__init__.py, iam/policy-templates/dss-events-scribe-lambda.json, tests/test_events.py, tests/test_utils.py
This daemon is called on a schedule every five minutes. It performs as much work as it can in five minutes and then quits. Uncompleted work will be resumed on the next call.
=> Events journaling and update daemon

.dockerfiles/.vimrc
This folder has no purpose that I can ascertain.
=> Remove dockerfiles.

infra/buckets/s3.tf, requirements-dev.txt, requirements.txt, requirements.txt.in
=> Collect flashflood garbage with s3 lifecycle

ISSUE_TEMPLATE.md
adds resources to keep discussions respectful.
=> [WIP] added resources to help issues

.gitlab-ci.yml
Changes destination for fusillade group to be stage dependent.
=> DSS Security: Pipeline Destination

tests/infra/base_smoketest.py, tests/test_smoketest.py
Removes auto paging feature's from `base_smoketest.py`, avoids delay while pages are being consumed. 
Closes #2576
=> DSS Smoketest: --no-pagination

daemons/dss-notify-v2/app.py
This method will do more than deliver notifications in the future.
=> [Easy] Generalize name of v2 event handler

daemons/dss-notify-v2/Readme.md
This reflects the current v2 notification system.
=> Improve documentation

dss/operations/iam.py
This PR simplifies a function in PR #2612
=> Simplify function calling Fusillade API in dss-ops IAM

scripts/check_fusillade.py
=> Check Fusillade hotfix - fix broken script

requirements-dev.txt, requirements.txt, requirements.txt.in
=> Bump flashflood to 0.4.3

infra/build_deploy_config.py, scripts/authorize_aws_deploy.sh, scripts/check_env.py, scripts/create_config_aws_event_relay_user.py, scripts/deploy_scale_dashboard.py, scripts/deploy_scale_tables.py, scripts/envhook.py, scripts/set_apigateway_base_path_mapping.py
This adds a docstring to the top of several scripts that are missing useful information about what they do/what they are for.
=> [EASY] Add docstrings to scripts

daemons/dss-events-scribe/app.py, iam/policy-templates/dss-events-scribe-lambda.json, tests/test_events.py
This refactors the event journaling and update daemon using a more elastic rate-limiting algorithm.
depends on #2654 
connected to #2648
=> Refactor the event journaling and update daemon dss-events-scribe

daemons/dss-events-scribe/Readme.md
depends on #2654, #2655 
closes #2648
=> Documentation for the refactored dss-events-scribe

dss-api.yml
=> Move Swagger docstring from HEAD /files to GET /files

iam/policy-templates/dss-lambda.json
removes multiple resource's for dynamodb within `dss-lambda` 
Connected to #2683
=> DSS Infra: dss-lambda IAM 
