- .gitignore
Ignore the gcs credential file so we don't mistakenly commit credential data to the public repo.
> ignore gcs credential file

- dss/api/bundles.py
This matches the swagger spec now and the endpoint does not fail.
> fix what Bundle.list returns

- dss-api.yml
self-explanatory.  Conveniently, the previously written code matches this spec!
> bundle should return a list of versions

- dss-api.yml
`blob_common_metadata` is the base type.
`file_version` is the file object in the bundle list.
`file_metadata` is the file metadata (searchable by file uuid)
> Add definitions for describing the file metadata and for describing the file contents of a bundle.

- .travis.yml
- Makefile
- chalice/.chalice/config.json
- chalice/.chalice/deployed.json
- chalice/.chalice/policy.json
- chalice/app.py
- chalice/build_deploy_config.sh
- chalice/requirements.txt
- dss/__init__.py
- dss/api/files.py
- Use [Chalice](https://github.com/awslabs/chalice) to enable deployment of the app to AWS Lambda/API Gateway
- Add a Chalice-Connexion adapter to preserve the ability to use Connexion validation
- Add a `deploy` config to Travis CI to perform automatic deployment any time we push to master
In our AWS account, I have separately set up the DNS/SSL/CloudFront to serve the app on https://hca-dss.czi.technology/v1/.
> Continuous deployment instrumentation

- dss-api.yml
- dss/api/files.py
- tests/test.py
1. Updated UUID definition.
2. `replica` is now not required.  It is enforced in code for only GET requests.
3. Added `timestamp` parameter.
4. Added response headers.  Unfortunately, it looks like connexion does not verify the minLength and maxLength fields of string headers (see https://github.com/zalando/connexion/blob/master/connexion/decorators/response.py), but if they add the proper support, this should hopefully match.
5. Use a shared code path for GET and HEAD.
> flesh out GET/HEAD support for /files/<uuid>

- dss-api.yml
This allows us to further constrain the valid input set. Again, headers are not verified by connexion, but one day.... :)
> use patterns instead of minLength/maxLength.

- dss/blobstore/gcs.py
- dss/blobstore/s3.py
- tests/test_gcsblobstore.py
- tests/test_s3blobstore.py
There are methods that involve multiple buckets, so it doesn't make sense to tie the handle to a container.  Verify that the handle is sane through a sensible API.
> Don't associate the {gcs,s3}_blobstore handle with a container

- dss/blobstore/__init__.py
- dss/blobstore/s3.py
Implement S3's delete object method.  Since it doesn't seem to distinguish between an-object-was-deleted and no-object-was-deleted, it returns nothing.
> Delete operation should take a container and a key

- dss/blobstore/__init__.py
- dss/blobstore/s3.py
This is the same as #64, except it uses the managed `copy` interface.
> add copy methods to BlobStore and S3BlobStore

- dss-api.yml
- dss/api/files.py
There's a connexion bug that results in some oddity.  Read the comment in files.py.head().
@Mackey22 needs this for the CLI.
> Separate get and head requests, but map it to the same code path.

- dss/blobstore/__init__.py
- dss/blobstore/gcs.py
- dss/blobstore/s3.py
- tests/test_blobstore.py
This way, we don't have to write cloud-specific error handling code everywhere.
> catch cloud-specific exceptions for `get_metadata()`  and throw a dss exception.

- tests/infra.py
- tests/test.py
This allows us to break the tests to smaller modules to improve testing time.
> move assert*Response magic to a new class

- dss/blobstore/__init__.py
- dss/blobstore/s3.py
- tests/test_bundle.py
- tests/test_file.py
get_presigned_url requires a method name, and that is not the same in each cloud.  I want to revisit this hideous hack later when time is less pressing.
> hideous abstraction layer for get_presigned_url

- dss-api.yml
- dss/api/bundles.py
- tests/test_bundle.py
1) list operation should belong inside the /bundles uri.
2) timestamp -> version
3) enforce data formats such as version: date-time and replica: (AWS|GC|Azure)
> Clean up the bundle interface.

- tests/expected_index_document.json
- tests/sample_data_loader.py
- tests/test_indexer.py
Fixed the  test for the change of the manifest 'files' section from a dict to a list.
Corrected handling of 'indexed' value in the test manifest and the resulting index document.
> Fix indexer test and corrected handling of 'indexed' value

- dss-api.yml
1. Return values are always lower case.  Input values remain case-insensitive.
2. Add patterns in some places where they are missing.
3. Clarify that the checksums are in hex format.
> Clarifications of the swagger spec.

- dss/api/files.py
- dss/blobstore/__init__.py
- dss/blobstore/s3.py
- tests/test_s3blobstore.py
I can't think of a good way to be simultaneously concise and retain the power of the underlying API.  Instead, we'll have explicit methods for each type of presigned urls we might want.
> Refactor the presigned url API.

- dss/hcablobstore/__init__.py
- dss/hcablobstore/s3.py
1. Make it a dict so other code can reference it more easily.
2. It's not going to be copied any more, just going to be mandatory to be present.
> Rename metadata list and make it more useful.

- dss/api/files.py
- dss/hcablobstore/__init__.py
- dss/hcablobstore/s3.py
- tests/test_s3hcablobstore.py
Now the new approach is:
1. Does the checksum on disk match our expectations?  If so, skip the copy.
2. Do the copy and verify that the copy was done correctly.
> Checksum-based mechanism for determining whether we copy.

- dss/api/files.py
- dss/blobstore/s3.py
- tests/test_file.py
Patch the tags into the metadata set.
For S3, metadata = metadata + tags.
Other cloud providers do not appear to have the notion of tags, so this is a S3-specific thing.
> Patch the tags into the metadata set.

- dss/api/bundles.py
- dss/api/files.py
```
{
"HTTPStatusCode": 404,
"exception": "An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.",
"message": "Cannot find bundle."
}
```
> Nicer error messages when we can't find a bundle or a file.

- dss/api/files.py
- dss/hcablobstore/__init__.py
- dss/hcablobstore/s3.py
- tests/test_file.py
- tests/test_s3hcablobstore.py
Removed the hackery we put in for the integration meeting.
Also added a test where a file with upper cased checksums get processed properly.
> Generalize the mechanism for lower-casing the metadata fields.

- dss/api/bundles.py
- dss/api/files.py
- requirements.txt
Use iso8601 to parse the timestamps, and datetime.datetime.strftime to format the dates.
> Remove ':' from the generated version names.

- daemons/dss-index/app.py
@mikebaumann, this makes the index daemon print a nice message on S3 test events (which get sent every time a deploy/event subscription happens) instead of an ugly stack trace. Please merge after review.
> Index daemon: Handle S3 test event without crashing

- dss-api.yml
- dss/__init__.py
- dss/api/search.py
- dss/events/handlers/index.py
- dss/util/__init__.py
- tests/expected_index_document.json
- tests/sample_data_loader.py
- tests/test_indexer.py
- tests/test_search.py
The two key changes here are:
- Indexer: replacing dot with underscore in the filename field of the index document
- Search API, both get (as Andrey provided) and post (as needed for the Boston demo)
Related changes include some refactoring for the indexer and search API to share common constants and code. There is some general code clean-up too, mostly to index.py, which adds to the diffs below.
> Changes to indexing and query for the Boston Demo

- .travis.yml
For whatever reason, wget flakes out often in the process of checking if ES is up, causing spurious test failures.
> Use nc instead of wget to check if ES is up

- tests/test_bundle.py
- tests/test_file.py
- tests/test_gcsblobstore.py
- tests/test_gcshcablobstore.py
- tests/test_indexer.py
- tests/test_s3blobstore.py
- tests/test_s3hcablobstore.py
- tests/test_search.py
- tests/test_sync.py
It turns out you can avoid E402 either by ignoring the import lines,
or the statement lines. In all our cases, the fixed-function import
hack is much less dangerous to ignore than the varied import lines
where we might make typos, etc.
> Invert noqa marker on import/path mangle lines where E402 is raised

- tests/test_gcshcablobstore.py
- tests/test_hcablobstore.py
- tests/test_s3hcablobstore.py
Use the checksums actually attached to the source files.  In the case of test_bad_source_data/incorrect_checksum, the checksums are intentionally set incorrectly so that the test will flag that as failures.
This should address #156.
> refactor the test_verify_blob_checksum test

- tests/test_api.py
1. get rid of usages of keyword `file`.
2. inline creation of file list to avoid type warning.
3. allow tests/test_api to be run from the command line.
> clean up test_api.py

- tests/test_bundle.py
- tests/test_file.py
This was a code path that was still using the same fixtures bucket name for both clouds, which is incorrect.  It has basically been a coincidence (i.e., people use the same name for their S3 bucket and their GS fixtures bucket) that this hasn't broken yet. :)
> Separate fixtures buckets for S3 and GS.

- chalice/build_deploy_config.sh
- daemons/build_deploy_config.sh
- iam/policy-templates/ci-cd.json
- iam/policy-templates/dss-index-lambda.json
- iam/policy-templates/dss-lambda.json
- scripts/authorize_aws_deploy.sh
es, lambda, and sns all seem to accept region wildcards, so there's no need to determine them or assume anything.
> Switch to region wildcards for services that permit region wildcards.

- iam/policy-templates/dss-index-lambda.json
- iam/policy-templates/dss-lambda.json
1. the indexer should use DSS_S3_BUCKET, which is set by daemons/build_deploy_config.sh.
2. the dss lambda should be able to read any bucket in order to ingest data.  NOTE: This means we need to disable read access on all other buckets owned by this account.
> Fix the policies set by the deployment script

- dss-api.yml
- dss/api/bundles.py
- dss/api/files.py
- dss/api/search.py
Use `operationId` to set the function name to something other than `list`.
> Avoid the list() keyword.

- chalice/app.py
- daemons/dss-index/app.py
- daemons/dss-sync/app.py
- dss/events/handlers/sync.py
- tests/test_bundle.py
- tests/test_file.py
- tests/test_gsblobstore.py
- tests/test_gshcablobstore.py
- tests/test_s3blobstore.py
- tests/test_s3hcablobstore.py
- tests/test_search.py
- tests/test_sync.py
1. remove unused imports
2. PEP8 requires two spaces before inline comment.
> [easy] assorted style fixes

- README.md
Added more complete documentation of the steps to setup DSS.
A few notes to the reviewer:
Populate.py does not have execute permission (at least not on my system), so the instructions explicitly include 'python' in the command line. Is this the best way to handle this case?
Tony had mentioned not using environment variables in the sample command line for populate.py, to instead have the user type the bucket names explicitly given the buckets will be emptied by populate.py. I didn't find a good way in markdown to within the code block display portions of the command syntax that should be replaced by the user. Also, the risk seems lower than before given the environment variables are for explicit test fixture buckets. Please let me know if you would like something different here.
Would you …
> Describe setup steps more completely in the readme

- requirements-dev.txt
- tests/fixtures/cloud_uploader.py
- tests/fixtures/populate.py
- tests/sample_data_loader.py
- tests/test_indexer.py
Changed cloud_uploader.py support for S3 and GS to use the APIs directly
rather than running CLI commands. This enables populate.py to be
used in unit tests with the moto S3 mock. It also runs much faster
than it did before.
Populate.py was modified slightly to enable convenient programmatic
use, in addition to CLI use.
This was tested both in the context of moto unit tests as well as
with actual S3 through the CLI. The amount of logging output is 
similar to before, which is useful for verifying operation when
run from the CLI. It currently does, however, increase the amount
of logging from a unit test run, now that it is being used in the 
unit tests as well. We may want to adjust that.
> Enable use of populate.py with moto S3 mock

- requirements.txt
- tests/es/__init__.py
- tests/test_indexer.py
There were some utility functions in `tests/test_indexer.py` that I should be able to use in my tests.
> Move es util functions into new es folder

- dss/__init__.py
- requirements.txt
- tests/test_indexer.py
@mikebaumann common place for us to be grabbing our queries index names and doc types. 
There will be two indices, `DSS_ELASTICSEARCH_INDEX_NAME` and `DSS_ELASTICSEARCH_QUERIES_INDEX_NAME`. 
`DSS_ELASTICSEARCH_QUERIES_INDEX_NAME` will only have one type, `DSS_ELASTICSEARCH_QUERIES_DOC_TYPE`, that contains callback info, creator_uid, and query.
`DSS_ELASTICSEARCH_INDEX_NAME` will have two types:
* `DSS_ELASTICSEARCH_DOC_TYPE` will hold all the metadata that the blue box inputs
* `DSS_ELASTICSEARCH_QUERIES_DOC_TYPE` will hold all of the percolate queries. The ids of these percolate queries will match up with the ids in `DSS_ELASTICSEARCH_QUERIES_INDEX_NAME/DSS_ELASTICSEARCH_QUERIES_DOC_TYPE`
Wasn't sure about how efficient keeping the percolate queries in the same index as the documents …
> [EASY] Add standardized index and type names for queries es index.

- dss-api.yml
- dss/api/files.py
- requirements.txt
1. werkzeug does this thing where it automagically adds HEAD to any route that handles GET, and it annoyingly cannot be turned off.  This causes all HEAD requests actually to be handled by the GET spec.  Previously, I believed that the spec was correctly determined, just the wrong code path was being chosen.  It turns out it's validating the wrong spec, but I didn't know because connexion wasn't actually validating default specs at all. 
https://github.com/zalando/connexion/commit/6668835420231c15095a71e264b2e2b0e1a68bf3 (ironically authored by me) exposed the issue because now the return values are actually properly validated.
2. move the HEAD first so it's added to the rules first.  This is probably not the right fix (the right fix is for werkzeug to evaluate *all* the rules on a HEAD …
> reorder HEAD and GET

- dss/__init__.py
- dss/error.py
There's now a DSSException type that has all the fields we want.
Additionally, there's a fallback exception handler which captures the uncaught exception and formats it in a safe way (although it's not verified).
This should address #221
> Capture exceptions and format them to the standard fields for errors.

- .travis.yml
@sampierson: I have enabled Travis CI to run a cron job daily. I'm not sure yet what time it gets triggered or whether it tries to deploy from the cron job (something we may want to disable). We'll see in 24 hours.
This change is a placeholder for you to add your integration test entry point when you're ready.
Fixes #198
> Add Travis CI cron job driven entry point

- dss-api.yml
- dss/api/files.py
- tests/test_file.py
Added a test for the error reporting.  This is an example to help facilitate discussion of #258 and #259.
> switch the /files not found message to the standard message format.

- dss-api.yml
- dss/api/subscriptions.py
See #248 
Only parameter there might be conversation about is replica. Replica isn't required as when getting bundles/files, but it is here because each subscription only lives on one replica, per https://docs.google.com/document/d/193u4w_gQzWNy1OK442KRApKF7hncckowvkNWGGCVRO4/edit#heading=h.ykmrpkea3e15
> Update dss-api.yml to include subscriptions endpoints

- .dockerignore
- Dockerfile
requirements-dev.txt now calls requirements.txt so we need both before
running pip.
Add in sourcing of environment before execution of python script.
Ignore the 10,000 files in daemons - they're not useful in the image and
just slow down image building.
> Get DSS running in Docker again

- dss/__init__.py
@ttung, I believe this is necessary when testing - @Mackey22 ran into this problem.
> Connexion error handler overload: translate response into Flask format

- dss-api.yml
- dss/error.py
- tests/test_file.py
Right now, parameter mismatches raise a generic TypeError.  We can't catch that because it could be an internal TypeError, and not necessarily tied to the parameters users send us.
Instead, we attempt to bind the functions to the args, and if that fails, then we know it's the arguments a user sends us.  If it passes, and some *other* TypeError is raised, we still send that to the generic exception handler.
Add test for this case.
Addresses issue #297, and thanks to @Mackey22 for finding this.
> Handle parameter mismatches and return 400.

- tests/test_search.py
Now passes tests/test_search.py standalone.
> Add missing dss.Config.set_config(..) to test_search.py

- Makefile
Create test targets for all the tests.  Then created a fast_test target that includes all of them.
Now you can run make -j fast_test and they are run in parallel and so so fast.
> Run unit tests in parallel.

- environment
When testing python bindings and cli in Travis, I get Forbidden errors because the requests are coming from an unauthorized domain. This will make testing possible.
> Add hca service accounts to allowed email domains for cli testing

- dss-api.yml
- dss/api/bundles.py
- dss/api/files.py
> Remove the top level GET /{files,bundles} endpoints.

- tests/test_file.py
This is to ensure that we exercise the file copy path.
To ensure that we exercise the identical-data path, we upload the same data twice.
> PUT /files should use random payload

- daemons/Makefile
- daemons/dss-chunked-task/.chalice/config.json
- daemons/dss-chunked-task/.chalice/deployed.json
- daemons/dss-chunked-task/.gitignore
- daemons/dss-chunked-task/app.py
- daemons/dss-chunked-task/requirements.txt
- dss/events/chunkedtask/_awsimpl.py
- dss/events/chunkedtask/aws.py
- dss/events/chunkedtask/awsconstants.py
- iam/policy-templates/dss-chunked-task-lambda.json
- tests/test_chunkedtask.py
The unit test fakes a more restrictive environment in order to run the test in a reasonable time (~15-20s).  There will be a test that runs against the standard `AWSRuntime` I will build that will run on the cron'ed test run.
This is the same as #287, but github most helpfully closed that for no apparent reason.
> Implementation of ChunkedTask tailored for AWS Lambda.

- dss/events/chunkedtask/base.py
- dss/events/chunkedtask/runner.py
- tests/test_awscopyclient.py
- tests/test_chunkedtask.py
This way, the AWS runtime can log a message indicating that its work is complete.
> Add a work_complete_callback() for runtimes to be notified when work is complete.

- dss/events/chunkedtask/_awsimpl.py
- dss/events/chunkedtask/aws.py
- dss/events/chunkedtask/awsconstants.py
- iam/policy-templates/ci-cd.json
- iam/policy-templates/dss-chunked-task-lambda.json
- requirements.txt
- tests/test_chunkedtask.py
1. Task scheduling happens through a `schedule_task()` method.
2. Work scheduling uses a versioned message now.  Therefore, it's future-proofed against message format changes.
3. Log each key event in the task lifecycle into a unique CloudWatch stream.
4. Updated test to watch these logged events rather than some hacky print statement at the end of a job.
5. Use watchtower to log messages.
> Clean up task scheduling and logging.

- codecov.yml
Unfortunately, enabling "bot" comments has made codecov noisy and obnoxious, since it seems to lose track of its previous comments often. Disable its PR comments until they figure that out.
> Disable codecov PR comments

- tests/test_chunkedtask.py
> Sleep per loop while we search for the completion marker.

- dss/events/chunkedtask/_awsimpl.py
- dss/events/chunkedtask/_awstest.py
- dss/events/chunkedtask/awscopyclient.py
- dss/events/chunkedtask/base.py
- dss/events/chunkedtask/runner.py
- tests/test_awscopyclient.py
- tests/test_chunkedtask.py
1. The existing `run_one_unit()` API has its contract changed to return None if there's more work, and the return value if it's done.
2. The return value is typed.
3. Updated the existing tests and code to reflect the change.
4. The return value, for the AWS runtime, is logged.
> Allow a completing task to return a value.

- tests/test_search.py
If we don't do this, we see errors on a brand new elasticsearch deployment.
I think this is probably some of the errors @csweaver was seeing.
> create index if it's missing in test_search

- .travis.yml
- dss/util/es.py
- tests/es/__init__.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
This way the test does not rely on any global state.  Adds a new required argument (only for tests) that DSS_TEST_ES_PATH be set to a valid elasticsearch binary.
> Start up an elasticsearch instance per test instance.

- dss/events/chunkedtask/aws.py
- dss/events/chunkedtask/awscopyclient.py
This is like a normal S3 copy client, except it has extra bits of state to manage writing the file manifest once the copy is complete.
> HCA-specific copy clients.

- dss/events/chunkedtask/aws.py
This is so that circular module dependencies can resolve.
> [easy] Move the clients list setup inside a method.

- tests/infra.py
PUT /files will possibly return multiple return codes until everyone is switched over to async PUT.
> Make assert*Response accept multiple response codes.

- tests/test_bundle.py
The bucket we use should be from the URL, and not from `Config.get_cloud_specific_handles(..)`
> Fix broken direct url test.

- dss/api/files.py
- tests/infra.py
- tests/test_bundle.py
- tests/test_file.py
1. PUT /files for AWS will now spawn a lambda to execute the copy.
2. tests are uploaded to use the `upload_file()` primitive that waits for completion.
> Update PUT /files to be async for AWS.

- tests/infra.py
info.filename is the full path.  this generates unnecessarily long and specific keys.
> [easy] strip the path from the generated key.

- dss-api.yml
- dss/api/files.py
1. Switch the crude `return (make_response(..), requests.codes...)` to `raise DSSException`
2. Add the 202 result code.
3. Add fallthrough error handling.
4. Improve the description fields.
> Clean up result handling for PUT /files.

- dss/events/chunkedtask/runner.py
- tests/test_s3copyclient.py
1. In the constructor of `Runner`, we should not consider the time-remaining-to-run in calculating the estimated time for how long a block takes.  This is an artifact from when I structured the code differently, to ensure that we at least process one unit of work.
2. Update the stats about how long a work unit takes before we decide if we want to run more work.
3. Time overhead factor on the wrong side of the equation.
> Fix bugs in how we deal with time-remaining.

- chalice/app.py
- daemons/dss-sync/app.py
- dss/events/handlers/sync.py
- scripts/deploy_gcf.py
- Fix SNS topic names to be per-stage (and also to match the per-stage IAM permissions)
- Propagate object metadata when performing multipart/composite object copy
- Deploy a per-stage GCF event relay for deployment sanity and because it seems a given GCF can only be subscribed to one bucket event source
Tested manually - tests for all of this are coming in the integration test suite.
> Fixups for sync engine

- dss/__init__.py
This is needed to be able to run staging and dev using the same ES cluster, which I'd like to keep doing for now. (Prod will get its own cluster)
Connected to #232
> Parameterize ES index name by stage

- tests/chunked_worker.py
1. A queue to track all the work that still needs to be run.
2. Each iteration of the loop removes a unit to run, constructs a runtime object and a task object, and runs it.  If there's more work to be run, save the state into the queue.
> A method to drive a task to completion.

- tests/test_chunkedtask.py
No reason to have two Runtimes that essentially serve the same purpose.
> refactor chunked worker tests to use the common stingy runtime.

- daemons/dss-index/app.py
- dss/events/handlers/index.py
- tests/test_indexer.py
Pass GCP events received via GCF/SNS to the indexer.
Log additional details in the case of a file access error during indexing.
smoketest.py output of test deployment:
```
$ scripts/smoketest.py 2>&1 | tee smoketest0.0.txt
'import warnings' failed; traceback:
File "/usr/local/Cellar/httpie/0.9.9/libexec/bin/../lib/python3.6/warnings.py", line 505, in <module>
_processoptions(sys.warnoptions)
File "/usr/local/Cellar/httpie/0.9.9/libexec/bin/../lib/python3.6/warnings.py", line 186, in _processoptions
_setoption(arg)
File "/usr/local/Cellar/httpie/0.9.9/libexec/bin/../lib/python3.6/warnings.py", line 192, in _setoption
import re
File "/usr/local/Cellar/httpie/0.9.9/libexec/bin/../lib/python3.6/re.py", line 122, in <module>
import enum
ModuleNotFoundError: …
```
> Connect GCP events to indexer

- daemons/dss-index/app.py
- dss-api.yml
- dss/__init__.py
- dss/api/search.py
- dss/api/subscriptions.py
- dss/config.py
- dss/events/handlers/index.py
- dss/util/es.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
Change Elasticsearch index names to be replica specific to enable replica
independent indexing, search, subscription/notification.
This commit is focused on replica specific indexing, with changes
to search and subscription for all tests to pass with replica specific indexes.
Additional changes are required to make the search route replica aware,
and additional GCP-specific testing is required for subscriptions,
which will be done as additional PRs.
> Make Elasticsearch indexes replica specific

- tests/fixtures/cloud_uploader.py
If the variable contains a '%', it may be treated as a formatting operation.
Connects to #427
> first argument logger.XXX should be a formatting string

- scripts/deploy_gcf.py
This should help with errors like this, which we see in the deploy stage occasionally:
```
make[1]: Entering directory '/home/travis/build/HumanCellAtlas/data-store/daemons'
/home/travis/build/HumanCellAtlas/data-store/scripts/deploy_gcf.py dss-gs-event-relay --entry-point "dss_gs_bucket_events_org_humancellatlas_dss_staging"
Waiting for deployment........................................GRTC config dss_gs_bucket_events_org_humancellatlas_dss_staging found
Writing GRTC variable AWS_ACCESS_KEY_ID
Writing GRTC variable AWS_SECRET_ACCESS_KEY
Writing GRTC variable AWS_REGION
Writing GRTC variable sns_topic_arn
Adding Readme.md
Adding index.js
Adding package.json
Uploaded <Blob: org-humancellatlas-dss-test-fixtures, dss-gs-event-relay-staging-deploy-2017-09-15-18-14-01-fa74cd74.zip>
{'name': …
```
> Retry PUT requests on 504 errors

- iam/policy-templates/ci-cd.json
This is needed for the deploy script in the cron script.
This depends on #477 because by itself, it would put us past the 2048 character limit.
> add write access to staging bucket.

- dss/__init__.py
- requirements-dev.txt
- requirements.txt
- requirements.txt.in
We use the chalice cli runner, which doesn't do auto-reload anyway.
> [easy] remove flask-failsafe.

- dss/config.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
- Added the environment variable `TEST_MODULE_NAME` to test cases that use an elasticsearch index. 
- Modified `get_es_index_name()` to append the `index`  with `TEST_MODULE_NAME` if `DSS_DEPLOYMENT_STAGE == Test`. 
We can now run the test cases in parallel to speed up execution time.
Connects to #355
> added test specific index to indexer

- daemons/Makefile
dss-chunked-task is empty, it should point to chained-aws-lambda.
> [easy] point deploy rule to the correct sub-rule.

- daemons/Makefile
- daemons/dss-s3-copy-write-metadata.filter
- dss/events/chunkedtask/s3copyclient.py
- requirements-dev.txt
- requirements.txt
1. We weren't invoking the parallel mode because we didn't write the parallel field.  Whoops.
2. We weren't deploying the child worker daemon.  This did not surface as a bug because of `(1)`.  Add Makefile & jq madness to fire up the child worker daemon.  The jq stuff is needed to enable the parent worker to call the child worker.
3. Upgrade chained-aws-lambda to pick up the statementid (sid) changes (https://github.com/chanzuckerberg/chained-aws-lambda/commit/6f10a132f82bb06c732e0f8bf0fcd0b3ff3e0682) to simplify the jq logic.
> Fix issues with parallel copy.

- tests/test_indexer.py
If we don't send a content-length, the python requests library will sit there and continue to try to read until the network connection is severed.  This is happening because (after some of my other changes), there's a library that's polluting the http.server globals (I haven't tracked this down) and enabling HTTP/1.1, which supports resumes.
> Send a content-length header to prevent a deadlock.

- tests/test_indexer.py
- tests/test_search.py
This will fix some search and index test cases from failing occasionally due to timeout.
Fixes #502
> [easy] increase test timeout for test search and index

- dss-api.yml
- dss/api/files.py
- tests/test_file.py
This makes it easier to manage API clients that have to do retries.  Idempotence means that they can just blindly try until they succeed.
It is idempotent as long as the parameters are identical.
This depends on #491.
Connects to #399
> make PUT /files idempotent.

- tests/smoketest.py
Use string substitution instead of env replacement for sample id.
> Respect the user's PATH when running the smoketest.

- tests/smoketest.py
Along with #518, this allows the smoke test to complete.
> Add a reasonable search for the smoke test.

- dss/util/__init__.py
- tests/test_utils.py
Also adds a `has_query()` method, which returns True if there's a query field with a given name.
> Allow users of the URLBuilder API to set the query.

- daemons/Makefile
```
[czipa1osx186 (.venv)]:~/hca/data-store:tonytung-stage> cat daemons/Makefile | grep dev
[czipa1osx186 (.venv)]:~/hca/data-store:tonytung-stage>
```
Let's find out, shall we?
> stage should be parameterized and not hardcoded to dev.

- .travis.yml
Use the -O mode, which buffers output and groups it by process.
> parallel make test should not intermix output.

- dss-api.yml
- dss/events/handlers/index.py
- requirements.txt
- requirements.txt.in
- tests/test_indexer.py
Also:
- check against local resource access attacks in redirect URLs
- require https webhook URLs in production
> Add support for signing webhook payloads with HMAC

- dss-api.yml
- dss/api/search.py
- tests/test_search.py
Search will now return the `count` which is equal to the number of results matching the `es_query`. The search testcase have been updated to check the total count is equal to number of documents indexed.
> added total matching results to search response.

- tests/infra/server.py
Since our execution can theoretically take up to 30s, let's be patient about responding.
Test no longer spews out errors about requests timing out.  It fails for other reasons now!
> Be more patient with test requests.

- dss-api.yml
- dss/api/search.py
- tests/test_search.py
When a search is executed and additional results available Partial (206) is returned with a link in the header with the next url. When all results are returned OK (200) is returned and no link is in the response header.
> Added response partial to search.

- Makefile
- requirements-dev.txt
- requirements-dev.txt.in
- scripts/release.sh
Automates releases of code from master to staging and from staging to prod (and between any two other branches, as long as an environment config file exists).
Checks for CI status and allows bypass.
Checks for commits only on the target branch.
I'm particularly interested in your review of the git commands. They include a delightful `git push --force` :shipit: 
Connects to #467
> Release automation script

- tests/fixtures/cloud_uploader.py
I did a poor job of reviewing #509.  I reviewed it for logical correctness rather than whether it makes sense as a whole.  The only changes we need are the changes to the static test data.  We don't need to tag the size data as metadata since that's freely available from the cloud provider.
> revert unnecessary changes

- chalice/.chalice/config.json
- dss-api
When we use the chalice app in tests, we override the timeout.  When we use the chalice app on lambda, the timeout is valid.
However, in the current version of chalice we're using, calling `get_remaining_time_in_millis()` throws an exception when not run in a lambda. 
This diff:
1. Sets the timeout in config.
2. Overrides the timeout set in config due to a chalice bug (see https://github.com/aws/chalice/pull/579)
> Fix timeouts for invocations on the command line.

- chalice/app.py
- daemons/dss-chunked-task/app.py
- daemons/dss-index/app.py
- daemons/dss-sync/app.py
- dss/__init__.py
- dss/config.py
- tests/test_api.py
- tests/test_bundle.py
- tests/test_file.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
- tests/test_sync.py
It's actually really BucketConfig, and not DeploymentStage.
I know we once renamed this from BucketConfig to DeploymentStage, but this really has no relationship with the deployment stage, which is controlled by `DSS_DEPLOYMENT_STAGE`.
> [easy] rename DeploymentStage to BucketConfig

- dss/api/bundles.py
- dss/api/files.py
- dss/hcablobstore/__init__.py
- requirements-dev.txt
- requirements.txt
Lookup size during file/bundle put.
Backward compatible size metadata on write path.
Read path to come later.
Expects get_size() from cloud_blobstore.
Connects to #471
Unit tests after read/write path finished.
> size metadata written on file/bundle put

- dss-api.yml
- dss/api/bundles.py
- tests/test_bundle.py
There's no way we can know if the missing file is due to race conditions or not, but we code a specific error so clients can retry in this scenario.
Also improve the existing documentation for 409 CONFLICT (previously nonexistent, of course).
Connects to #464
> Specific error condition/code for missing files.

- tests/test_indexer.py
Updated test_indexer.test_subscription_notification_successful to
reset the notification test handler between notifications within the same test.
See issue #580 for details.
Fixes #580.
> Updated test_indexer to reset test notification handler between uses

- tests/smoketest.py
Corrected hca option use in smoketest.py that was causing this test to fail.
This failure may be seen in Travis build: https://travis-ci.org/HumanCellAtlas/data-store/builds/292794550
This failure was reproduced and the fix was verified using a deployment of the current master branch at UCSC.
> Corrected CLI option in smoketest

- dss/__init__.py
- dss/config.py
- dss/events/handlers/index.py
- tests/test_config.py
- tests/test_indexer.py
If we don't nip this in the bud, we'll have the codebase littered with `os.environ["DSS_DEPLOYMENT_STAGE"] == "ababab"` and that would be awful.
Depends on #561
> Deployment stage + magic methods to invoke.

- daemons/Makefile
- dss/__init__.py
- dss/events/chunkedtask/s3copyclient.py
Roman needs this for the checkout service.
> Add the parallel copy supervisor to the list of chained-aws-lambda clients we enable.

- dss/api/files.py
- requirements-dev.txt
- requirements.txt
- tests/fixtures/cloud_uploader.py
- tests/fixtures/populate_lib.py
- tests/test_file.py
This removes the usage of the hca-dss-content-type field.
Connects to #605 
Tested by populating test fixtures buckets and running `DSS_GS_BUCKET_TEST_FIXTURES=org-humancellatlas-dss-test-fixtures-ttung DSS_S3_BUCKET_TEST_FIXTURES=org-humancellatlas-dss-test-fixtures-ttung make tests/test_file.py`.
The travis run is likely to fail, unfortunately, until I run this on the main test fixtures bucket.
> Use the cloud-native content-type attached to the src data blob.

- chalice/app.py
- dss/api/bundles.py
- requirements-dev.txt
- requirements.txt
- requirements.txt.in
- tests/test_bundle.py
We've observed that there are race conditions on S3 where a `PUT /files` has completed but the metadata files are not available on the subsequent `PUT /bundles` request.  We added logic to make it easier for the client to identify this situation (and retry) in #566, but it is desirable to attempt the retry on the server as well.
Connects to #464
Verified that the existing paths still work.
Added test that sets up a missing file, starts a `PUT /bundles` request, and then uploads the missing file.
> spin-loop for PUT /bundles on missing file

- tests/test_search.py
py-elasticsearch timeout is quick for DNS failures, but seems to be taking a lonnnng time for DNS success, no ES running.
> Bogus is not the least likely hostname to exist

- .gitignore
- tests/smoketest.py
smoketest installs the CLI into the currently active virtualenv or even the global site-dist if no virtualenv is active. The CLI's dependencies might differ from those of data-store creating potential breakage in data-store after smoketest.py runs. This PR changes smoketest to install the CLI into a temporary virtualenv and remove it afterwards.
Run smoketest.py manually.
> Prevent smoketest from clobbering the current virtualenv

- dss/stepfunctions/lambdaexecutor/__init__.py
- tests/test_lambdaexecutor.py
Copy-paste from the docblock:
This is a "Thread" class that runs a job for a maximum period of time.  The class provides concurrency-safe methods to retrieve and persist a chunk of state.
You can use this primitive to wrap your lambda execution such that you send a consistent chunk of state out of the lambda back to AWS step functions.
> Introduce TimedThread.

- tests/smoketest.py
fixes #652
Run smoketest locally and temporarily enable it for Travis builds of this PR.
> Fix smoketest on Travis (fixes #652)

- tests/test_standalone_script.py
For reasons unclear to me, the standalone test is now failing without this.  It appears that it is waiting for the test connection to make its request, and that never happens, and it does not answer subsequent requests.
> close the test connection.

- dss/api/search.py
- tests/test_search.py
Fixes https://github.com/HumanCellAtlas/data-store/issues/582
Connects to https://waffle.io/HumanCellAtlas/data-store/cards/59f0d13a29243f01cc41eb1d
TODO: The absence of the `metadata` field in non-raw output queries is tested for. The presence of `_source` information in the `metadata` field is tested for in raw output queries.
> DSS-582: only return _source info on 'raw' output_format

- Makefile
- daemons/Makefile
They both edit the bucket notifications, which can conflict when run in parallel.
To compensate for this, I parallelized chalice deploy with daemon deploy. :)
Connects to #668
> Serialize the deployment for dss-sync and dss-index

- iam/policy-templates/ci-cd.json
Grant Travis CI group permission to create state machine. This is needed as port of the deployment performed by Travis
> Grant permission to create state machine to the Travis CI group

- dss/api/search.py
- dss/api/subscriptions.py
- dss/config.py
- dss/events/handlers/index.py
- dss/util/es.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
Rather than accessing indexes directly they are now accessed through an alias name. This helps with reindexing and indexing by major version. For now the alias will only point to a single index. 
Connected to #594
Updated units test to reflect change. Will need further refactoring once indexing by major version is implemented.
Do not merge until reindex is supported.
split get_elasticsearch_index into get_elasticsearch_subscription_index, and get_elasticsearch_doc_index
using document version to create the actual index
adding new indexes to alias on creation.
> New indexes are alias when created and access by alias name.

- Makefile
- README.md
1. Modifies the requirements{,-dev}.txt targets such that they are incremental, i.e., they install {requirements,-dev}.txt, then {requirements,-dev}.txt.in, and then freezes.  If you add just one new requirement to {requirements,-dev}.txt.in, it will not update everything.
2. refresh_all_requirements will empty out the existing requirements.
Connects to #678
> refresh_all_requirements target that blows away requirements.

- Makefile
- README.md
- requirements-dev.txt.in
- requirements.txt.in
Since we have an easy way to do small updates to requirements.txt and requirements-dev.txt, we should unpin so we can stay up to date and avoid the accumulation of technical debt.
> unpin requirements.txt and requirements-dev.txt

- dss/config.py
- dss/events/handlers/index.py
- tests/test_indexer.py
Place bundle index document in an ES index appropriate for the shape/structure/format 
of the metadata in the index document, so that it may be indexed successfully
without conflict.
The name of the index includes identification of the metadata schema release major number:
For example:
v3 - Bundle contains metadata in the version 3 format
v4 - Bundle contains metadata in the version 4 format
...
If no metadata version information is contained in the bundle, the bundle index document
is (attempted to be) added to the an index without a version identifier.
Currently this occurs in the case of the empty bundle used for deployment testing,
and perhaps other test data.
If/when bundle schemas are available, indexing should be updated to reflect the
bundle schema type and major version number. …
> Index documents according to metadata schema major version number.

- dss/api/subscriptions.py
- dss/config.py
- dss/events/handlers/index.py
- dss/events/handlers/mapping.json
- tests/sample_search_queries.py
- tests/test_indexer.py
- tests/test_subscriptions.py
Ensure subscription queries are added to indices, and do so in a way
that allows queries including fields not defined in the index mappings.
This enables subscription of queries that work across metadata schema versions,
including fields that are not present in a schema version or have
changed between versions, such as a field changing from type text to type object.
This also resolves internal constraints of needing to have the mappings defined
in an index before a subscription query for percolation can be added to the index.
This is accomplished by setting index.percolator.map_unmapped_fields_as_string to true,
which also works in the case of other field types (e.g. numeric, date).
Note when dynamic templates are used and queries for percolation have been added
to an index before the …
> Finish changes for schema version specific subscription/notification

- dss/config.py
- tests/fixtures/datafiles/indexing/bundles/unversioned/smartseq2/paired_ends/assay.json
- tests/fixtures/datafiles/indexing/bundles/unversioned/smartseq2/paired_ends/cell.json
- tests/fixtures/datafiles/indexing/bundles/unversioned/smartseq2/paired_ends/manifest.json
- tests/fixtures/datafiles/indexing/bundles/unversioned/smartseq2/paired_ends/project.json
- tests/fixtures/datafiles/indexing/bundles/unversioned/smartseq2/paired_ends/sample.json
- tests/fixtures/populate_lib.py
- tests/sample_search_queries.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
Test with version 2 (unversioned) data bundles, in addition to current (version 3)
data bundles. Verify correct aliases and indices are crated and that both version-specific
and multi-version searches and subscriptions/notifications work as expected.
**The populate.py script must be run to update the text fixture buckets for these tests
to pass.**
Tests with version 4 and later data will be added when the data is available.
> Unit tests for multiple schema version indexing, search and subscription/notification

- iam/policy-templates/dss-lambda.json
Fixes #699 (please see this issue for details)
With this change, smoketest passes on master.
> Enable dss Lambda to use "es:ESHttpPost" to ES server

- environment
- tests/smoketest.py
> Smoketest fixes to go along with the CLI updates

- daemons/Makefile
- scripts/deploy_checkout_lifecycle.py
Apply S3 lifecycle rule to the checkout bucket to automatically expire files based on the creation date. Connects to #641  
Manually validated via AWS S3 console - confirmed that lifecycle rule is installed. 
Also set shortest possible expiration period 1 day and confirmed:
- files are deleted next day
- checkout of the same bundle updates date created and resets the "timer"
> Apply checkout bucket expiration policy

- dss/events/handlers/index.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
I would like to introduce a little OO into index.py. The benefit of this refactoring is that it makes more obvious how data flows between methods when preparing a document for indexing. The method signatures are simplified because contextual arguments are converted to instance attributes, for example `logger` and `replica`.
This change increases the line count mostly because it adds another way of constructing a BundleDocument from a ES document JSON.
This is a pure refactoring with minimal functional changes.
Reviewers are encouraged to review the diff with a tool that highlights intra-line changes, e.g. PyCharm. The diff will become very small as I paid close attention to not move code around, to the extent that one function became a method of BundleDocument even though it should not …
> Extract BundleDocument class from indexer

- dss/stepfunctions/__init__.py
Utility methods needed for visitation batch processor, may
be useful for other step function consumers.
connects to #539
Continued from #714 which was merged in error.
> A few extra step function utility methods.

- dss/config.py
- dss/events/handlers/index.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
Starting to reap the benefits of the `BundleDocument` refactoring.
The reasoning for renaming `index shape identifier` to `shape descriptor` is that the former might be misinterpreted as the shape of an index, whereas the latter more accurately describes the shape of a document.
Reviewers should look at each commit separately.
> More indexer refactorings

- tests/test_search.py
The `test_elasticsearch_bogus_endpoint_exception` test will fail if the resolver used to run the test does not return that the hostname does not exist.
This pull request skips this test if the resolver matches the bogus hostname.
> Remove the ES bogus endpoint test

- tests/infra/server.py
… or any other IDE that uses pydevd.
This change use a more static approach for reexporting the `requests.api` methods on `ThreadedLocalServer`. With the original `__getattr__`-based approach I get
```
Fatal Python error: Cannot recover from stack overflow.
```
and the process crashes with SIGABRT.
The currently recommended workaround of enabling Genvent-compatible debugging avoids the SO but trashed stderr with hundreds of these:
```
File "/Users/hannes/workspace/hca/data-store/.venv/lib/python3.6/site-packages/werkzeug/urls.py", line 425, in <genexpr>
if not rest or any(c not in s('0123456789') for c in rest):
SystemError: error return without exception set
Exception ignored in: <generator object url_parse.<locals>.<genexpr> at 0x105169d58>
```
> Fix stack overflow when debugging test_indexer.py with PyCharm (alternative 3/3)

- daemons/dss-index/app.py
- dss/events/handlers/index.py
- tests/test_indexer.py
This improves modularity of the indexing code and separates the
unpacking of the AWS s3 events from GCP CloudStorage events.
> Create IndexHandler class.

- Makefile
- tests/infra/__init__.py
- tests/infra/testmode.py
- tests/test_file.py
Targets:
tests/test_xyz.py: this will run both the standalone and integration tests in tests/test_xyz.py
integration__tests/test_xyz.py: this will run the integration test in tests/test_xyz.py
standalone__tests/test_xyz.py: this will run the standalone test in tests/test_xyz.py
test: this will run both the standalone and integration tests in tests/*
integration_test: this will run the integration tests in tests/*
standalone_test: this will run the standalone tests in tests/*
The environment DSS_TEST_MODE selects which type of tests to run.  If the word "integration" is in the env var, then it runs the integration tests.  If the word "standalone" is in the env var, then it runs the standalone tests.   DSS_TEST_MODE _can_ contain both words, in which case, both sets of tests are run.
> annotate tests with standalone vs integration

- dss/config.py
- tests/es/__init__.py
- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
Clear the contents of ES indices between tests instead of removing the indices completely.
Index creation is time consuming and this improves the performance of the tests.
Fixes #654 
Fixes #644 
No conflicts
> Clear index per test

- dss/stepfunctions/s3copyclient/__init__.py
- dss/stepfunctions/s3copyclient/implementation.py
Most of the code is lifted from dss/events/chunkedtask/s3copyclient.py.
Depends on #704, #707.
> Definition for a parallelized s3 copy state machine that also writes file metadata.

- daemons/dss-sync/app.py
- dss/hcablobstore/__init__.py
- dss/hcablobstore/gs.py
- dss/hcablobstore/s3.py
- requirements.txt
- requirements.txt.in
This release renames any `object_name` arguments to `key`
> Bump cloud-blobstore dependency to 1.0.0

- .travis.yml
- daemons/integration-test/.chalice/config.json
- daemons/integration-test/app.py
- daemons/integration-test/requirements.txt
1. Added configuration in .travis.yml to run standalone tests normally.
2. Added configuration in .travis.yml to run integration tests when TRAVIS_DSS_INTEGRATION_MODE is non-empty.
3. Added a daemon that kicks off integration tests every hour.
> Daemon to kick off integration tests.

- dss/api/bundles/__init__.py
When user email is unauthorized in bundles/delete, "Forbidden" fails
response validation and a 500 error is returned. Lower case "forbidden"
passes response validation, returning the correct 403 response.
Incorrect 500 error:
{'detail': "'Forbidden' is not one of ['forbidden']\n"
'\n'
"Failed validating 'enum' in "
"schema['allOf'][1]['properties']['code']:\n"
"    {'description': 'Machine-readable error code.  The types of "
"return '\n"
"                    'values should not be changed lightly.',\n"
"     'enum': ['forbidden'],\n"
"     'type': 'string'}\n"
'\n'
"On instance['code']:\n"
"    'Forbidden'",
'status': 500,
'title': 'Response body does not conform to specification',
'type': 'about:blank'}
> Fix validation error: Forbidden -> forbidden

- .travis.yml
Since it has an exclamation mark, it needs to be quoted.
> condition needs to be quoted.

- README.md
The README should mention the checkout buckets. 
Without those buckets `make deploy` fails with
```
File "/Users/hannes/workspace/hca/data-store/scripts/deploy_checkout_lifecycle.py", line 19, in <module>
'ID': "dss_checkout_expiration",
File "/Users/hannes/workspace/hca/data-store/.venv/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/Users/hannes/workspace/hca/data-store/.venv/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutBucketLifecycleConfiguration operation: Access Denied
make[1]: *** [dss-checkout-sfn] …
```
> Mention checkout buckets in README

- daemons/dss-sync/app.py
I did a grep of `"gcp"` and it's clean.  Found some `"aws"` but will file that separately as that's an entirely different code path.
> Replicas are now enums, not strings.

- daemons/build_deploy_config.sh
- daemons/dss-checkout-sfn/.chalice/config.json
- daemons/dss-checkout-sfn/app.py
- dss/stepfunctions/checkout/checkout_states.py
- iam/policy-templates/dss-checkout-sfn-lambda.json
Implement 60 minutes timeout for the overall bundle checkout
Implement retries for individual steps in the workflow including
TaskFailed
Timeout
Other
Configure intervals, max attempts and back-off rates
Test plan
Manually injected delays and failures in the lambda using alternative stage configuration. Confirmed complex retry behavior by analyzing execution log in AWS Step Function console
connect to #614
> Fault tolerance for checkout service

- tests/fixtures/datafiles/indexing/bundles/v4/smartseq2/paired_ends/assay.json
- tests/fixtures/datafiles/indexing/bundles/v4/smartseq2/paired_ends/project.json
- tests/fixtures/datafiles/indexing/bundles/v4/smartseq2/paired_ends/sample.json
- tests/fixtures/populate_lib.py
- tests/sample_search_queries.py
- tests/test_indexer.py
Updated test_indexer to use new test data.
Must run populate before running tests.
Added version 4 testdata to the test fixtures buckets.
> Tsmith v4 test data

- .travis.yml
- Makefile
The first commit fixes a bug in .travis.yml and removes a stale .PHONY declaration.
The bug causes non-IT builds tests to essentially skip tests and IT-builds to only run standalone tests. Any PR builds of branches based on b8290d240a4c7f20753122415a6df5a6666414c8 should be disregarded and the branches rebased once this is merged. 
The second commit makes the target naming in Makefile more intuitive.
> Fix Makefile target mixup

- dss/stepfunctions/visitation/implementation.py
- tests/test_visitation.py
Pass parallel input directly to output.
Bugfix avoiding state loss when catching exceptions.
> Avoid large state in visitation Parallel, bugfixes

- dss/storage/validator.py
- tests/fixtures/datafiles/indexing/bundles/v3/smartseq2/paired_ends/project.json
- tests/test_indexer.py
Fixes #804 
Fix for Validator KeyError
- Added testing for json schemas with patternProperties.
- Added testing for extra fields in different json files.
- Run populate on test fixtures.
- Added EXTRA_FIELD_ERROR_REGEX and adjust regular express to extract field names from both error messages found in jsonschema._validators.additionalProperties.
- Added characteristics field to ./tests/fixtures/datafiles/indexing/bundles/v3/smartseq2/paired_ends/project.json.
- Fixes #804
> Validator KeyError Fix (fixes #804)

- dss/storage/validator.py
Here is another way we could get the fields. It might cost a bit more since `jsonschema._utils.find_additional_properties` is called twice per `document`. The first call is by `_validators.additionalProperties`, the second time is by us.
Using `jsonschema._utils.find_additional_properties` to find extra fields over `re.findall`. This is less prone to breaking since extra fields are extracted by comparing the `json_data` with the `schema` and not the `error.message`.
> Make Validator More Robust

- .coveragerc
- .gitignore
- dss/config.py
- dss/util/bundles.py
- tests/infra/storage_mixin.py
- tests/test_bundle.py
- tests/test_config.py
- tests/test_indexer.py
I think get_cloud_specific_handles() is ill-conceived. If you look at its call sites, you'll see that often only a subset of its three return values are used.
This takes us one step closer to its elimination. The typesafe Enum pattern encourages converting code like
```
if foo == Foo.x:
return ...
elif foo == Foo.y:
return ...
```
into instance methods of the enum class.
> Allow for getting bucket name without instantiating blob store objects

- Makefile
This is purely cosmetic. It bugged me `test_srcs` wasn't used for the `test` target. With this change
* `test` uses test_srcs
* `integration_test` uses integration_test_srcs
* `all_test` uses all_test_srcs
> Make variable naming more consistent with test target names

- daemons/dss-index/app.py
- dss/events/handlers/index.py
- dss/storage/bundles.py
- dss/storage/index_document.py
- dss/util/es.py
- dss/util/retry.py
- tests/test_doctests.py
- tests/test_indexer.py
This refactors the indexer considerably in order to get it ready for the REPAIR and VERIFY modes of reindexing. It adds a general @retry decorator and uses that decorator to retry indexing on 409 versioning conflicts and 5xx server errors.
> Reindexing 1/3: Prepare indexer code for REPAIR and VERIFY, add retry

- tests/test_smoketest.py
importing tests.* should happen after the path hack.
@amork noticed that `make smoketest` fails.
> Fix smoketest imports

- dss/storage/index_document.py
- tests/sample_v3_index_doc.json
- tests/test_indexer.py
The UUID is added to the index document for both regular bundles and bundle tombstones.
Connects to #801 
Test search by bundle UUID in deployed system.
> Include bundle UUID in index document to enable searching by bundle UUID

- .travis.yml
- Makefile
When the `-O` make option is used in conjunction with `-j`, the output of an entire recipe is buffered and printed atomically when the recipe finishes. I have the suspicion that this 1) interferes with Travis' build output handler and 2) causes truncated build logs. This PR
* prefixes every line in the test output with the shell's PID which is going to be unique per line in the recipe. The test recipes only consist of one line, so each test module's output will be prefixed with a different number. A stable, lexical sort of the build output will produce a result resembling that of `-O`.
* passes `-v` to unittest for Travis builds, making the test output more lively. A nice side effect of `-v` is that it also prints which individual test methods were skipped.
* removes `-O` for test-related …
> Prevent test output from being delayed by `make`

- tests/readme.md
At this point all test cases have been tagged. Finishing up #751 by adding a readme to tests as a reminder to add the decorator to your test cases.
> Described testmode integration and standalone in ./tests/readme.md

- iam/policy-templates/dss-checkout-sfn-lambda.json
The change is required due to switching to the step function-based implementation of the parllel copy. dss-checkout-sfn-* lambda needs to be able to start and describe executions of the dss-s3-copy-sfn
> Add permissions to sfn checkout to execute sfn-based copy

- dss/api/bundles/checkout.py
- dss/util/email.py
In order to avoid exposing account id and region switch from using ARN to uuid4-based sfn execution id.
Also update format of the checkout S3 location.
Tested locally by initiating a checkout process then using returned checkout job id in the check status invokation.
Integration and also mmoke test in dev cover this.
> Use execution id instead of ARN

- scripts/kibana-proxy.py
This is useful for running Kibana against an Amazon Elasticsearch instance without having to change the access policy to allow requests from your local IP. It works by running Kibana through a proxy that signs the requests with your AWS credentials.
> Add utility for using Kibana with AWS credentials

- tests/test_file.py
Isolate the upload portion, which is the most cloud-specific aspect of the whole operation.
> refactor the `test_file_put_large` test to more easily accommodate additional replicas

- dss/config.py
Each replica encapsulates its parameters, simplifying the getters considerably.
Depends on #869
> Simplify Replica class

- dss/hcablobstore/__init__.py
This is so we can satisfy type checking for a generic construction of a HCABlobStore from a BlobStore.
> Add a constructor to the HCABlobStore base class

- dss/stepfunctions/gscopyclient/implementation.py
I merged incorrectly. We should be using get_gcp_client(..) until #873 updates to the new API.
> Fix merge damage

- iam/policy-templates/dss-visitation-lambda.json
This is necessary since the indexer caches schema URLs there.
> Let visitation lambda write to storage bucket (resolves #913)

- tests/test_indexer.py
This test is flaky and is causing false negatives in test runs.
> Disable flaky tests.

- dss/util/es.py
Status code is typically a number but can be 'N/A'.
> Fix type error in retry logic for Elasticsearch (fixes #928)

- scripts/deploy_gcf.py
Deployment of `dss-gs-event-relay` currently relies on the existence of GCP test fixture buckets. This can be avoided with `gcloud beta functions deploy`.
Unfortunately the gcloud method is in beta.
Connects to #856 
FIxes #923
> Use gcloud command to deploy dss-gs-event-relay

- .travis.yml
- Makefile
- dss/util/es.py
A variant of https://github.com/HumanCellAtlas/data-store/pull/941, based on @kislyuk's [preference](https://github.com/HumanCellAtlas/data-store/pull/941#pullrequestreview-94536735) but with the following differences:
* retains @ttung's [requirement](https://github.com/HumanCellAtlas/data-store/pull/941#issuecomment-363554076) that, by default, tests are run in parallel
* keep standalone the default test mode, as currently on master
* serial tests are run in parallel to parallel test (but obviously not in parallel to each other)
> 1b/2: Serialize tests that use local ES instance; increase ES heap

- dss/events/handlers/index.py
- dss/storage/index_document.py
- dss/util/es.py
- tests/test_indexer.py
The tests that involve retries log a bunch of expected but scary looking exceptions. This change traps them in a mock and asserts them instead.
Test @retry in `Elasticsearch.get` as well as in `.index`.
Change the logger used by Elasticsearch retries to the module logger of the retried function instead of the @retry module's logger.
> 2/2: Make test_indexer logs less noisy; improve @retry test coverage 

- dss/stepfunctions/s3copyclient/implementation.py
In this case, we don't use it, so just throw it away.
Fixes #961
> callbacks for `Future.add_done_callback` expect a single argument.

- tests/test_indexer.py
- tests/test_search.py
- tests/test_subscriptions.py
Moving the testmode decorators to the class level prevents the class setup/teardown that results in the needless start/stop of that instance.
> Fix: Integration tests needlessly start local Elasticsearch instances

- dss/storage/bundles.py
While UUID versions 1, 2, and 3 are now obsolete, we should at least allow for versions 4 and 5. However, BlueBox is not the place to apply such restrictions, PurpleBox is. BlueBox should accept UUIDs of any version.
> Relax bundle UUID pattern to allow any version (fixes #962)

- Makefile
Regression from 16742eae967356645d7b451b011d50d352a51865
> [URGENT] Fix: `test` target should depend on `mypy` and `lint`

- .travis.yml
- Makefile
- README.md
- common.mk
- package-lock.json
- package.json
- tests/scalability/json_faker.py
Only every 16th build succeeds. The exact error message is
```
Error: Cannot create property '_randexp' on string '.{8}-.{4}-.{4}-.{4}-.{12}' in /properties/hca_ingest/properties/document_id
```
This is caused by a recent release of randexp, a transitive dependency, upgrading it from `0.4.6` to `0.4.7`. The fix is to pin that dependency. In order to pin the dependency, we need to switch to using `package-lock.json` in conjuction with `npm install` which is the prescribed way of installing node.js dependencies reproducibly. Another fix would be to bump `json-schema-faker` to `0.4.7` but unfortunately that's not as easy because `json-schema-faker-cli` depends on it with a `^0.3.6` (essentially `0.3.x`) spec. Bumping to `0.4.7` would conflict with that spec, causing `json-schema-faker-cli` …
> [URGENT] Fix: test_json_faker fails stochastically

- Makefile
- README.md
- dss/__init__.py
- tests/test_smoketest.py
5f547b5 is the fix. This is a annoying since it seems that this test was never actually run because that assertion could never have succeeded.
I recommend running smoketest locally after making changes to it or at least watching the Travis IT build like a hawk after your PR lands. I know, it's annoying that we don't run ITs on PRs but it is the best we can do right now.
> Fix smoketest

- tests/test_smoketest.py
Regression from e0d7aafc33e2ae35a2c01b184434ae2ab0a4fbc9.
> Fix: spaces in DSS_NOTIFICATION_SENDER break smoke_test

- dss/stepfunctions/s3copyclient/implementation.py
If it's a non-multipart copy, we want to exit the join operation.  Otherwise, we will attempt to join a non-existent multipart copy.
Ran tests/test_s3parallelcopy.py and checked that the sfns completed without errors.
> Fix s3-copy-sfn

- tests/test_file.py
Because S3 only guarantees eventual consistency, some clients may have seen the file land while others may still not see the file has landed.  Therefore, we cannot guarantee that the second request will be synchronous.
Fixes #992
> Fix sporadic failures in tests/test_file.py

- dss/index/es/__init__.py
- dss/logging.py
- tests/es/__init__.py
- tests/infra/elasticsearch_test_case.py
I still suspect some test hangs are caused by the code that spawns an Elasticsearch instance on demand during test setup. There was this outer loop that would essentially retry starting a new instance forever if it couldn't connect to recently started one. There were no log statements made during that loop so it would have been hard to detect in the build output. I took it out. The new approach will raise an exception if the situation occurs that the outer loop tried to mitigate. I think we would want to see this happen in the wild before we attempt to fix it.
The way the free ports are determined is still potentially racy. For example, there are two invocations of that function, one right after the other. There is no guarantee that the second one won't return the same port as the first …
> ES test server improvements

- .travis.yml
- Makefile
This squeezes build time back to the 9 or so minutes again. I've seen 6 minutes, too. I also think the Travis config is more readable now as it untangles the various conditionals from the actual scripts.
~~I've also snuck in a change the ES server class. See the specific commit for my reasoning.~~
> Parallelize slow tests again, using Travis' new Build Stages feature

- dss-api
- requirements-dev.txt
- requirements-dev.txt.in
- tests/infra/server.py
This is required to pull in a fix in domovoi that should avoid triggering a Lambda CreateAlias API call error limit when creating aliases for step function states. We see this error sporadically causing failed deployments.
> Bump domovoi dependency version

- tests/json_gen/generator.py
- tests/test_hcagenerator.py
- tests/test_jsongenerator.py
Fixes #1003.
Preventing Faker from generating types that are not valid json types.
@hannes-ucsc please review.
> Only Supported JSON types are generated by jsongenerator

- .coveragerc
- Makefile
- dss/api/search.py
acc2353 eliminates lines in the build output like https://travis-ci.org/HumanCellAtlas/data-store/builds/344089603#L786 which I find misleading as it looks like "standalone" test mode is being activated, which is not always the case.
6399d59 is a follow-up from #984.
> [easy] Two small fixes; one a follow-up from #984

- daemons/dss-checkout-sfn/.chalice/config.json
- daemons/dss-checkout-sfn/app.py
- dss/config.py
- dss/storage/checkout.py
- dss/util/email.py
- environment
- iam/policy-templates/dss-checkout-sfn-lambda.json
- requirements-dev.txt
- requirements.txt
- tests/test_checkout.py
- tests/test_email.py
Google Cloud for the checkout service. Implementation relies on dss-gs-copy-sfn* step function for file copy and cloud_blobstore as an abstraction layer for the storage access
manual testing:
1. initiate checkout
2. readiness check 
3. get location prefix from email
4. use CLI to confirm validity of the prefix
Extend existing integration tests to GCP implementation
> GCP support in checkout service

- scripts/deploy_scale_dashboard.py
Use correct SFN metrics on the failure tracking charts.
Turned on stacking
*Testing*
Ran ./scripts/deploy_scale_dashboard.py
Confirmed dashboard is displaying correct data
> Updated scale test dashboard

- dss/index/es/document.py
- dss/index/es/schemainfo.py
- dss/index/es/validator.py
- tests/infra/assert_mixin.py
- tests/test_hcagenerator.py
- tests/test_indexer.py
- adding test cases for `shape_descriptor` and `scrub_index_data`
v5 of the meta data uses `describedBy` to specify versions and type. Extra fields will be removed from v5 metadata bundle  and v5 bundle will be index by major version using `describedBy`. The `core` field in previous version of the metadate will continue to be supported.
> V5 meta support

- dss/index/es/document.py
- tests/test_indexer.py
This is a lightly tested PR to allow integration day efforts (6-March, 2018) to move forward with the most reason meta data bundle example, which involves files of mixed schema versions.
This commit may subsequently be reverted upon completion of integration testing. Alternatively, unit tests may be brought up to date with new ES index names.
> Allow multi-version-schema bundles to be indexed

- Makefile
Follow up on https://github.com/HumanCellAtlas/data-store/pull/1055
I don't like how some test targets depend on mypy and lint while others don't. This is the first of two alternative proposals.
It ensures that mypy and lint are run once before any test is run.
> Simplify how test, lint and mypy targets interact [alternative A]

- Makefile
- daemons/Makefile
- daemons/build_deploy_config.sh
- daemons/dss-scalability-test/domovoilib/json_generator/__init__.py
- daemons/package_daemon.sh
- dss/util/json_gen/generator.py
- dss/util/json_gen/hca_generator.py
- tests/test_hcagenerator.py
- tests/test_jsongenerator.py
- Move `tests/json_gen` to `dss/util`
- Factor out the daemon pre-packaging staging steps into a shell script
- Introduce a new test built into a make target, `import-test`, that runs the pre-packaging staging steps and then parses the daemon entry point, to make sure code reachable at import time from daemon entry points is runnable
Fixes #1072
Reverts https://github.com/HumanCellAtlas/data-store/commit/ae6e74194f31dc5365167c1b441fb175163c010f
Tested manually.
> Move json_gen to a shared location; run import test on all daemons

- dss-api.yml
- dss/api/files.py
- tests/test_file.py
Probabilistically return "Retry-after" header. The retry-after interval can be relatively short now, but it sets up downstream libraries / users for success when we start integrating this with the checkout service.
> Probabilistically return Retry-after header in GET /files/<uuid> request

- dss/logging.py
Ran smoke test before change and verified logs from dss-sync where not present.
Ran smoke test  after change and verified logs from dss-sync lambda function were present.
```[INFO]	2018-04-03T23:16:56.428Z	1a2a61b5-3795-11e8-b3f5-073ab1df4c00	Copying blobs/190a817c2f89732021d118945cb2f1629bb778957601cca9858da04d4b397609.778911c46874cd319dd1ceb75a27727a546d24d6.16a405357a4b5ff8d85a261294d51e00-2.68ba65c9:{'id': 1, 'start': 0, 'end': 67108864, 'total_parts': 1} from s3://dss-tsmith1 to gs://dss-tsmith1```
> fixed logging from lambdas by add logger name 'app'

- chalice/app.py
- daemons/dss-admin/app.py
- daemons/dss-checkout-sfn/app.py
- daemons/dss-index/app.py
- daemons/dss-s3-copy-sfn/app.py
- daemons/dss-s3-copy-write-metadata-sfn/app.py
- daemons/dss-sync/app.py
- daemons/dss-visitation/app.py
- daemons/scheduled-ci-build/app.py
- dss/logging.py
Lambdas deployed with chalice are not currently configured to emit logs. This PR makes the daemon log configuration general to all lambdas and adds the logging configuration to chalice lambdas.
> Configure chalice apps with lambda logging config

- chalice/app.py
- dss/__init__.py
- dss/logging.py
Some tests start an instance of the API web app. At that time, test logging is already configured and the web app is expected to complain about logging already being configured. We shouldn't log a scary backtrace in that case: https://travis-ci.org/HumanCellAtlas/data-store/jobs/362872052#L713
@mweiden Import style of configure_lambda_logging should be consistent. Feel free to change the style, but please do so consistently across all modules.
> Fix: chalice app logs a scary message during tests

- dss/stepfunctions/__init__.py
- dss/stepfunctions/visitation/__init__.py
With the stepfunction DLQ changes, `_step_functions_start_execution` expects a json string for the
`execution_input` parameter.
> Reaper circumvention requires json string.

- daemons/dss-checkout-sfn/app.py
- dss-api.yml
- dss/api/bundles/checkout.py
- tests/test_checkout.py
Make email address an optional parameter for checkout service API
> Checkout: make email optional

- dss-api.yml
At least one bundle on staging contains files with `bundle_uuid` fields that do not match the bundle's uuid (brought to our attention by @aaclan-ebi). Bundle: `018a513f-75a2-422f-b1f5-5836df59d054`
* This PR prepares a new `conflict` error in the `dss-api.yml`: `incorrect_file_bundle_uuid`
* Soon to be follows by a PR that verifies file `bundle_uuid`'s match their bundle.
Addresses https://github.com/HumanCellAtlas/data-store/blob/7007beac418dec45d6f097dabdf131b96d094cf4/dss/api/bundles/__init__.py#L101
> [1/2] New PUT /bundle error incorrect_file_bundle_uuid

- daemons/dss-index/app.py
- dss/index/backend.py
- dss/index/bundle.py
- dss/index/es/__init__.py
- dss/index/es/backend.py
- dss/stepfunctions/visitation/reindex.py
- dss/util/types.py
- tests/infra/__init__.py
- tests/test_indexer.py
- tests/test_visitation.py
- Added lambda context to indexer.
- Retry finding files in manifest if not found until lambda times out.
- If file cannot be found an exception is raised.
- fixes #1115 
updated test cases for indexer.
redeploy indexing lambdas
> Retry get file blob if not found else raise error (fixes #1115)

- dss/api/bundles/__init__.py
- tests/test_bundle.py
depends on: #1147 
Require file `bundle_uuid`'s match their bundle in `PUT /bundle`
Addresses:
https://github.com/HumanCellAtlas/data-store/blob/7007beac418dec45d6f097dabdf131b96d094cf4/dss/api/bundles/__init__.py#L101
> [2/2] New PUT /bundle error incorrect_file_bundle_uuid

- dss/stepfunctions/visitation/__init__.py
When a state dict value is assigned from the default value from the state spec, and if that value is of a reference type, the default value needs to copied. Otherwise the state will refer to the value from the state spec and updates to it will inadvertently modify the spec which should be strictly read-only.
This shouldn't occur in the wild but it does occur during tests where it causes one test failure to cascade into another failure of a test that would otherwise succeed. It's actually a coincidence that this doesn't occur all the time. For example, if `test_reindex_timeout` fails and leaves the `state['work_result']` dict with anything but zero for its values, `test_reindex_walk`, the next test in alphabetic order—the order unittest runs tests in—will fail when asserting the …
> [easy] Fix: Visitation instances inadvertently alter the state spec

- chalice/app.py
Currently the health check app pings the `/v1/swagger.json` endpoint. We should have a basic health check endpoint instead that we can build L2 and L3 health check functionality on top of. This PR introduces that endpoint.
> Add an L1 health check endpoint

- tests/es/__init__.py
- tests/test_indexer.py
The integration tests in test_indexer don't benefit from being run for each replica. I'm also worried that if those tests run in parallel, they might conflict with each other as in this case:
https://travis-ci.org/HumanCellAtlas/data-store/jobs/370849706#L1256
> Run indexer integration tests for AWS replica only

- scripts/dss-start-stop--think-before-you-invoke-me.py
#connects to #1101 
Lambda executions may be throttled by setting the concurrency limit to 0.
See the relevant AWS documentation here:
https://docs.aws.amazon.com/lambda/latest/dg/concurrent-executions.html
> The Big Red Button: Script for an emergency halt of the DSS

- requirements-dev.txt.in
Changes to requirements.txt.in should affect how we build requirements-dev.txt.  That is only possible if requirements-dev.txt.in sources requirements.txt.in.
> requirements-dev.txt.in should source requirements.txt.in

- requirements-dev.txt
Because of the bug fixed by #1193, we didn't update the dependency correctly.
> Fix cloud-blobstore dep

- chalice/app.py
- iam/policy-templates/ci-cd.json
- iam/policy-templates/dss-lambda.json
This PR adds logging and metrics for requests and their response codes in the DSS HTTP API.
I've used CloudWatch Metrics, but may change this in the future if we decide on a different metrics system.
The call to the metrics server is done on its own thread to prevent the API from lagging if CloudWatch metrics is slow in responding.
HTTP metric data is grouped into two CloudWatch metrics, `HttpRequests by StatusClass` and `HttpRequests by Path, Method, StatusClass`. `HttpRequests by StatusClass` is for dashboarding and will allow coarse-grained indication of errors on the API. `HttpRequests by Path, Method, StatusClass` will allow us to drill down to the problematic endpoint and method when an issue is spotted in logs or on coarser metric plots. The HTTP return codes are grouped in the …
> Add response metrics and logging

- chalice/app.py
- iam/policy-templates/ci-cd.json
- iam/policy-templates/dss-lambda.json
The threading model in the asynchronous metrics push was concern enough that we decided to pull this change out and generate the metrics asynchronously.
This PR backs out the metrics push. The generation of the metrics will be done with logs or processed in a separate PR.
> Remove asynchronous API metrics push

- daemons/dss-index/app.py
- dss/config.py
- dss/index/backend.py
- dss/index/bundle.py
- dss/index/es/__init__.py
- dss/index/es/backend.py
- dss/index/indexer.py
- dss/stepfunctions/visitation/__init__.py
- dss/stepfunctions/visitation/reindex.py
- tests/infra/__init__.py
- tests/test_indexer.py
- tests/test_visitation.py
So far we've been neglecting to accurately track the Lambda invocation's remaining run time in the indexer. No one noticed until we started retrying to load metadata blobs in #1137 as a fix for #1115. The retries could potentially take so much time that there wouldn't be anything left for the actual indexing operation, like interacting with ES. We should make reasonably sure that there is sufficient time to complete an indexing operation before we commence it, because if we are interrupted, we'll leave the index inconsistent. This PR fixes that on a best effort basis. I've opened #1164 to retry the entire invocation if that best effort fails.
> Consolidate indexer run time tracking in Indexer class (mostly)

- dss/api/bundles/__init__.py
- dss/config.py
- tests/test_config.py
Connects to #1098 
Gateway timeouts (504 errors) have been probabilistically observed during PUT /bundle.
PUT /bundle should either succeed, or fail with an appropriate error, before the gateway times out. This PR attempts to mitigate against occasionally high latency storage by using a more aggressive timeout strategy.
> Fighting the duplicate bundle threat with timeouts

- dss-api.yml
- dss/api/bundles/__init__.py
- dss/api/files.py
- dss/storage/hcablobstore/__init__.py
- tests/infra/storage_mixin.py
- tests/test_api.py
- tests/test_bundle.py
- tests/test_file.py
Remove backlink from file to bundle (fixes #1172)
This makes it possible for a file to belong to more than one bundle. It has implications on the physical deletion of files. We cannot remove a file without enumerating all bundles, loading their metadata and then checking if any other bundles reference that file. However this is no different to the physical deletion of blobs: since one blob can belong to many files, the same enumeration is required there. Ultimately, physical deletion due to lack of consent will always require the deletion of the actual data, i.e. the blob. These changes do not significantly complicate the search for files and bundles that refer to it, or, IOW, the presence of a backlink from file to bundle does not siginifcantly simplify the problem.
> Remove backlink from file to bundle

- dss/config.py
- tests/test_gscopyclient.py
Fix for integration test failures.
During test setup, TestGSCopy uploads a blob to GCP "nearline" storage, which is a semi-cold storage service. Since nearline storage uploads do not appear to be particularly snappy, use longer connect/read timeouts during upload.
> Lengthen nearline storage timeouts in TestGSCopy

- daemons/dss-notify/app.py
- requirements-dev.txt
- requirements-dev.txt.in
- requirements.txt
- requirements.txt.in
(fixes #1211)
Since I had to touch the requirements files, I also fixed three regressions there
- aegea was added to the `.in` but the `.txt` was never updated
- the explicit `.in` entry for `botocore` was missing (we know we need 1.10 and the first commit proves that the downgrade to 1.9 does indeed happen without this entry, as I suspected)
- the lower bound on `click` was missing (we agreed to provide lower bounds in the `.in`)
I clobbered @ttung's manual one-time exclusion of `clickclick`. It may be unnecessary but we can't expect all devs to forever redo the exclusion. We need a way to declaratively exclude it or just accept its presence.
>  Use stage-specific CW rule names for notifier

- .gitignore
- Makefile
- environment
- infra/Makefile
- infra/buckets/gs_buckets.tf
- infra/buckets/s3_buckets.tf
- infra/build_deploy_config.py
* Terraform objects defined in `infra/{component}`
* Only one component right now: `buckets`
* Terraform configuration carried out in `infra/build_deploy_config.py`
Testing (with custom bucket names!) may be carried out with:
`make deploy-infra`
`make -C infra apply COMPONENT=buckets`
`make -C infra destroy COMPONENT=buckets`
> Deploy buckets with terraform

- chalice/app.py
- dss/config.py
- tests/test_config.py
- tests/test_gscopyclient.py
* Use default client timeouts for daemons, which are unconstrained by API Gateway.
* Revert timeout changes to `tests/test_gscopyclient.py`
> Connect/read blobstore timeouts enabled only for API server

- environment
- infra/build_deploy_config.py
- infra/elasticsearch/elasticsearch.tf
> Deploy elasticsearch with terraform

- daemons/dss-admin/app.py
- dss/logging.py
- dss/stepfunctions/__init__.py
- dss/stepfunctions/visitation/__init__.py
- dss/stepfunctions/visitation/implementation.py
- dss/stepfunctions/visitation/registered_visitations.py
- dss/stepfunctions/visitation/reindex.py
- dss/stepfunctions/visitation/storage.py
- dss/util/iterators.py
- scripts/admin-cli.py
- tests/test_doctests.py
- tests/test_visitation.py
Please ignore the coverage check. The added code is only covered by integration tests.
This uses my original approach that relies on the listings to be strictly sorted. @xbrianh proposed an alternative solution for two replicas that relaxed that requirement to the extent of being able to efficiently handle mostly sorted listings and degraded to using large amounts of state for unsorted listings, but not failing in that case. Then he, @Bento007 and I generalized his proposal to comparing more than two replicas in parallel, a feature that my original approach already offered. So why did I not go with the alternative approach?
For one, I asked on SO and a Google engineer pointed me at the place where Google documents that their bucket listing is sorted—at a somewhat obscure location—but its …
> Add simple storage replication check (fixes #667) 

- daemons/dss-index/app.py
- daemons/dss-notify/app.py
- dss/index/backend.py
- dss/index/indexer.py
- dss/notify/notifier.py
- dss/stepfunctions/visitation/__init__.py
- dss/stepfunctions/visitation/implementation.py
- dss/stepfunctions/visitation/index.py
- dss/util/time.py
- tests/test_indexer.py
- tests/test_notifier.py
- tests/test_visitation.py
Another outcome from the F2F at Boston and the collaboration with @rexwangcc there. 
Backend timeouts are currently not handled very well and could cause duplicate notifications. For the remainder of this text, note that we run the actual indexer backend as a task in a thread pool executor.
E = estimated time for writing one document (tombstone or bundle document)
R = remaining time in lambda execution
Currently the main thread times out after waiting E seconds for the backend thread and exits with an exception. The exception will eventually cause the lambda execution to fail and then to be retried. While the main thread is shutting down, the backend thread continues to run in its own pool thread. The pool isn't shut down (by choice, so it doesn't block) and the backend thread keeps …
> Fix duplicate notifications

- README.md
- chalice/app.py
- daemons/dss-admin/app.py
- daemons/dss-checkout-sfn/app.py
- daemons/dss-dlq-reaper/app.py
- daemons/dss-gs-copy-write-metadata-sfn/app.py
- daemons/dss-index/app.py
- daemons/dss-notify/app.py
- daemons/dss-s3-copy-sfn/app.py
- daemons/dss-s3-copy-write-metadata-sfn/app.py
- daemons/dss-sfn-launcher/app.py
- daemons/dss-sync/app.py
- daemons/dss-visitation/app.py
- dss/api/files.py
- dss/util/tracing.py
As a DSS operator
I want to profile uninstrumented (unpatched) DSS application logic (code not in `boto3` or `requests`)
so that I know what parts of an endpoint's logic are slow.
Add xray tracing subsegments to the GET /files logic.
Adding xray tracing subsegments to the GET /files logic will allow us to profile unpatched code.
Must be deployed from a privileged account in order to update AWS Permissions for lambdas
> Add X-Ray profiling for daemons and subsegments for GET /v1/files

- tests/test_visitation.py
> [EASY] Error string will properly display status from failed visitation test.

- environment
Before this PR:
- Put `DSS_DEBUG=1` in `environment.local`
- `cd chalice && make deploy`
- Observe that `chalice/.chalice/config.json` does't have `DSS_DEBUG`
After this PR, `chalice/.chalice/config.json` has `DSS_DEBUG`.
> Fix DSS_DEBUG not being propagated to lambdas

- scripts/set_apigateway_base_path_mapping.py
A script for idempotently mapping the AWS Apigateway custom domain name to the Apigateway stage. It should be executed for a first-time deployment after successfully running `make deploy-infra` and `make deploy`.
#connect to #856
> Script for setting up Apigateway base path maping

- chalice/build_deploy_config.sh
Before this PR: `source environment && cd chalice && ./build_deploy_config.sh` gives:
```
./build_deploy_config.sh: line 63: 0: command not found
```
After this PR, it succeeds.
Not sure how things are working on Travis. (Also, I'm pretty sure build_deploy_config.sh was working for me earlier, not sure what changed.)
> Fix admin_user_emails_length if statement

- infra/Makefile
Subdirectories of /infa are considered components by /infa/Makefile only when they contain terraform files (files ending with .tf).
> [Easy] Component dirs must contain terraform files

- daemons/Makefile
Remove reference to `$(DSS_HOME)/scripts/deploy_checkout_lifecycle.py` from daemons Makefile. This is causing deploy to fail.
> Remove dangling reference to old lifecycle script

- infra/buckets/gs_buckets.tf
- infra/buckets/locals.tf
- infra/buckets/s3_buckets.tf
* All stages share test buckets
* Test buckets are only deployed from `dev`
* Add Terraform logic to accommodate GS buckets with different storage region settings.
> Deploy test buckets only from the dev stage

- iam/policy-templates/dss-s3-copy-sfn-lambda.json
This is required to do a test checkout.
> Allow the s3 copy sfn to write to the test checkout bucket.

- dss/stepfunctions/s3copyclient/implementation.py
When we do a single part copy, we don't mark the ["finished"] = True.  This is confusing for someone inspecting the SFN output.
> Change confusing output state for single part copy.

- dss/stepfunctions/checkout/checkout_states.py
- dss/storage/checkout.py
- tests/test_checkout.py
Right now, the SFN always uses the bucket configured at deploy time (for DEV, it's DEV).  However, if we want checkout service tests to be able to check out from the TEST bucket, we need to use the bucket specified in the SFN message.
Depends on #1313 
Depends on #1330 permission change being deployed.
> Use the bucket specified in the SFN message

- dss/api/bundles/checkout.py
It shouldn't be hardcoded to s3.  Instead, it should be replica-specific.
Depends on #1313
> Fix how we determine the dss bucket

- dss/api/bundles/checkout.py
- dss/stepfunctions/checkout/checkout_states.py
- dss/storage/checkout.py
- tests/test_checkout.py
Rename the methods to accomodate checking of file checkout status.  No logic should have changed in this PR.
Depends on #1313
> Group all the checkout status methods together.

- dss/storage/checkout.py
This allows us to have two namespaces -- checked out files and checked out bundles.
> [easy] Rename the checkouts path to "bundles"

- chalice/.chalice/config.json
Increasing the memory for the DSS-API lambda will prevent timeouts when burst loads are encountered by the DSS-API. This fixes #1300. If larger burst loads are expected we may need to further increase the memory allocation in the future. Further optimization of the lambda maybe need in the future.
> Increasing memory from 128MB to 512MB to on DSS-API Lambda

- dss/api/collections.py
- dss/api/files.py
- dss/index/bundle.py
- dss/storage/bundles.py
- dss/storage/checkout.py
- dss/storage/hcablobstore/__init__.py
- dss/util/__init__.py
- tests/test_indexer.py
Unify all the places where we compose the blob key.
Self-explanatory, no?
The only problem is that we apparently have a disagreement about s3-etag (what's written to cloud storage) and s3_etag (what's sent to users).  I recall going through and changing them but apparently I missed one place...?
> Unify all the places where we compose the blob key.

- dss/api/files.py
- dss/storage/hcablobstore/__init__.py
- dss/storage/hcablobstore/gs.py
- dss/storage/hcablobstore/s3.py
- tests/hcablobstore_base.py
This function is really verifying that the cloud checksum matches the metadata set by the staging.
> [easy] rename verify_blob_checksum to verify_blob_checksum_from_staging_metadata

- dss/storage/hcablobstore/__init__.py
- dss/storage/hcablobstore/gs.py
- dss/storage/hcablobstore/s3.py
- tests/hcablobstore_base.py
This is useful for verifying that checkouts are completed correctly.
Depends on #1339
> Function for verifying that the cloud-provided checksum matches metadata written to dss storage

- dss/api/files.py
- dss/stepfunctions/gscopyclient/implementation.py
- dss/stepfunctions/s3copyclient/implementation.py
- dss/storage/files.py
This is required to break circular dependencies.
> [easy] move file metadata write method.

- scripts/dss-chalice
Chalice does not currently compile all `py` files to `pyc` files before deploying lambdas. For this reason, lambda cold start will be slower. This PR introduces compilation as part of the package and deployment of chalice apps.
> Precompile all .py files to .pyc before deploying

- dss/api/bundles/__init__.py
- dss/api/bundles/checkout.py
- dss/storage/bundles.py
- dss/storage/checkout.py
- dss/storage/hcablobstore/__init__.py
- tests/test_bundle.py
- tests/test_checkout.py
storage/bundles transacts in what is stored on cloud storage.  The logic that translates what is stored in cloud storage into what the API endpoint is expecting is moved to dss.api.bundles.
This allows us to get rid of the awkward hack for compose_blob_key(..), as well as some unnecessary ['bundle'] indirection.
> Introduce get_bundle_manifest(..)

- tests/test_smoketest.py
This seems to make the smoketest not run, as it's not a valid param of the hca tool.
> get rid of --method PUT in smoketest

- tests/test_smoketest.py
This parameter does exist, just that my ~/.config/hca was outdated (smoketest should really just pull the config anew...)
> Backed out #1351

- tests/infra/assert_mixin.py
- tests/test_file.py
Since both files and bundles may need retries, move that logic into assert_mixin so we can reuse it.
> Move retry logic into assert_mixin

- dss-api.yml
#1196 introduced the service_unavailable error code, but did not add it to the swagger spec.  This triggered a validation error https://travis-ci.com/HumanCellAtlas/data-store/jobs/130688193
> Add 503 to GET /bundles/<uuid>

- tests/__init__.py
`tests/__init__.py` modfifies `environ['ADMIN_USER_EMAILS']`, which `dss/api/bundles/__init__.py` uses to populate the list of email domains authorized to delete.
Unfortunately, if `dss/api/bundles/__init__.py` is imported before `tests/__init__.py`, then the modification in `tests/__init__.py` does not affect any of the code.  This change ensures that the modification propagates.
> Fix race condition between tests/__init__.py and dss/api/bundles/__init.py__

- tests/test_smoketest.py
Getting the status of a checkout now requires the replica parameter.
> Fix smoketest.

- tests/infra/assert_mixin.py
- tests/test_file.py
1. Improve documentation.
2. Allow callers to override the retry time, otherwise the retry time is taken from the Retry-After header.
> Improve documentation and behavior of retries in assert_mixin

- dss/stepfunctions/checkout/checkout_states.py
- dss/stepfunctions/checkout/constants.py
- dss/storage/checkout.py
- tests/test_checkout.py
The only thing I didn't change is the _value_ of EventConstants.EXECUTION_ID.  The rationale was to preserve existing sfn runs, but maybe we don't care and we can blow away backwards compatibility. :)
Test plan: `DSS_TEST_MODE="standalone integration" make -j tests/test_checkout.py`
Addresses comment https://github.com/HumanCellAtlas/data-store/pull/1373#pullrequestreview-132235939
> Rename most things to execution_id

- tests/test_bundle.py
allows tests to pass/fail independently.
> [EASY] Using subtest in test_bundle_delete

- dss-api.yml
- dss/api/search.py
- dss/index/es/mapping.json
- tests/test_search.py
Using search after for paged searching. This will reduce the overhead required to search beyond 10,000 results at the cost of search results being dynamically generated.
Relates to #835
Removed test cases relating to scroll_id
> Replaced scroll with search after

- dss/index/es/__init__.py
This sets the timeout for all elasticsearch instances despite the host. This will help prevent timeout errors in elastic search unit tests.
Fixes #1370
> Setting ES timeout for all hosts

- dss/storage/checkout.py
This avoids the problem where the delete throws an exception, causes a spurious permission test failure.
Connects to #1398
> Move cleanup of the permissions test to a finally clause.

- dss-api.yml
- dss/api/bundles/__init__.py
- dss/api/files.py
- tests/infra/storage_mixin.py
- tests/test_bundle.py
- tests/test_checkout.py
- tests/test_file.py
- Updated test cases to always include version
- Added test cases to test when no version is present
- the HCA-CLI will need to be updated to handles these changes.
- updated the swagger paths for bundles/put to require version
- updated the swagger paths for files/put to require version
> Version mandatory for PUT Files and Bundles

- infra/build_deploy_config.py
- infra/domain/domain.tf
Some certificates must live in us-east-1 regardless of deployment region:
https://docs.aws.amazon.com/acm/latest/userguide/acm-regions.html
> Reintroduce aws us-east-1 provider for non-us-east-1 deployments

- infra/Makefile
infra Makefile should exit with non-zero status if an error occurs in a loop.
> infra/Makefile exits loops with non-zero status

- dss/stepfunctions/checkout/checkout_states.py
- dss/storage/checkout/__init__.py
- dss/storage/checkout/error.py
- tests/test_checkout.py
This allows us to bubble up the root cause of errors.
Test plan: deployed and `DSS_TEST_MODE="standalone integration" make -j tests/test_checkout.py tests/test_file.py tests/test_bundle.py`
Depends on #1409
> Use exceptions to signal failures in pre-exec checks

- environment
- infra/buckets/s3_buckets.tf
- tests/test_checkout.py
DestinationBucketNotWritableError is not practical to test with GCP because creating a bucket that we don't own is the only way to prevent write access, and that's not possible within the same account.
Depends on #1415
> Test DestinationBucketNotFoundError and DestinationBucketNotWritableError

- dss-api.yml
Fixes https://github.com/HumanCellAtlas/data-store/issues/1263 (partially)
Verified in the UI and by the standard unit tests.
> Add missing 301 response to GET /v1/bundles/{uuid} swagger

- infra/build_deploy_config.py
env vars to TF need to be included in `infra/build_deploy_config.py`
> [Easy] Include missing infra env var

- daemons/dss-admin/app.py
Changing admin reindex to never send notification during a repair operations.
connects to #1386
> Admin repair will never send notifications

- dss/stepfunctions/visitation/__init__.py
- dss/stepfunctions/visitation/integration_test.py
Make the execution name available in the `Visitation` sfn state, which is useful as a correlation id.
> Include SFN execution name in visitation state

- infra/gcp_service_account/main.tf
`roles/cloudfunctions.developer` is needed to successfully execute `scripts/deploy_gcf.py` during deployment of `daemons/dss-gs-event-relay`.
> Add roles/cloudfunctions.developer to gcp service account

- .gitlab-ci.yml
- .travis.yml
- Dockerfile.allspark
* Run tests on GitLab, and deploy to `dev` if they pass.
* Create a custom Docker container to resolve Elasticsearch needing to run as a non-root user, and other permission issues.
* Turn off travis `dev` deployment
> Deploy dev on the  Build Box

- chalice/app.py
- chalice/build_deploy_config.sh
- tests/test_api.py
Connected to https://github.com/HumanCellAtlas/dcp-cli/issues/113 (cross repo)
The new `/version` endpoint on the DSS API will serve the version of the DSS generated by `git describe --tags --apply` at the time of deployment. This change is part of a larger solution to expose service version(s) describing each DCP service, and ultimately, to consolidate these endpoints in the DCP CLI as a single command that lists the versions of all DCP services.
The version value for DSS is set via environment variable and is injected into the Lambda environment. The return value of the endpoint is a named dictionary, `version_info`, and contains relevant <service/component, version> pair(s) in order to support multiple subcomponents/versions (see [Green Box's /version …
> Add /version endpoint to DSS API

- tests/test_bundle.py
Fixes #1406 
Adding test cases when invalid version and uuid are supplied to bundle.
> Adding test cases when invalid version and uuid are supplied to bundle

- environment.integration
- environment.prod
- environment.staging
* Stages should ideally have completely separated environments.
* Churn on GCP service account permissions should not crash other environments.
* Service accounts will be created when this PR is approved (`dev` and `prod` already exists).
> [Easy] Separate GCP service accounts by stage

- dss/index/backend.py
- tests/infra/storage_mixin.py
- tests/test_indexer.py
- modified indexer test cases to handle notification on modification.
- added test case to indexer when duplicate indexer events are sent.
- None
-  Notification only sent on bundle modification
- connects to #1386
>  Notification only sent on bundle modification

- dss/stepfunctions/visitation/implementation.py
- Adding `Lambda.SdkClientException` and `State.TaskFailed` to visitation retry conditions
- Fixes #1401
- Fixes #1391
We will need to run this against integration for a few days to ensure this fix works
@xbrianh any ideas how to unittest?
- none
- Visitation workers will retry if the lambda fails to be invoked this includes reindexing and verify.
> Adding additional retry errors to visitation

- dss/storage/checkout/__init__.py
Fixes #1440 
Run test over several days to see if any GCP request rate limits errors are triggered.
None
A touch_*.txt file will be created for every checkout process. These files will eventually be deleted based on the buckets data lifecycle rules. We should also suggest that creators of checkout buckets set a shorter data lifecycle rule for files starting with `touch_`.
> adding uuid to touch.txt to prevent GCP rate limit errors

- environment.integration
- infra/buckets/gs_buckets.tf
- infra/buckets/s3_buckets.tf
- infra/domain/main.tf
- infra/elasticsearch/elasticsearch.tf
* Accommodate, and bring up-to-date, infrastructure for `integration`.
* With this PR, `make deploy-infra` passes without changes on `dev` and `integration`.
> Update infra to reflect current state

- .gitlab-ci.yml
This prevents the virtualenv from being annihilated by git clean.
> [Easy] Move gitlab-ci.yml virtualenv out of project root

- .gitlab-ci.yml
Grab the GCP credentials in gitlab-ci.yml after git clean
> [Easy] Grab credentials before release it gitlab-ci.yml

- daemons/dss-admin/app.py
By default admin repair will **not** send notification when new objects are discovered during the repair process. This can be changes by overriding the default values for repair.
> Admin repair's default is to not send notifications

- dss/api/files.py
- requirements-dev.txt
- requirements.txt
- requirements.txt.in
- tests/fixtures/cloud_uploader.py
- tests/test_file.py
1. Bumped to cloud-blobstore 2.1.5 to pick up https://github.com/chanzuckerberg/cloud-blobstore/commit/749d4ef7d9c7cff1d9de662a5fe5919d446a2ef5.
2. Changed the multipart threshold to 64MB+1 for the test uploader class.  This ensures that we don't switch to multipart uploads for 64MB objects.
3. Refactored the tests so that synchronous requests (i.e., <= 64MB) tests can run standalone.
4. Clarified expectations for the three classes of requests: aws multipart, gs multipart, and synchronous requests.
Test plan: Ran `DSS_TEST_MODE="standalone integration" make tests/test_file.py`
> Fixed multipart upload

- dss/api/files.py
- dss/stepfunctions/s3copyclient/implementation.py
- dss/util/aws/__init__.py
- requirements-dev.txt
- requirements-dev.txt.in
- requirements.txt
- requirements.txt.in
- tests/fixtures/cloud_uploader.py
- tests/test_s3parallelcopy.py
- tests/test_utils.py
https://github.com/HumanCellAtlas/dcplib/commit/d446e4d79a93f1e4ccc17d9d002c13717a495c04 replicates the constants defined in dss/util/aws/__init__.py, and should be used throughout the HCA DCP.
> Switch to the constants defined in dcplib

- requirements-dev.txt
- requirements.txt
https://nvd.nist.gov/vuln/detail/CVE-2018-10903
> bump cryptography lib to 2.3

- dss-api.yml
Follow up from https://github.com/HumanCellAtlas/data-store/pull/1461
The swagger doc currently uses [literal block style](http://yaml.org/spec/1.2/spec.html#id2795688). This causes text in the swagger doc to not format properly. See example below
This makes the documentation harder to read for users.
To fix this, this PR switches the swagger docs to [folded block style](http://yaml.org/spec/1.2/spec.html#id2796251) as suggested by @hannes-ucsc. See an example of the result below.
> Use folded block YAML style for docs in swagger

- Makefile
This allows us to run make -j requirements.txt requirement-dev.txt.  Parallel > serial.
> Use different staging folders for building requirements.

- dss-api.yml
- dss/api/bundles/__init__.py
- tests/test_bundle.py
They belong on each of their own groups.
Also changed missing file in a bundle to a 400 not a 409.
> Move errcodes out of the catch-all default error handler.

- dss-api.yml
- dss/api/bundles/__init__.py
- dss/api/files.py
- tests/test_bundle.py
- tests/test_file.py
This should _not_ be a 500.  This is a case we should handle, and return the proper error message.  In general, we should never expect a 500 in a test.
> Change illegal version to a 400.

- scripts/envhook.py
This has proven useful in not having to start PyCharm or any other IDE from a shell with `environment` sourced. Not only is that a nuissance, you're essentially restricted to a single project because you can only source the `environment` from a single project. If you have another project that also uses an `environment`, you're out of luck. It installs itself as a `sitecustomize.py` hook in the currently active virtualenv. Whenever that virtualenv is activated, it will source `environment` and apply the resulting environment changes to `os.environ` such that the interpreter process and all its children see them.
To install, activate the virtualenv and run `python scripts/envhook.py install`. To uninstall, run `python scripts/envhook.py remove`.
> Add envhook.py

- requirements-dev.txt
- requirements.txt
- requirements.txt.in
- tests/fixtures/cloud_uploader.py
- tests/test_collections.py
ChecksummingSink now has a required parameter write_chunk_size, which allows it to calculate correct HCA checksums.
Waiting for travis....
> Upgrade to dcplib 1.3.2

- dss-api.yml
- dss/api/collections.py
- tests/test_collections.py
This is required to unpin dependencies, as validation has changed for empty strings.  This is a generally good change to have though, since we were not previously testing for versions that are not timestamps but not an empty string.
> Explicitly catch a malformed version error for PATCH /collections

- .gitlab-ci.yml
This allows deployment to proceed before the integration tests are performed.
> Deploy before performing integration tests

- .gitlab-ci.yml
This allows pipelines that pass all tests and deploy succesfully to `dev` to be marked as passed even if they fail to release to the `integration` stage.
This:
Will look more like this (note the orange shade):
> [Easy] Don't mark job as failed when not releasing to integration

- dss-api.yml
- dss/api/collections.py
1. Explode all the various errors so they're tied to their own response codes.
2. Add illegal_arguments to the default error.  This is REQUIRED for every endpoint's default error handler, because when swagger validates the parameters and fails, it returns this code.
> Improve error response documentation for PATCH /collections

- .gitlab-ci.yml
For release builds, explicitly clone the repo from GitHub using an access token.
This fixes a bug where release pushes were attempted on the cloned repo in the build box, which failed.
Tested by successfully pushing a test tag to GitHub.
> Checkout from GitHub with token for releases

- tests/fixtures/populate_lib.py
- tests/test_api.py
tests/test_api.py doesn't need  it's own (old) fixture.
> Update fixture for tests/test_api.py

- infra/buckets/gs_buckets.tf
- infra/buckets/s3_buckets.tf
Fix for broken deploy:
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/-/jobs/4991b
Testing:
- ran `make infra-plan` locally
- should we add a test that runs .tf scripts in the travis PR builds?
> Add missing quotes to fix tf scripts

- .gitlab-ci.yml
Since dcp-wide integration has been blocked for a long time, require manual action to integration. This can be turned on again when things stabilize.
> [Easy] Release to integration requires manual action.

- dss/api/files.py
It's not consumed anywhere in the codebase.
> [easy] remove REDIRECT_PROBABILITY_PERCENTS

- dss/storage/checkout/__init__.py
Store touch test files across a range of names to prevent the error, "The total number of changes to the object org-humancellatlas-dss-checkout-test/touch.txt exceeds the rate limit. Please reduce the rate of create, update, and delete requests."
> Prevent object modification rate limit for touch test files.

- scripts/release.sh
When running `scripts/release.sh`, skip deployment  step if `--no-deploy` flag is set.
Connects to #692
> Add `--no-deploy` flag to scripts/release.sh

- .gitlab-ci.yml
Split apart release and deploy.
This should make re-deploying, or rolling back, possible for `integration` and `staging`
#depends on #1537
> Refactor gitlab jobs

- dss/api/bundles/__init__.py
- dss/api/bundles/checkout.py
- dss/storage/checkout/bundle.py
- tests/test_bundle.py
1. `dss/api/bundles/__init__.py`: changes to which bucket we point to after the checkout succeeds.  Note that the keys are different.
2. Make the dst replica explicit.  Right now, the state machine is not aware of overrides done in tests.
3. Small change #1 that I'm sneaking in: `bundle_version` is actually possibly None.
4. Small change #2 that I'm sneaking in: fix styling around default parameter values.
Test plan: `DSS_TEST_MODE="standalone integration" make -j tests/test_checkout.py tests/test_file.py tests/test_bundle.py tests/test_api.py`
> directaccess and presignedurl should go to the checkout bucket

- dss/index/indexer.py
This prevents false positive error messages from polluting the logs
no changes
> Adding Debug log message when a collection is identified by the indexer.

- dss/api/files.py
- dss/stepfunctions/visitation/index.py
- dss/stepfunctions/visitation/integration_test.py
- dss/stepfunctions/visitation/storage.py
- requirements-dev.txt
- requirements.txt
- requirements.txt.in
- tests/test_file.py
- tests/test_visitation.py
These changes enable `get_file` (file GETs) to immediately return the location of the file if it has already been checked out with the conditions:
- the file has not "expired"
- the checksum of the checkout file matches the original (existing logic)
Expiration is defined by `request_time - advertised_ttl` (i.e. earliest acceptable last modified date) such that we ensure the file we serve is preserved in checkout for the time that we advertise to the user.
Tested:
- manual testing via local DSS API server
- added integration test
Will test:
- Hit get_file unchecked-out files, checked-out files that are either stale or valid, and observe expected behaviors
Must be merged after https://github.com/HumanCellAtlas/data-store/pull/1515
Related to #1347
> Optimize get_file to run synchronously when possible

- dss/storage/bundles.py
- dss/storage/checkout/bundle.py
- tests/test_bundle.py
These changes update bundle GETs (`get_bundle`) to only perform a checkout in the following cases:
- if any file in the bundle has become [stale](https://github.com/HumanCellAtlas/data-store/pull/1516)
- if any file in the checkout bundle is not listed in the bundle manifest
- if the number of files in the checkout bundle does not match the number of files in the bundle manifest
- Manual testing on dev DSS
- Added integration test
Upgraded dependency: [`cloud-blobstore` >= 3.0.0](https://github.com/chanzuckerberg/cloud-blobstore/pull/21)
Should be merged after https://github.com/HumanCellAtlas/data-store/pull/1516
Fixes #1347
> Optimize get_bundle to only perform checkout when necessary

- .gitlab-ci.yml
- scripts/release.sh
* Use the scripts/release.sh from source branch, not dest branch
* Don't source environment from scripts/release.sh, which overwrites source env with `dev` env
* Use `--` to make sure git can differentiate flags from branches
* Remove unused gitlab cache
* Remove unused Terraform env var
`.gitlab-ci.yml` has undergone some churn. However, a full test of the release pipeline should now be possible.
> Further .gitlab-ci.yml simplifications and fixes

- chalice/app.py
- tests/test_bundle.py
1. Remove OVERRIDE_EXECUTION_LIMIT_SECONDS, which is not really doing much.
2. mypy fixes for `url`.  url is defined above, and mypy retains the typing of the first instance of a variable.
This is split out of #1552, which was more controversial than expected.
> No-op fixes

- infra/gcp_service_account/main.tf
This is needed to for `terraform plan` to succeed on GCP infra.
> Give GCP service account read access.

- .gitlab-ci.yml
- scripts/release.sh
* Command number checks no needed anymore in `scripts/release.sh`
* Reset working tree before doing anything
* Add `--skip-account-verification` and `--skip-github-status` to `scripts/release.sh`, which is useful for the CI build since the `yes 1 | ...` was causing non-zero exit status for some reason
Testing:
Successfully released to integration
> More GitLab CI release bugfixes

- dss/api/bundles/__init__.py
- dss/api/collections.py
- dss/api/subscriptions.py
- dss/config.py
- dss/util/security.py
- tests/__init__.py
- tests/test_subscriptions.py
- tests/test_utils.py
* Fixes an error that prevent users from making authorized request with user credentials. Does not affect service credentials.
* Moved common logic for retrieving user email to a function in security. 
* Added tests to confirm the behavior of that function. 
added specific test cases for custom email claims.
None
> Custom email claim fix and tests

- dss/events/handlers/sync.py
- tests/test_sync.py
- Sync daemon needs to use the "normal" bucket since that is what events are configured on.
- For now, let's have the sync daemon copy tombstones without checking for their dependencies. It's not clear if there are situations where we need to hold back dependent tombstone copying for referential integrity.
> Fix sync daemon tests and logic error when copying tombstones

- daemons/dss-gs-event-relay/main.py
- daemons/dss-index/app.py
- daemons/dss-sync-sfn/app.py
- scripts/deploy_gcf.py
My initial design had the same issue with GS events as it did with S3 events: SQS can't be used to send events to multiple destinations at once.
Fixup for 1cf7717
> Multiplex GS events between indexer and sync daemons using SNS-SQS

- dss/api/files.py
- requirements-dev.txt
- requirements.txt
- requirements.txt.in
- tests/test_file.py
These changes follow https://github.com/HumanCellAtlas/data-store/pull/1516 and further optimize `get_file` to initiate a checkout and return `302 Found` (instead of previously initiating a checkout and returning a `301 Redirect`) if the file is requested past its soft expiration date (`DSS_BLOB_PUBLIC_TTL_DAYS`), but 1 hour before its real expiration date (`DSS_BLOB_TTL_DAYS`). The second condition is to prevent returning a `302 Found` immediately before the file is deleted from the bucket.
- Added tests for both cases
- Tested both cases by hitting local API server
- `get_file` always optimistically returns `302 Found` when file is in checkout
Relates to #1367
> Optimize file checkout to always return immediately if available

- dss-api.yml
- dss/api/files.py
- need to add a test case.
- A 422 is returned when the file metadata is missing checksums.
> adding 422 when metadata checksums are missing for put_file

- dss/api/bundles/__init__.py
- dss/storage/checkout/bundle.py
- tests/test_bundle.py
These changes follow https://github.com/HumanCellAtlas/data-store/pull/1522. With these changes, if a [stale](https://github.com/HumanCellAtlas/data-store/pull/1516) bundle is accessed, a checkout job will be kicked off but the existing checkout bundle will be returned immediately such that the client does not have to wait for the checkout job to complete, and the bundle's TTL will be refreshed.
- Added integration tests for new stale bundle behavior
- Manual testing against local DSS API server
- Upgraded `cloud-blobstore` to 3.1.0
- Optimized GET bundle to return existing checkout bundles when possible
Fixed #1367
> Optimize get bundle to serve existing checkout bundles whenever possible

- daemons/dss-gs-event-relay/main.py
The GET variables method in GRTC allows us to get all the values in
one go. This reduces the number of GRTC API calls, so we're less
likely to exceed our quota (crashing the function).
https://cloud.google.com/deployment-manager/runtime-configurator/reference/rest/v1beta1/projects.configs.variables/list
> GS event relay: Get all available GRTC env vars in one go

- environment
- infra/build_deploy_config.py
* Move TF state bucket to common HCA DCP bucket
* Put state files int s3://{bucket}/dss/{component}.state instead of s3://{bucket}/dss-{component}.state
* Make bucket account-id parameterization explicit
> Use the HCA DCP common Terraform backend bucket

- README.md
- docs/environment/README.md
Reorganize README into the following sections:
- Overview
- Getting Started
- Configuration
- Running tests
- Deployment
- Development
- Contributing
More complex processes should be captured in separate documentation so as to not crowd the main README. A couple of these topics are:
- Description of environment variables: https://app.zenhub.com/workspace/o/humancellatlas/data-store/issues/1593
- Configuring the HCA CLI: https://app.zenhub.com/workspace/o/humancellatlas/data-store/issues/1594
- Checkout process
Certain sections in the current README should also be extracted into separate documents and expanded on, however, I think more involved discussion is required before organizing this.
> Organize README into sections

- .gitlab-ci.yml
This prevents noisy (and pointless) slack notifications
> [Easy] Don't run GitLab tests when tags are pushed

- environment.integration
This greenbox service account is needed for dcp-wide integration testing.
> [Easy] Update integration checkout bucket whitelist

- iam/policy-templates/dss-admin-lambda.json
- iam/policy-templates/dss-checkout-sfn-lambda.json
- iam/policy-templates/dss-dlq-reaper-lambda.json
- iam/policy-templates/dss-gs-copy-sfn-lambda.json
- iam/policy-templates/dss-gs-copy-write-metadata-sfn-lambda.json
- iam/policy-templates/dss-index-lambda.json
- iam/policy-templates/dss-lambda.json
- iam/policy-templates/dss-notify-lambda.json
- iam/policy-templates/dss-s3-copy-sfn-lambda.json
- iam/policy-templates/dss-s3-copy-write-metadata-sfn-lambda.json
- iam/policy-templates/dss-scalability-test-lambda.json
- iam/policy-templates/dss-sfn-launcher-lambda.json
- iam/policy-templates/dss-sync-sfn-lambda.json
- iam/policy-templates/dss-visitation-lambda.json
Connected to #1623 .
All lambdas were given robust s3 Get*/List* permissions for X-ray I believe, however I believe this is only needed for EC2 instances.  We're trying to tighten down privileges for our data store on the commons side and wanted to submit a PR.  Also to double-check and make sure it passes tests on the HCA side.
Documentation here: https://docs.aws.amazon.com/xray/latest/devguide/xray-permissions.html
> AmazonS3ReadOnlyAccess **(Amazon EC2 only)** – Gives the instance permission to download the X-Ray daemon from Amazon S3.
> Remove unnecessary lambda Get/List permissions for s3.

- .gitlab-ci.yml
Define a scheduled GitLab job for `tests/test_sync.py TestSyncDaemon.test_sync_large_blob`.
See:
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/pipeline_schedules
closes #1290
> Define GitLab test for large blob sync

- .gitlab-ci-prod.yml
- .gitlab-ci.yml
This adds two manual GitLab jobs to enable  `prod` releases:
1. Prod release/force-release buttons in dev GitLab
2. A manual prod build job in prod GitLab
This means that the operator cannot release `prod` until tests are passing on `staging`, and the operator must have access to the prod build box.
Closes #1620
> Define GitLab prod release/deploy

- dss/events/handlers/sync.py
This will cause the sync sfn to retry oneshot copies when presigned urls fail to resolve.
fixes #1636
> Raise sync exception when s3/gs presigned urls fail to resolve

- dss/stepfunctions/s3copyclient/implementation.py
Catch S3 copy client errors to an SFN fail task.
This will allow us to propagate stack traces to end users.
Connected to #1616
> Send S3 copy client exceptions to fail state

- dss/stepfunctions/s3copyclient/implementation.py
Retry on all errors to catch
```
{
"error": "States.TaskFailed",
"cause": "An attempt was made to invoke the Lambda function. Step Functions cannot determine whether Lambda successfully received the call and executed the function."
}
```
> Retry join state in s3 copy sfn

- README.md
Otherwise "make deploy-infra" will fail with:
```
$ make deploy-infra
make -C infra apply-all
make[1]: Entering directory '/home/ubuntu/data-store/infra'
make[2]: Entering directory '/home/ubuntu/data-store/infra'
rm -rf buckets/.terraform/*.tfstate
./build_deploy_config.py buckets
cd buckets; terraform init;
/bin/sh: 1: terraform: not found
make[2]: *** [Makefile:45: init] Error 127
make[2]: Leaving directory '/home/ubuntu/data-store/infra'
make[1]: *** [Makefile:17: apply-all] Error 1
make[1]: Leaving directory '/home/ubuntu/data-store/infra'
make: *** [Makefile:80: deploy-infra] Error 2
```
> State that terraform is needed

- scripts/populate_lambda_ssm_parameters.py
Currently, Lambda environment variables are read from SSM during deployment.
This makes it possible to update environment variables without re-deploying in the following manner:
1. SSM only
1. SSM and all deployed lambdas
1. Individually set or unset one environment variable in SSM and all deployed lambdas
> Provide fine grained management of Lambda environment variables

- dss/util/async_state.py
- iam/policy-templates/ci-cd.json
- infra/async_state_db/main.tf
- tests/test_async_state.py
This will make it possible to catch copy sfn errors and expose them to the api.
It may also be useful as a lightweight caching mechanism.
related to #1616
> Store and recover chunks of state in dynamodb

- dss/api/files.py
- dss/events/handlers/sync.py
- dss/stepfunctions/gscopyclient/implementation.py
- dss/stepfunctions/s3copyclient/implementation.py
- iam/policy-templates/dss-lambda.json
- iam/policy-templates/dss-s3-copy-sfn-lambda.json
- iam/policy-templates/dss-s3-copy-write-metadata-sfn-lambda.json
- tests/fixtures/cloud_uploader.py
- tests/test_file.py
Stash copy sfn errors into async state and raise on GET or HEAD /file.
depends on #1705 
fixes #1616
> Use async state to catch/expose copy sfn errors

- dss/util/__init__.py
- scripts/deploy_gcf.py
- tests/__init__.py
This is useful for local testing and local scripting requiring GCP service credentials.
> Convenience function for temporary local storage of gcp credentials

- .gitlab-ci.yml
This will allow the `release_*` GitLab CI/CD button to work again.
> [Easy] Remove obsolete release flag from .gitlab-ci.yml

- tests/test_collections.py
This allows collections tests to pass for deployments other than master.
> Grab collections owner from gcp credentials during tests

- .gitlab-ci.yml
Variable created in GitLab yml (outside of `variables`) are not interpolated, causing GitLabs environment mechanism to fail silently.
issue: https://gitlab.com/gitlab-com/support-forum/issues/2814
potential fix: https://gitlab.com/gitlab-org/gitlab-ce/issues/27921
> Remove url from GitLab environments

- dss/api/search.py
Checking that all shards returned successfully to preventing partial search result from being returned. 
None
None
Search will return an internal_server error if partial search results were retrieved due to shard failure.
Fixes #1770
> Error returned if partial results are returned.

- docs/environment/README.md
- environment
- scripts/populate_lambda_ssm_parameters.py
This is needed for non-DCP deployments to use their own SSM parameter store.
> Parameterize SSM store name in environment

- scripts/populate_lambda_ssm_parameters.py
When population AWS Systems Manager parameters, warn instead of fail on undefined environment variables.
This allows variables such as DSS_VERSION, which is set during deployment, to be undefined when populating SSM values.
Make some readability improvements.
depends on #1814
> Populating lambda SSM warns on undefined vars

- README.md
- docs/environment/README.md
- environment
- infra/build_deploy_config.py
- infra/cloudtrail/audit_trail.tf
- Adding terraform script to enable audit logging for AWS resource
- Update documentation with instruction on how to enable audit logging
- Added environment variable to toggle audit logging
- Updated documentation for new environment variables.
- connects to #1667 
Tested the terraform plan, and verified the logs were generated.
- can now toggle audit logging for the DSS.
> Optional Audit logging for DSS in AWS.

- environment.prod
- infra/domain/main.tf
- Increase ES volume size to max for cluster
- Don't manage cert validation through TF
The prod domain and certificate was not created through Terraform, cannot be straightforwardly imported into the Terraform state file, and there appears to be little value in managing it through Terraform.
> Update infra defs for prod

- chalice/build_deploy_config.sh
- daemons/package_daemon.sh
- scripts/populate_lambda_ssm_parameters.py
This fixes a bug causing ADMIN_USER_EMAILS to be set to an empty string during deploy.
> Put admin user emails in SSM store

- tests/sample_doc_tombstone.json
- tests/sample_search_queries.py
- tests/test_indexer.py
This ensures that notifications are sent to a subscriber_id if the tombstoned bundle matches their query or if the subscriber is subscribed to tombstones.
> notify tombstone

- daemons/dss-sync-sfn/app.py
This gets rid of the following class of sync daemon error:
```
2019-01-23 19:26:30+00:00 Unknown prefix for key cache.1/3eecbe82f512d809efbcb817ae57bfe5c03dfd613eecbe82f512d809efbcb817ae57bfe5c03dfd61: NotImplementedError
File "/var/task/domovoi/app.py", line 209, in __call__
result = handler(event, context)
File "/var/task/app.py", line 283, in check_deps
if dependencies_exist(source_replica, dest_replica, event["source_key"]):
File "/var/task/domovoilib/dss/events/handlers/sync.py", line 279, in dependencies_exist
raise NotImplementedError("Unknown prefix for key {}".format(key))
NotImplementedError: Unknown prefix for key cache.1/3eecbe82f512d809efbcb817ae57bfe5c03dfd613eecbe82f512d809efbcb817ae57bfe5c03dfd61
```
> Ignore cache objects when syncing

- dss/api/search.py
- tests/sample_v0_index_doc_tombstone.json
- tests/test_search.py
in cases where manifest.version is not specified in the ES tombstone document we would still like to page through the results.
related to #1846 
added test cases to page through tombstones with manifest.version and without and verified that multiple pages of results can be returned.
None
None
> Search when Version is None

- iam/policy-templates/dss-visitation-lambda.json
This fixes an issue with `integration` that occured during the bucket move.
> Add s3:GetObjectTagging permissions to the visitation lambda explicitly.

- daemons/dss-sync-sfn/app.py
This appears to fix sync daemon deploy woes.
Perhaps the AWS CLI grabs Lambda output via Cloudwatch, causing logged errors to appear as Lambd failures?
> [Easy] Sync logs INFO instead of ERROR for existing keys

- dss/index/es/backend.py
- dss/index/es/document.py
- tests/test_indexer.py
- fixes #1866
- When a bundle delete is performed without the version specified, all bundles sharing that UUID are deleted. Notifications will be sent out for each version of that bundle that has been deleted when a bundle deletion for all version is processed.
- The LocalNotificationRequestHandler infrastructure was modified to track all notification received by the local notification server, and returns the requests in LIFO order.
- A new local test was added test_unversioned_tombstone_notifications
> Notification sent out for all versions of a deleted bundle

- dss/util/networking.py
- tests/test_utils.py
This is needed for bundle scalability work and should be encouraged for use by any library that performs HTTP requests.
> Add HTTP request handler preconfigured with timeout and retry policies

- environment.prod
Change instance type from `m4.large.elasticsearch` to `m4.2xlarge.elasticsearch`
Price is scaled up from `$0.151/hr` to `$0.603/hr`
Addresses #1801
> Scale up the prod ES domain

- dss-api.yml
This documents JMESPath subscriptions, which differ slightly to Elasticsearch subscriptions.
It is our intention to migrate all subscriptions to JMESPath.
fixes #1909
> Document subscriptions in swagger

- daemons/dss-notify-v2/app.py
- dss/events/handlers/notify_v2.py
- tests/test_notify_v2.py
This fixes a bug causing notifications to remain in queue after object has been deleted.
Instead, dequeue and log notification failure.
> Fix JMESPath notification race condition

- iam/policy-templates/ci-cd.json
We ran into a file size limit on our ci-cd group policy.  See #1963.
> Truncate ci-cd.json to get around the file size restriction AWS imposes.

- README.md
- dss-api.yml
This PR explicitly adds Retry-After headers to [500, 502, 503, 504] responses for all methods except `POST /bundles/{uuid}/checkout`.
This allows the client to know which codes to retry on, even if it is a POST request (currently there is a desire to retry on POST search, see: https://github.com/HumanCellAtlas/dcp-cli/issues/222 ).
*Current CLI behavior:*
Do not retry on POST methods.  Retry on 500, 502, 503, & 504 for all non-POST methods.
*Updating the swagger would:*
Allow changes in the `dcp-cli` to retry on POST search but not `POST /bundles/{uuid}/checkout`.
> Update swagger with explicit retry-after headers.

- environment.prod
This allows `make plan-infra` to pass on prod.
> Fix ACM_CERTIFICATE_IDENTIFIER in environment.prod

- README.md
- security.txt
Links to the centralized policy at `dcp`, based on the conversation here: https://github.com/HumanCellAtlas/dcp/issues/274 .
> [Easy] Centralize SECURITY.md, and delete security.txt.

- dss/config.py
The default number of pool connections available to botocore is 10.
Increase to 20 to provide more future parallelization to verification logic in PUT and PATCH /collections and /bundles.
connects to #1901
> Increase max number of botocore connections

- chalice/.chalice/config.json
Adding 1000 files to a collection or bundle currently tends to time out.
With this change, and some forthcoming parallelization changes, adding 1000 files to a collection takes ~12 seconds, and adding 1000 files to a bundle takes ~5 seconds.
API Lambda costs are increased by a factor of 5 (from 0.000000417/100ms to 0.000002084/100ms).
connects to #1901
> Increase Lambda mem+cpu

- dss/api/collections.py
Use a few more connections to marginally increase verification performance.
depends on #1993 #1994 
connected to #1901
> Increase collection verification parallelization

- dss-api.yml
- dss/api/collections.py
- scripts/swagger_auth.py
- tests/test_collections.py
Addresses #1932.
This endpoint adds the `GET /collections` root endpoint which allows a user to retrieve all of their collections without knowing the UUID for each one.
For example:
```
res = self.app.get('/v1/collections',
headers=get_auth_header(authorized=True),
params=dict(replica='aws'))
print(res.json())
```
Should return something like this:
```
{
"collections": [
{
"collection": {
"contents": [
{
"type": "file",
"uuid": "29aad27a-536a-42c3-92df-e7c5a14df22d",
"version": "2019-04-02T165421.995240Z"
},
{
"fragment": "/foo",
"type": "foo",
"uuid": "29aad27a-536a-42c3-92df-e7c5a14df22d",
"version": "2019-04-02T165421.995240Z"
}
],
"description": "d",
"details": {},
"name": "n",
"owner": "service-account@b.gserviceaccount.com"
},
"collection_uuid": …
```
> Add a root collections endpoint.

- dss-api.yml
- dss/api/collections.py
- tests/test_bundle.py
- tests/test_collections.py
Addresses #1920.
This adds paging to the new `GET /collections` root endpoint, with some caveats.
Right now this is really expensive as all collections in a bucket need to be searched and opened to determine ownership before returning the information to the user.
To prevent timing out, I've put in a max paging size of 100 (min 50).  This will check each chunk of 100 `collection` files in the bucket and return any belonging to the user per page (takes about 15s per page when the bucket contains about 2000 collections).
This means instead of returning 100 collections per page, it will return between 0 and 100 collections per page since it needs to check them all, but only some will belong to the user.
Collections need to be indexed to make this scalable.
> Add paging to collections.

- dss/api/bundles/__init__.py
- tests/test_bundle.py
This fixes a bug wherePATCH /bundle was not updating bundle version in the manifest, and adds tests.
fixes #2015
> [Easy] PATCH /bundle sets version correctly

- dss/api/bundles/__init__.py
This causes PATCH /bundle to throw an error if the bundle is tombstoned
fixes #2016
> [Easy] Disallow PATCH on tombstoned bundles

- dss-api.yml
- dss/api/bundles/__init__.py
- dss/index/es/document.py
- environment
- tests/test_indexer.py
Elasticsearch document size limits prevent inclusion of large bundle manifests into the indexed document:
- https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html#network-limits
- https://stackoverflow.com/questions/55541625/aws-elasticsearch-cluster-method-to-update-http-max-content-length
> Exclude very large bundle manifests from ES document

- dss/events/handlers/notify_v2.py
Perform S3 GETs in parallel while building metadata document for JMESPath filtering.
> Add parallelization to JMESPath filter doc construction

- daemons/dss-notify-v2/.chalice/config.json
- daemons/dss-notify-v2/app.py
This parallelizes JMESPath filtering and notification delivery, and scales up the notification Lambda.
Future notification scaling tracked via #2034
> Parallelize JMESPath notification delivery

- dss/api/bundles/__init__.py
- dss/util/__init__.py
- tests/test_utils.py
This improves PATCH /bundle performance by uploading large manifests in parallel, presumably saturating the Lambda-S3 network connection.
Incidentally, it may be possible to improve manifest paging performance by downloading individual parts from s3 multipart manifest objects.
closes #2012
> Use s3 multipart upload for large bundle manifests

- dss/api/bundles/__init__.py
- dss/api/collections.py
- dss/storage/bundles.py
Previously, bundle manifests were cached in memory during GET. This extends that functionality to PUT and PATCH /bundle, improving PATCH performance.
closes #2011
> Bundle manifest memcaching

- daemons/dss-gs-event-relay/main.py
- daemons/dss-index/app.py
- daemons/dss-notify-v2/app.py
- daemons/dss-sync-sfn/app.py
This is needed for the JMESPath notification daemon to handle deletion events.
connected to #2003
> Forward GCP object deletion events

- dss/events/handlers/notify_v2.py
This keeps JMESPath and ES queries consistent.
> [Easy] decode if content-type contains "application/json"

- dss/config.py
This matches S3 connection pool
Also addresses `WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: www.googleapis.com`:
https://travis-ci.com/HumanCellAtlas/data-store/jobs/195750957
> Increase GS client connection pool to 20

- daemons/dss-sync-sfn/app.py
- dss/events/handlers/sync.py
- tests/test_sync.py
When object size is an integer multiple of part size, `object_size // part_size) + 1` evaluates to the incorrect number of parts.
> Fix multipart sync completion criteria

- daemons/dss-operations/app.py
Otherwise this may DOS logger tooling when performing operations on large buckets.
> Increase operations daemon log level to WARNING

- dss/operations/util.py
- tests/test_operations.py
This makes `map_bucket` easier to use.
> [Easy] improve bucket mapping operations utility

- iam/policy-templates/dss-lambda.json
Addresses issue where Lambda does not have privileges to list resource by tag type.
> [EZ] Update lambda-iam for accessing resource by tag

- dss/operations/storage.py
- tests/test_operations.py
This operation
1. Verifies that file metadata is equivalent on all replicas (where file metadata is referenced by key=`files/{uuid}`
2. sets the blob content-type equal to the file metadata content-type
> Operation to repair file blob metadata

- dss-api.yml
- dss/api/files.py
- tests/test_file.py
Return direct url option for `GET /file/{uuid}` endpoint
Addresses: #2045
This PR returns a cloud native URL with the same path as is currently used for the presigned URL, the blob key path (with checksums), and refers to the same object in the checkout bucket.
There is a current question regarding whether that is the best/right path to return going forward, yet this current change is sufficient to unblock the HCA handoff to Terra effort.
> Direct URLs for Files

- dss/stepfunctions/gscopyclient/implementation.py
Hopefully addresses intermittent failures like this one: https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/-/jobs/31047 .
> Change how content-type is propagated when caching.

- tests/test_sync.py
Specify replication information in blob content type during sync tests.
This will either fix intermittent errors in sync, or elucidate them.
addresses #2159
> Specify replicas in sync test content-type

- dss/stepfunctions/gscopyclient/implementation.py
- tests/test_checkout_caching.py
This:
1. Avoids lost state by adding choice step to SFN flow
2. Provides 10 seconds of padding for thread to time out before Lambda times out
> Resume unfinished GS copies

- dss/util/async_state.py
- tests/test_async_state.py
This:
1. Adds convenience method to async state to capture state absent private keys
2. Prevents accidental modification of state data before putting into database
> Async state convenience methods and bug fixes

- dss/operations/storage.py
- tests/test_operations.py
This reports the object key during storage file blob metadata repair operations. Also, improve testing.
> Storage operations errors log object info

- dss/operations/storage.py
- dss/operations/sync.py
- dss/storage/identifiers.py
- scripts/dss-ops.py
- tests/test_operations.py
This ads an operation to verity that an entity, and all references, exists on target and destination replicas.
connected to #2172 
closes #2096
> Add operation to verify entity replication

- daemons/dss-sync-sfn/app.py
- dss/operations/sync.py
This allows DSS operators to initiate sync for replica repair, and eventually replica standup.
The new functionality is:
1. Adding an operational SQS queue entry point to the sync daemon, and
2. Pushing sqs messages to the operational queue
This has been tested manually.
closes #2171
> Add operation to trigger sync

- daemons/dss-notify-v2/app.py
10000 bundles * 60 stale subscriptions * 7 days * 24 retries/day = one hundred million requests, which is a lot.
This is in place on dev, integration, and staging.
Perhaps we should consider automatically deleting unserviceable subscriptions.
> (Temporarily) reduce notification retry to every 6 hours for 3 days

- dss-api.yml
- dss/storage/identifiers.py
- tests/test_api.py
- tests/test_identifiers.py
Noticed this when testing.  Some of the uuids in the swagger differ from each other as well.  This ensures we only use version 4 RFC4122-compliant IDs.
We seem to have variations between `A-Za-z0-9` and `a-z0-9` in our swagger doc, and the regex in `storage/identifiers.py` only allows `A-Fa-f0-9`.
The actual standard (for version 4) is `a-f0-9`, which is none of these.  I'm wondering which regex makes sense, because I think they should all be the same regex.
I opted for `A-Za-z0-9` based on @kislyuk 's response.
> [easy] Use the same regex for all uuids.

- dss/operations/__init__.py
- dss/operations/storage.py
- scripts/dss-ops.py
- Don't generate job-id unless forwarding commands for cloud execution.
- Make sure user-specified job-id is used
> Better operations job-id handling

- tests/infra/base_smoketest.py
Avoid more smoktest failures due to sync impatience.
> [Easy] Increase smoketest sync wait to 120s

- environment
Added `GROUP_All_Users@firecloud.org` to the `DSS_CHECKOUT_BUCKET_OBJECT_VIEWERS` environment variable so users of the Broad's Terra/FireCloud workspace can run workflows accessing HCA data.
For more information, please see: #2210
Fixes #2210
> Allow Terra user read access to Google checkout bucket

- environment
Type (serviceAccount or group) is required during policy application.
connected to #2210
> [Easy] Include type for firecloud checkout viewer

- dss-api.yml
- dss/api/subscriptions_v1.py
- tests/test_subscriptions.py
replaces `hmac_secret_key` with `hmac_key_id` for get/find subscription operations.
> [EZ] GET/ Subscription_v1 HMAC Key Change

- dss/api/files.py
- dss/operations/storage.py
- dss/stepfunctions/s3copyclient/implementation.py
Multipart file uploads weren't specifying the content-type and so this was creating mismatches.  Tested and working when the step function is manually deployed.
> Verify content type.

- tests/test_file.py
`test_file_get_checkout()` has been flaky lately.
> [easy] Extend test_file_get_checkout's test_creation_date_updated time.

- dss/operations/events.py
- scripts/dss-ops.py
This is useful for quickly downloading the metadata of a bundle, which is the document validated against JMESPath subscriptions filters.
> Add operation to output bundle metadata document

- tests/test_sync.py
This prevents exceptions when GCP bucket listing becomes out of date during cleanup operations.
closes #2271
> [Easy] Increase concurrency safety of sync test cleanup

- daemons/dss-notify-v2/Readme.md
- dss/events/handlers/notify_v2.py
- tests/test_notify_v2.py
- tests/test_operations.py
Provides more context to a jmespath notification, adds:
``` 
"dss_api": api url
"bundle_url" : url to bundle matched.
"event_timestamp": timestamp for when event was created
```
Resolves: #2184
> Notify V2 Payload Context

- dss/api/collections.py
Schema requires version parameter be provided, so the code removed
by this commit would never run.
> Require version in PUT /collections (closes #2280)

- chalice/app.py
Flask request context is not generally available during timeout exceptions. Request contextual information is passed into `timeout_response` from chalice instead.
> Use chalice request context

- dss-api.yml
- tests/test_collections.py
Reverts HumanCellAtlas/data-store#2317.
* Reverts changes to dss-api.yml due to changes being formatted in Swagger 3.0 spec, vs 2.0 (current)
* Reverts breakage in dcp-cli due to Client Method Factory not being able to parse mixed versions
Schema is OpenAPI v2, not v3.
> Revert "1k item limit in PUT /collections (closes #2281)"

- chalice/build_deploy_config.sh
- daemons/build_deploy_config.sh
- infra/async_state_db/main.tf
- infra/buckets/gs.tf
- infra/buckets/s3.tf
- infra/collections_db/main.tf
- infra/elasticsearch/main.tf
- infra/subscription_v2_db/main.tf
change resource tagging `Name` to reference sub-component of the DSS
adds labels to gcp buckets
> Tagging Updates: Name

- .gitlab-ci.yml
This checks the correct target branch for dcp-wide integration test status, allowing the normal release button (not force release) to work in allspark.
> Check the correct DCP branch status during release

- .gitlab-ci.yml
Move Trufflehog check to its own stage, and run it first. This prevents Trufflehog installation from contaminating release dependency verification.
> Dedicated Trufflehog CI/CD stage

- scripts/release.sh
This improves visibility into status check failures during releases.
> [Easy] More informative release status

- .gitlab-ci.yml
- scripts/release.sh
This simplifies the release scripting by skipping redundant status checks when a CI environment is detected.
Status checks were previously performed while the CI/CD pipeline was _currently running_. Since status is always `running` in this case, the check for `status==success` failed.
> Simplify release scripting

- dss/storage/checkout/file.py
There have been some weird sync errors.
```
Unknown prefix for key 542497a4-cccc-4659-bb87-784273ed46bf/process_10.json: NotImplementedError
File "/var/task/domovoi/app.py", line 223, in __call__
result = handler(event, context)
File "/var/task/app.py", line 327, in check_deps
if dependencies_exist(source_replica, dest_replica, event["source_key"]):
File "/var/task/domovoilib/dss/events/handlers/sync.py", line 293, in dependencies_exist
raise NotImplementedError("Unknown prefix for key
{}
".format(key))
NotImplementedError: Unknown prefix for key 542497a4-cccc-4659-bb87-784273ed46bf/process_10.json
```
https://github.com/HumanCellAtlas/data-store/blob/master/dss/events/handlers/sync.py#L293
https://console.aws.amazon.com/states/home?region=us-east-1#/stat …
> Assert we don't checkout to the main bucket (avoiding a sync error).

- dss/operations/secrets.py
- tests/__init__.py
- tests/test_operations.py
This commit has two parts:
- additions to `tests/__init__.py` that add context manager objects to capture stdout and to feed a string to stdin
- additions to `test_operations.py` that test specific functionality added to dss operations (secrets verb)
Note: this PR is to merge into the `dss-secrets` branch (#2325), not the `master` branch
> Add tests for dss-ops secrets functionality

- dss/operations/secrets.py
- scripts/dss-ops.py
- tests/__init__.py
- tests/test_operations.py
This pull request adds functionality to dss-ops that allows it to manage secrets. There are three verbs added:
* `dss-ops.py secrets list` to list secrets (names only)
* `dss-ops.py secrets get --secret-name <X>` to get a secret variable's value
* `dss-ops.py secrets set --secret-name <X>` to set a secret variable's value
* `dss-ops.py secrets delete --secret-name <X>` to delete a secret variable from the secrets manager
The `set` action can take input piped in from stdin.
This PR closes #2296
> Add secrets management to dss-ops script

- dss/events/handlers/sync.py
This relaxes the sync metadata size limit to 50 MB. Bundle manifests containing tens of thousands of files are expected to be in this range.
> Relax sync size limit

- tests/test_operations.py
This fixes a hard-coded stage variable ("dev") to use an environment variable instead.
> Remove hard-coded stage name in secrets tests

- dss-api.yml
- dss/api/bundles/__init__.py
- tests/test_bundle.py
The last PR, #2344, broke master. Sorry about that! I did two things wrong:
1. I incorrectly believed that I could expect certain test failures when testing locally without a new deployment. This was not the case. I've now confirmed that affected tests pass locally.
2. I misunderstood how tombstoning worked and how bundles were stored, so the failing test I wrote was testing the wrong thing.
This PR fixes that.
> Fix 500 on delete nonexistent bundle, again (fixes #1918)

- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
- README.md
- daemons/dss-dlq-reaper/README.md
- daemons/dss-gs-event-relay/Readme.md
- daemons/dss-notify-v2/Readme.md
- daemons/dss-scalability-test/README.md
- dss/notify/README.md
This pull request does a few things:
* Fixes improper markdown in various markdown files in the repository (formatting changes only, no content changes)
* Changes the PR and issue templates to be more navigable and readable
Most of the improper markdown looks fine on Github because Github's markdown rendering engine is more forgiving, but many docs look broken when viewed in any application/website that uses stock markdown syntax.
> Fix improper markdown

- tests/test_smoketest.py
Reorder smoke test to allow more time between replication and prefix enumeration
> DSS SmokeTest: Test Order

- tests/test_bundle.py
Fixes `test_bundle.py` endpoint was not changed in after discussion to rename.
> DSS Bundle Enumeration: Test Fix

- dss/operations/ssm_params.py
- scripts/dss-ops.py
- tests/__init__.py
- tests/test_operations.py
This PR adds functionality to the `dss-ops.py` script that allows operators to list, set, and unset parameters stored in the SSM store under the "environment" variables. It also adds tests for the new SSM parameter functionality.
This PR is part of #2299 and is a reworked version of (part of) a PR that was abandoned (#2324). This PR is much simpler and should be easier/faster to review.
> Add SSM parameter store functionality to dss-ops

- tests/test_smoketest.py
Previously we were only performing these tests on the last replica set here: https://github.com/HumanCellAtlas/data-store/blob/4b10ceea51249995cbe89ba9f109dcb980188a01/tests/test_smoketest.py#L61
> Testing upload, get_bundle, and checkout with different replicas

- .gitlab-ci.yml
- roles.json
This PR addresses HumanCellAtlas/dcp-fusillade#7.
These changes are to the integration system on Allspark, so it needs to be in a PR in order for it to be tested. The changes made to the Fusillade deployment also need to be tested, but will not be tested using anything added in this pull request.
Each stage of the DSS will use a script in HumanCellAtlas/dcp-fusillade to set up Fusillade with the roles defined in `roles.json` in this repo. 
Either each DSS stage will use the `testing` stage of Fusillade as the target for the setup script, or each DSS stage will use the corresponding stage of Fusillade (staging->staging, integration->integration). This needs some clarification.
TBA
> Add fusillade stage and setup fusillade step to CI/CD

- dss/api/bundles/__init__.py
- dss/config.py
- dss/util/security.py
- environment
- environment.integration
- environment.prod
- environment.staging
- roles.json
- tests/infra/auth_tests_mixin.py
- tests/test_bundle.py
fixes deployment issues cause by #2303 
- Added roles `dss-admin` and `dss_privilaged_user` roles to `fusillade-dev` using ./script/setup_authz.py.
- Added `travis-test` google service account as `fusillade_admin`, and `dss_admin` for `fusillade-dev`
- Run ./script/setup_authz.py for each deployment of DSS.
- Make users `dss_privilaged_users` who need permission to delete and write bundles.
- add script to setup DSS with fusillade. A google service account that has permission to modify fusillade is required before running.
- Added a folder for to created, and manage dss related roles.
- Using fusillade to authorize bundle related write API requests
> Adding fusillade to bundle write operation

- dss/operations/lambda_params.py
- dss/operations/ssm_params.py
- scripts/dss-ops.py
- tests/test_operations.py
This PR adds functionality to the dss-ops.py script that allows operators to list, set, and unset deployed lambda functions and their environments (environment variables).
This PR is part of #2299 and is a reworked version of (part of) a PR that was abandoned (#2324). This PR is much simpler and should be easier/faster to review.
This closes #2389
> Add lambda parameter functionality to dss-ops

- scripts/deploy_gcf.py
Google cloud functions were failing for a few hours due to google cloud function flakiness.  This error handling should hopefully save time in the future trying to figure out why google cloud functions are breaking for no good reason.
> [easy] Add GCP function error handling.

- dss/operations/lambda_params.py
- dss/operations/secrets.py
- tests/test_operations.py
This addresses #2374 (issue) as well as #2423 (issue), both related to improving the existing functionality for secrets handling in dss-ops.
This will also unblock #2359 (issue - remove and replace set_secrets and fetch_secrets from other operational toolling) and PR #2370 (associated pull request).
This implements new tests in `tests/test_operations.py`
N/A
> Improve security in dss-ops secrets handling

- daemons/dss-sync-sfn/app.py
- dss/api/files.py
- dss/storage/identifiers.py
- tests/test_sync.py
skips sync if blob key does not match `blob/{sha256}-{sha1}-{s3_etag}-{crc32c}`
> DSS Sync: skip sync on file parts

- tests/test_sync.py
Removes special `blob_keys` used within sync tests to pass through filter.
> Dss Sync Filter: Integration Test Refactor

- .gitlab-ci-prod.yml
- .gitlab-ci.yml
- README.md
- scripts/check_deployment_secrets.py
- scripts/create_config_aws_event_relay_user.py
Closes #2359 
This pull request replaces instances of `set_secret.py` and `fetch_secret.py` that appear in infrastructure setup with calls to `dss-ops.py secrets`.
I may need some help with testing - this is introducing changes to the CI server, and am not sure if there is a way to test these changes without deploying.
> Update infrastructure to use dss-ops.py and not set_secret/fetch_secret

- .gitlab-ci-prod.yml
- .gitlab-ci.yml
- README.md
- scripts/check_deployment_secrets.py
- scripts/create_config_aws_event_relay_user.py
Reverts HumanCellAtlas/data-store#2370
There is a problem creating/using local Google Cloud service credentials, so unit tests are failing. Reverting until the issue has been resolved.
> Revert "Update infrastructure to use dss-ops.py and not set_secret/fetch_secret"

- daemons/dss-notify-v2/app.py
adds logging for s3 bundle events that don't have warnings.
> DSS Notifyv2: add logging [EZ]

- daemons/dss-operations/app.py
- dss/operations/events.py
- dss/operations/util.py
- requirements-dev.txt
- requirements.txt
- requirements.txt.in
This adds commands to the data-store operations scripting for events:
- record: record events for a list of keys, or for every bundle in replica
- journal: compile flashflood events into journals
- update: apply event updates to the event journals
> Operation scripting for recording and journaling events

- dss/api/bundles/__init__.py
- dss/api/collections.py
- dss/api/events.py
- dss/api/search.py
X-OpenAPI-Paginated-Content-Key needs to be sent with every response
for methods that support pagination, even if there is only one
page. The client needs the key name metadata in
X-OpenAPI-Paginated-Content-Key to stream results without hardcoding
the key name.
> Send X-OpenAPI-Paginated-Content-Key even when only one page is present

- tests/test_bundle.py
- tests/test_smoketest.py
move complex enumeration tests out of `tests/test_smoketest.py`, introduces more testing into `tests/test_bundles.py`
marks file for `@testmode.standalone`
addresses change to header in test
> DSS Bundle Enumeration: Test Refactor

- tests/test_api.py
- tests/test_bundle.py
Adds the Mock Fusillade Server to `tests/test_bundle.py` and `tests/test_api.py`
> Add Mock Fusillade server to test_bundle and test_api

- dss/operations/elasticsearch.py
This adds an operation to the `dss/operations` framework to bulk queue SQS messages to the indexer lambda for each key in `bundles/{pfx}`.
Usage:
```
scripts/dss-ops.py elasticsearch index-prefix --replica {replica} --prefix 0
```
> Add Elasticsearch reindex operation

- dss/operations/iam.py
- dss/operations/lambda_params.py
- tests/test_api.py
- tests/test_bundle.py
- tests/test_operations.py
This PR is made on the `chmreid-iam-ops` branch.
This PR splits up and isolates some of the fusillade-specific work in PR #2492. It is intended to make that pull request easier to review.
Also, PR #2501 adds tests for new fusillade IAM functionality to this pull request.
> Add Fusillade to IAM auditing functionality in dss-ops script

- dss/operations/events.py
- dss/operations/util.py
This uses the new bundle enumeration tooling to avoid recording events for tombstoned bundles.
> Avoid recording tombstones into events

- dss/events/__init__.py
20 workers is probably too aggressive for Lambda parallelization.
> [Easy] Reduce concurrency of bundle metadata document construction.

- dss/operations/lambda_params.py
- tests/test_operations.py
This fixes a problem with how lambda variable prefixes are set. The SSM store requires a leading /, while the secrets store does not. This update reflects that change in `dss/operations/lambda_params.py`.
> Hotfix for lambda params

- dss/api/bundles/__init__.py
- dss/storage/__init__.py
This is the first of several PRs needed to implement the file deletion API (#2409). This PR refactors a tombstone helper function to be consistent with the deletion RFC and relocates it in preparation for use with files (and not just bundles).
> Gentle refactor of tombstoning code

- dss/operations/__init__.py
This fixes a bug in the `dss-ops.py` script that prevented docstrings for sub-parser sub-commands from being printed.
Before:
```
$ ./scripts/dss-ops.py secrets -h
usage: dss-ops.py secrets [-h] {list,get,set,delete} ...
positional arguments:
{list,get,set,delete}
optional arguments:
-h, --help            show this help message and exit
```
After:
```
$ ./scripts/dss-ops.py secrets -h
usage: dss-ops.py secrets [-h] {list,get,set,delete} ...
positional arguments:
{list,get,set,delete}
list                Print a list of names of every secret variable in the
secrets manager for the DSS secrets manager for
$DSS_DEPLOYMENT_STAGE.
get                 Get the value of the secret variable specified by
secret_name.
set                 Set the value of the secret variable.
delete …
```
> [EASY] Add help to dss-ops subcommands

- infra/collections_db/main.tf
- infra/subscription_v2_db/main.tf
Closes #1661.
Backs up the collection and subscription DynamoDB tables by enabling point-in-time recovery (PITR).
The original ticket specified backing up v1 subscriptions, which are backed by ElasticSearch, which is being deprecated. Because DynamoDB is severless, the need to back up data in the event of a component failure is reduced.
Because PITR restores take are not fast (can take hours), the main use case of these backups seems to be to protect against unintentional wide-scale deletion of data.
> Back up collections, subscriptions (closes #1661)

- dss/operations/iam.py
- tests/test_operations.py
This PR adds Fusillade functionality to the dss-ops.py script's IAM action.
This PR is part of #2509
This adds both Fusillade IAM functionality and tests for the new functionality.
> Add Fusillade IAM auditing functionality to dss-ops script (redux)

- dss/events/__init__.py
- dss/operations/events.py
- requirements-dev.txt
- requirements.txt
- requirements.txt.in
- tests/test_events.py
- tests/test_operations.py
This adds a Lambda-parallelized event journaling operation, and a journal listing operation. It also centralizes some flashflood access calls to `dss/events/__init__.py`
flashflood is bumped to 0.4.1
> Improve events operations, bump flashflood to 0.4.1

- Makefile
Updates Makefile to invoke unittest with the `--buffer` option,
which buffers stdin and stdout for each tests and discards the
buffer if the test passes. Ideally, this will help make CI logs
more manageable.
I see that `DSS_UNITTEST_OPTS` can also be set, and that it
is configured in `.gitlab-ci.yml`, `.travis.yml`, etc. but I don't see
a reason that this shouldn't be default behavior.
> Suppress test output for passing tests.

- dss-api.yml
Swagger validator chokes on duplicate `type` declarations in `EventsManifest.events.items.properties`.
> Remove duplicated keys in API spec

- dss/storage/bundles.py
- tests/test_storage.py
This adds a method to list bundle keys associated with a tombstone key, in the following manner:
For this listing:
```
bundles/uuid.version1
bundles/uuid.version2
bundles/uuid.version2.dead
bundles/uuid.version3
bundles/uuid.version3.dead
bundles/uuid.dead
```
We should get these results:
`get_tombstoned_bundles(bundles/uuid.version2.dead)` -> `bundles/uuid.version2`
`get_tombstoned_bundles(bundles/uuid.dead)` -> `bundles/uuid.version1`
Note that the unversioned tombstone is associate with bundles _not previously tombstoned_.
This functionality will be useful for refactoring notify_v2 logic, and for forthcoming logic to remove tombstoned bundles from event streams.
> Add method to list bundle zombies

- .gitlab-ci.yml
This prevents fusillade setup from running for feature branch CI/CD pipelines.
> Only setup fusillade for main branches

- daemons/dss-index/.chalice/config.json
- daemons/dss-notify/.chalice/config.json
Partially addresses: https://github.com/HumanCellAtlas/data-store/issues/2583
> [Easy] Set dss-indexer lambda concurrency to 200; increase timeout by 1 minute.

- dss/error.py
This includes error information along with the stacktrace in API server logs. Previously only the stacktrace was logged, which does not perform string interpolation.
> Include error message in api logs

- dss/events/__init__.py
- tests/test_events.py
This renames `_build_bundle_metadata_document` to `build_bundle_metadata_document`.
> [Easy] Private event method should be public

- .gitlab-ci-prod.yml
- .gitlab-ci.yml
This PR addresses #2546 and attempts to fix PR #2539 (which was abandoned) and #2585 (which we decided was not the right approach).
This PR removes this problematic line from `.gitlab-ci.yml`:
https://github.com/HumanCellAtlas/data-store/blob/master/.gitlab-ci.yml#L22
It keeps this line in `.gitlab-ci-prod.yml` but fixes the syntax:
https://github.com/HumanCellAtlas/data-store/blob/master/.gitlab-ci-prod.yml#L19
Removes `not` and replaces `==` with `!=`
Useful:
- List of environment variables defined in Gitlab CI/CD tests, plus example values: https://docs.gitlab.com/ee/ci/variables/
- PR #1423 (commit 8b0b44c) originally added this line, the intent seems to be to prevent Allspark from deploying when Allspark and Github are out of sync
- [This …
> Move check of whether allspark is behind github to prod stage only

- tests/test_notify_v2.py
This extends the wait time for test notification delivery from 60 seconds to 120 seconds.
> [Easy] Extend test expectation TTL for v2 notifications

- daemons/dss-notify-v2/Readme.md
Taking a shot at #2563 to improve JMESpath documentation, improving changes suggested in #2510.
This addresses the following issues:
- documents what the bundle manifest looks like (individual fields)
- replaces `file_name_1` with `file_name_A` and mentions the transformation of `_dot_to_underscore_and_strip_numerical_suffix`
- replaces `{variable_name}` interpolation with `$variable_name` interpolation (good way of denoting variable JSON contents independent of JSON syntax, and also useful if using something like `envsubst`)
None required, this only changes documentation
N/A
Improving JMESpath documentation for v2 notifications
> Improve jmespath/dss-notify-v2 documentation

- dss/api/events.py
- dss/config.py
- dss/events/__init__.py
- tests/test_events.py
This configures flashflood to wait for s3 consistency during event journaling and updates, avoiding the possibility that the previous batch of journals/updates are unavailable for read before the next batch is
processed.
> Confirm flashflood writes during journaling/update

- tests/test_events.py
This makes the `_upload_bundle` utility method available to additional events test classes.
> Refactor _upload_bundle in tests/test_events.py

- dss-api.yml
This fixes an issue with the API documentation. An improperly formatted string in the API documentation results in confusing output for the dcp-cli documentation:
Ref: "Named Arguments" section of dcp-cli documentation https://hca.readthedocs.io/en/latest/cli.html#put-subscription
Closes #443
> Fix API formatting issue

- daemons/dss-notify-v2/Readme.md
- dss/events/__init__.py
- tests/test_events.py
- tests/test_notify_v2.py
This adds `bundle_info` to the bundle metadata document, making it possible to filter JMESPath subscriptions on both bundle uuid and version.
```
{
"event_type: ...
"bundle_info" = {
'uuid': ...,
'version': ...
},
...
}
```
closes #2513
> Include `bundle_info` in bundle metadata document

- dss/events/__init__.py
Also, fail gracefully when attempting to delete non-existent event
> Include event logging info to aid debugging

- daemons/dss-notify-v2/app.py
- tests/test_notify_v2.py
This:
- verifies the existence of normal bundle keys and tombstoned bundle keys before attempting to build or retrieve the bundle metadata document.
- tests the refactored handler method
> Refactor notify v2 event handler

- .gitlab-ci.yml
- scripts/check_fusillade.py
This PR adds two steps to the CI/CD:
- run the `roles.json` file through a JSON linting step
- check the Fusillade roles specified in `roles.json` have been deployed to Fusillade correctly using `check_fusillade.py` script
The check fusillade script uses IAM functionality added in two other PRs.
**NOTE:** This is the third in a series of pull requests. This PR is made against the `chmreid-iam-list-roles-3` branch to make review easier but will ultimately be made against `master`.
> [Fusillade Check 3/3] Add Fusillade check, JSON linting steps to CI/CD

- .gitlab-ci.yml
- dss/operations/iam.py
- scripts/check_fusillade.py
- tests/test_operations.py
This PR adds the ability to list assets to the `dss-ops.py iam` script action.
**NOTE:** This is the second in a series of pull requests. This PR is made against the `chmreid-iam-list-roles-2` branch to make review easier but will ultimately be made against `master`.
> [Fusillade Check 2/3] Add list-users, list-groups, list-roles endpoints to dss-ops iam script

- .gitlab-ci.yml
- dss/operations/iam.py
- scripts/check_fusillade.py
- tests/test_operations.py
This PR refactors the dss-ops IAM action and associated tests.
- rearrange functions in dss ops iam to be used across more of the code
- reduce copypasta and multiple functions related to users/groups/roles into single function calls for "assets" with keyword indicating "asset type"
- pack up and parameterize redundant keyword arguments passed to tests
This is a refactor only
> [Fusillade Check 1/3] Refactor dss-ops iam script and tests

- dss-api.yml
- dss/api/bundles/__init__.py
When calling GET /bundles/all with the prefix `bundles/f` and `bundles/F`, the former gives search results and the latter does not.
Since we lowercase uuids for users when they submit them, we should also probably lowercase them when that user searches for that same uuid (or uuid prefix).
See https://github.com/HumanCellAtlas/data-store/issues/2643
> [easy] Lowercase uuid prefixes for GET /bundles/all.

- dss/operations/storage.py
- tests/test_operations.py
Allows reference lists to be built for bundle key
Enables us to build object references for tombstoned bundles
Connected to #2528
> DSS Operations: Bundle Reference List

- infra/dss-events-scribe/main.tf
This defines infrastructure that will be used for the forthcoming refactor of the DSS event journaling and update daemon:
- A scheduled CloudWatch event rule
- An SQS queue
- CloudWatch-SQS integration
connected to #2648
> Define cloudwatch rule and SQS queue

- tests/test_subscriptions.py
These pass locally for me so I'd like to see if this fixes our recent test failures:
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/-/jobs/58183
https://allspark.dev.data.humancellatlas.org/HumanCellAtlas/data-store/-/jobs/58162
> Eventually see dynamodb result for subscription owner.

- dss-api.yml
- dss/api/bundles/__init__.py
- tests/test_bundle.py
After speaking with @jessebrennan , this further checks syntax and adds tests for prefixes supplied to `GET /bundles/all`.
> [easy] Add tests for GET /bundles/all prefixes and syntax checking.

- infra/async_state_db/main.tf
- infra/buckets/gs.tf
- infra/buckets/s3.tf
- infra/collections_db/main.tf
- infra/domain/main.tf
- infra/dss-events-scribe/main.tf
- infra/elasticsearch/access_ips.tf
- infra/elasticsearch/main.tf
- infra/gcp_service_account/main.tf
- infra/subscription_v2_db/main.tf
Terraform generates 100 billion warnings since we updated to `0.12.16`.  This should address them and bring our scripts up to date.
Issue: #2671
> Update terraform files to address deprecation warnings.

- common.mk
So that we don't accidentally upgrade our system.  Behavior now looks like:
```(v3nv) quokka@qcore:~/update-terraform-warnings/data-store$ make plan-infra
common.mk:25: *** You must use Terraform v0.12.16, please check your terraform version..  Stop.```
> [easy] Add check for terraform version.

- .gitlab-ci-prod.yml
This adds calls to the setup fusillade and check fusillade script from `.gitlab-ci-prod.yml`.
Currently this maps the `prod` stage of DSS to the `production` stage of Fusillade. (I hope one day soon everyone in the DCP will use `prod`.)
Closes #2677
> Add setup/check fusillade steps to prod CI/CD

- dss/operations/iam.py
This updates the Fusillade stage names in the `FusilladeClient` class in `dss/operations/iam.py`. `s/production/prod`.
See https://github.com/HumanCellAtlas/fusillade/pull/366 for the PR that swapped out `prod` in place of `production` in fusillade.
> [easy] Change production to prod.

- chalice/build_deploy_config.sh
- iam/policy-templates/dss-lambda.json
Removes different IAM policies depending on deployment source.
Only updates IAM policies from non-CI environments (operator machines).
Addresses malformed IAM policy for dss-{stage} lambda. 
Connected To #2681 , #1973 , #1955
> DSS Infra: Chalice IAM Policy

- .codecov.yml
- .travis.yml
- README.md
Codecov has been returning weird results for some builds, usually
trending lower (saying that code coverage has dropped by some
ridiculous amount). I think this is because Codecov is getting
confused by all the different reports being uploaded - five from
the PR build, and another five from the branch build.
Here's an example of Codecov conflating reports from different
builds:
https://codecov.io/gh/HumanCellAtlas/data-store/commit/2fcdaa2c27de001e6a436371950d0caecdb40d3d/builds
Closes #2692
> [test] Disable codecov upload on PR builds

- dss/operations/iam.py
- dss/operations/lambda_params.py
- dss/operations/secrets.py
- dss/operations/util.py
For the secrets and lambda actions of dss-ops, there are some options that take a `--quiet` flag to suppress output to stdout to make it easier to pipe output to a JSON file or use as input for a subsequent step.
This PR refactors how these print statements happen by defining a `polite_print()` function that checks if the `--quiet` flag is present and only prints the message if it is not present.
> Use polite_print in secrets and lambda_params

- .codacy.yml
Codacy code quality checks are enabled for pull requests, but seem
to be inferring Python 2 from the codebase. For example, at time of
submission, checks for #2691 at https://app.codacy.com/manual/natanlao/data-store/pullRequest?prid=4686721
are showing fstrings as a syntax error.
This change to .codacy.yml should force Codacy to use Python 3.
> Force Codacy to use Python 3 for linting

- tests/fixtures/datafiles/example_bundle/project_0.json
- tests/sample_doc_tombstone.json
- tests/sample_v0_index_doc_tombstone.json
- tests/sample_vx_index_doc.json
- tests/sample_vx_index_doc_tombstone.json
- tests/test_checkout.py
- tests/test_operations.py
- tests/test_server.py
- tests/test_subscriptions.py
- tests/test_utils.py
Replaces generic emails in tests (e.g. `test@test.com`) with
test-specific placeholder emails to aid in the debugging process.
In general, I used a convention like:
{{ test_case_name }}@{{ test_suite_name }}.data.humancellatlas.org
I didn't touch tests/test_operations.py. It seemed to be fine. For propriety, here's the `ack`:
```
tests/test_operations.py
630:                ["fake-user@foo.bar", "another-fake-user@baz.wuz"],
692:                self.assertIn(IAMSEPARATOR.join(["fake-user@foo.bar", "fake-group-policy"]), output)
693:                self.assertIn(IAMSEPARATOR.join(["fake-user@foo.bar", "fake-role-policy"]), output)
694:                self.assertIn(IAMSEPARATOR.join(["another-fake-user@baz.wuz", "fake-group-2-policy"]), output)
695: …
```
> Use test-specific placeholder emails (closes #2665)

- dss/index/es/validator.py
Error:
```
[WARNING]	2019-12-19T01:55:16.4Z	42ae5d7c-5095-5257-b30e-0b088a27c26b	An exception occurred in retry.TX(name='index_bundle', {'bundle': <dss.index.bundle.Bundle object at 0x7efde976f898>}).
File "/var/task/domovoilib/dss/util/retry.py", line 207, in wrapper
return f(*args, **kwargs)
File "/var/task/domovoilib/dss/index/es/backend.py", line 44, in index_bundle
doc = BundleDocument.from_bundle(bundle)
File "/var/task/domovoilib/dss/index/es/document.py", line 123, in from_bundle
scrub_index_data(files, str(self.fqid))
File "/var/task/domovoilib/dss/index/es/validator.py", line 70, in scrub_index_data
extra_fields.append(fields_to_remove)
UnboundLocalError: local variable 'fields_to_remove' referenced before assignment
```
Seems to simply be an …
> [easy] Fix indent error.

- dss/api/bundles/__init__.py
- dss/api/collections.py
This moves fusillade usage from PUT/PATCH/DELETE /bundle to GET /collections.
> [easy] Move fusillade usage to a non-critical API endpoint.

- scripts/deploy_gcf.py
changes gcp deployment from `v1beta2` to `v1` to avoid deprecation issues.
> DSS INFRA: Update Google Cloud Function API

- dss/storage/bundles.py
- tests/infra/mock_storage_handler.py
- tests/test_storage.py
addresses bug where the first bundle shows up when enumerating multiple dead bundles. 
Connected To : #2723
> DSS API: enumerating consecutive dead bundles

- environment.prod
overwrites `DSS_AUTHORIZED_GOOGLE_PROJECT_DOMAIN_ARRAY` from environment file
Removes `human-cell-atlas-travis-test` project from authorized google domains, removing the ability for CI systems to upload to `dss-prod`
> DSS Security: Remove travis-test google project
